### ISSUE TITLE
Not able to set up another database server

### ISSUE THREAD

**Issue by Im-PJ** [dreamfactorysoftware/dreamfactory#10]
This is my .env config
DB_DRIVER=sqlsrv
DB_HOST=192.xx.xx.xx
DB_PORT=1433
DB_DATABASE=bitnamidb
DB_USERNAME=bitnami
DB_PASSWORD=bitnami@123

When I run `php artisan dreamfactory:setup` command, I get this error
`[InvalidArgumentException]                  
  Command "dreamfactory:setup" is not defined. `

If I open dreamfactory in browser it gives me error like  `MySQL server has gone away` which means its not picking my driver. I'm using DF2 beta-2

**Comment by jstablesdf** [comment]
Are you running the latest code release https://github.com/dreamfactorysoftware/dreamfactory/commit/a58248ddd8657ae2d0cdd3e9fa53919278605d41 ? The `dreamfactory:setup` command was recently implemented.

**Comment by Im-PJ** [comment]
@jstablesdf  Ok I dont think so. I'm running beta-2. I was following the doc which was updated recently. I will try with beta-4 and update. thanks.

**Comment by jstablesdf** [comment]
The GitHub instructions are for GitHub installs. You may encounter more than just a few differences if you're using Bitnami.

**Comment by Im-PJ** [comment]
@jstablesdf  So then this command won't work for bitnami installs? If not, then how to setup different db server for bitnami install.

**Comment by jstablesdf** [comment]
I don't know. Let me know how it works out for you!
