### ISSUE TITLE
scripting platform.api.get error

### ISSUE THREAD

**Issue by adixsyukri** [dreamfactorysoftware/dreamfactory#100]
I am unable to use platform.api.get from node js. It just throws error code 1.

If using Python, just setting pre-process to active, it just failed eventhough i didn't write any code.

**Comment by vinodhum** [comment]
Same here, I am getting same error with nodejs but only on event scripting

**Comment by vinodhum** [comment]
if you still getting this error try reinstalling dreamfactory or try cloud version
for me cloud version worked.

**Comment by drewpearce** [comment]
could no replicate
