### ISSUE TITLE
"Packages->Export Package" cannot export "events"

### ISSUE THREAD

**Issue by philicious** [dreamfactorysoftware/dreamfactory#102]
- the list displays two lines. But I'm only having one event script `user.session.post.post_process`
- the the lines dont have any description
![event_export](https://cloud.githubusercontent.com/assets/404412/17380288/c50d2bea-59c6-11e6-8e57-14a424a15225.PNG)

- when adding to package and then exporting, I get
![event_export2](https://cloud.githubusercontent.com/assets/404412/17380344/0708a196-59c7-11e6-9609-094e504b6bd0.PNG)

**Comment by df-arif** [comment]
@philicious, I confirmed that it is a bug in the UI. We will fix this. In the mean time you can still export your events by making a POST call to /api/v2/system/package with a payload like below...

    {
        "service":{
            "system":{
                "event": [
		    "db._table.contact_info.get.pre_process",
		    "db._table.contact.get.post_process"
                ]
            }
        }
    }

**Comment by philicious** [comment]
Thx @df-arif
Also see my other issue with package export that's more critical #95

**Comment by philicious** [comment]
I'm closing this as it seems to be fixed with DF 2.3.0

@df-arif correct me if I'm wrong

**Comment by leehicks** [comment]
You are correct. 2.3.0 changed/clarified the event scripting API resource. Now there is a separate resource for pulling generated event list (event) versus the scripts associated with those events (event_script). Package import supports the old format as well.
