### ISSUE TITLE
AWS SNS: All calls with {app_name} or {endpoint_name} as URL param are broken

### ISSUE THREAD

**Issue by philicious** [dreamfactorysoftware/dreamfactory#103]
All calls like `GET /push/app/{app_name}` are broken. Same for the {endpoint_name}

The problem is that you have to supply the full ARN like `arn:aws:sns:eu-central-1:123456789:app/GCM/foobar` which results in an URL like `api/v2/push/app/arn%3Aaws%3Asns%3Aeu-central-1%3A123456789%3Aapp%2FGCM%2Ffoobar` which leads to

`The requested URL /api/v2/push/app/arn:aws:sns:eu-central-1:123456789:app/GCM/foobar was not found on this server.`

So the encoding of the ARN is a problem. If you change webserver vhost to
`AllowEncodedSlashes On` (Apache) , then at least the calls with {endpoint_name} are working. However some with {app_name} are still broken as df-aws likely does sth wrong

(Reason: An ARN must have at least 6 elements, not 5) 

```
api/v2/push/app/arn%3Aaws%3Asns%3Aeu-central-1%3A123456789%3Aapp%2FGCM%2Ffoobar/endpoint

    "message": "Error executing &quot;GetEndpointAttributes&quot; on &quot;https://sns.eu-central-1.amazonaws.com&quot;; AWS HTTP error: Client error: `POST https://sns.eu-central-1.amazonaws.com` resulted in a `400 Bad Request` response:\n&lt;ErrorResponse xmlns=&quot;http://sns.amazonaws.com/doc/2010-03-31/&quot;&gt;\n  &lt;Error&gt;\n    &lt;Type&gt;Sender&lt;/Type&gt;\n    &lt;Code&gt;InvalidPara (truncated...)\n InvalidParameter (client): Invalid parameter: EndpointArn Reason: An ARN must have at least 6 elements, not 5 - &lt;ErrorResponse xmlns=&quot;http://sns.amazonaws.com/doc/2010-03-31/&quot;&gt;\n  &lt;Error&gt;\n    &lt;Type&gt;Sender&lt;/Type&gt;\n    &lt;Code&gt;InvalidParameter&lt;/Code&gt;\n    &lt;Message&gt;Invalid parameter: EndpointArn Reason: An ARN must have at least 6 elements, not 5&lt;/Message&gt;\n  &lt;/Error&gt;\n  &lt;RequestId&gt;6893163f-0c7e-527a-8f0e-461d820b12b3&lt;/RequestId&gt;\n&lt;/ErrorResponse&gt;\n",
    "code": 500,
    "trace": [
      "0 /opt/dreamfactory/vendor/dreamfactory/df-aws/src/Resources/SnsEndpoint.php(261): DreamFactory\\Core\\Aws\\Services\\Sns::translateException(Object(Aws\\Sns\\Exception\\SnsException))",
      "1 /opt/dreamfactory/vendor/dreamfactory/df-aws/src/Resources/SnsEndpoint.php(186): DreamFactory\\Core\\Aws\\Resources\\SnsEndpoint->retrieveEndpoint('foobar/endpoi...')",
      "2 [internal function]: DreamFactory\\Core\\Aws\\Resources\\SnsEndpoint->handleGET()",
```

**Comment by philicious** [comment]
I did some more testing meanwhile. 
Note: The list is based on having `AllowEncodedSlashes On` or alot calls will fail

**buggy:**
GET /push/app/{app_name}/endpoint  **// it only does work when appending trailing slash to ARN.**
POST /push/app/{app_name}/endpoint **// it only does work when appending trailing slash to ARN.**
(trailing slash not required by other calls and also not what ARN usually look like or are returned by calls)

**broken:**
GET /push/endpoint  **//should work like listEndpoints() but empty response. Also description wrong,from GET /push/endpoint/{endpoint_name}**

**working:**
POST /push **//misses required attribute Message in example value**
GET /push/topic
POST /push/topic
DELETE /push/topic/{topic_name}
GET /push/topic/{topic_name}
POST /push/topic/{topic_name}  **//misses required attribute Message in example value**
PUT /push/topic/{topic_name}
GET /push/topic/{topic_name}/subscription
POST /push/topic/{topic_name}/subscription
GET /push/subscription
POST /push/subscription
DELETE /push/subscription/{sub_name}
GET /push/subscription/{sub_name}
GET /push/app
POST /push/app **//misses required attribute "Attributes" in example value**
GET /push/app/{app_name}
PUT /push/app/{app_name}  **//misses required attributes "Attributes" and "Application" in example value**
POST /push/endpoint
GET /push/endpoint/{endpoint_name} 
POST /push/endpoint/{endpoint_name} **//misses required attribute Message in example value**

**untested:**
PUT /push/subscription/{sub_name}
DELETE /push/app/{app_name}
DELETE /push/endpoint/{endpoint_name}
PUT /push/endpoint/{endpoint_name}

Also the example values are for some API endpoints missing entirely or have required attributes missing. The comments above are only those I noticed.

**Comment by df-arif** [comment]
@philicious, I confirmed the issues that you mentioned here. We will fix the ARN encoding issue as well as the broken APIs in future release/hot fixes. Thanks for bringing this to our attention.

**Comment by philicious** [comment]
@df-arif cool :) do you happen to have a rough ETA ? Only asking as we are currently implementing PushNotifications and might need the broken endpoints. (However I think we can workaround then, fingers-crossed)

PS: You definitely need `AllowEncodedSlashes On` in webserver config which also df-docker (and likely Bitnami) needs. And your wiki instructions for the various manual install methods

**Comment by aabowen** [comment]
@philicious we are working on it now - it's in progress. Should have an update for you very soon. Thanks for your patience!

**Comment by philicious** [comment]
so after v2.4.1 changelog claimed to have fixed AWS SNS service, I finally did some testing again and can verify that the 3 completly broken endpoints are now working !

**However** you definitely need `AllowEncodedSlashes On` (or little safer `AllowEncodedSlashes NoDecode`) in your webserver config! or every endpoint with {app_name} or {endpoint_name} wont work. 
I guess you want to add that fact to http://wiki.dreamfactory.com/DreamFactory/Tutorials/Sending_Push_Notifications and maybe also to the various setup instructions.

PS: the example values in API Docs are still missing mandatory attributes as mentioned above but as thats a minor problem, I'm closing the issue

**Comment by libarra** [comment]
Hi @philicious, great Info!
I have a questions: I'm using the bitnami DreamFactory VM (debian), where is the httpd.conf file to add the "AllowEncodedSlashes On" variable ?

Thanks in advance.

**Comment by philicious** [comment]
hi @libarra 
I never used the Bitnami VMs for Dreamfactory but I just checked and its in `/opt/bitnami/apache2/conf` and its missing the `AllowEncodedSlashes` option.

I didnt check if this still is a problem for DFs AWS SNS component but I would assume so

**Comment by libarra** [comment]
@philicious thanks for your response.

Yes the problem (slashes) still in the DF v2.9, I tried adding the AllowEncodedSlashes in 2 files: vhostsxxxxxx.conf and in the apache httpd.conf. But both without success.

 I will try to test with a tool like postman to direct connect with the AWS SNS service, but this is very tricky.

Luis.

**Comment by philicious** [comment]
@libarra I did some more digging thru Bitnamis confusing and unnecessarily split up snow-flaky config files

apache is started with
`/opt/bitnami/apache2/conf/httpd.conf`
which includes
`/opt/bitnami/apache2/conf/bitnami/bitnami.conf`
which includes in the VirtualHost block
`/opt/bitnami/apache2/conf/bitnami/bitnami-apps-prefix.conf`
which includes 
`/opt/bitnami/apps/dreamfactory/conf/httpd-prefix.conf`
which sets DocumentRoot for DF and includes
`/opt/bitnami/apps/dreamfactory/conf/httpd-app.conf`
which has Directory directive et.al.

so you could add the `AllowEncodedSlashes` directive in the `/opt/bitnami/apps/dreamfactory/conf/httpd-app.conf` file at top level and it should work (i.e. dont nest it under any of the existing directives in there as its context is either at Server block level or VirtualHost level)

When I was working with DF and debugging the AWS SNS problems I had seen, I 
- tailed dreamfactorys logfile
- used the Swagger UI "API Docs" in DF GUI and played with the CURL commands it showed
- used tcpdump / ssldump / WireShark to see which requests are actually going over the network
- checked AWS SNS docs to see how they should be called

Maybe this helps you getting things to work on your side

**Comment by libarra** [comment]
Thanks @philicious I will try it!

Luis.
