### ISSUE TITLE
bigint in table but return as string in the get method.

### ISSUE THREAD

**Issue by hoswey** [dreamfactorysoftware/dreamfactory#106]
I have a table below,  the channel_uid is bigint,  but it cast to string when I use the rest api to get the record.

+-------------+------------+------+-----+---------+-------+
| Field       | Type       | Null | Key | Default | Extra |
+-------------+------------+------+-----+---------+-------+
| year        | int(11)    | NO   | PRI | 0       |       |
| month       | int(11)    | NO   | PRI | 0       |       |
| channel_uid | bigint(20) | NO   | PRI | 0       |       |
| mau         | int(11)    | YES  |     | NULL    |       |
+-------------+------------+------+-----+---------+-------+

{
  "resource": [
    {
      "year": 2016,
      "month": 8,
      "channel_uid": "103453445",
      "mau": 112512
    }
  ]
}

**Comment by drewpearce** [comment]
BIGINT has to be cast to a string because that's how PHP handles them.

**Comment by drewpearce** [comment]
Or rather it's more precise to say, that in order to get a consistent conversion from PHP to JSON and back we handle them by casting to string.
