### ISSUE TITLE
DF 2.3.0: "Packages->Export Package" cannot export "lookup" 

### ISSUE THREAD

**Issue by philicious** [dreamfactorysoftware/dreamfactory#109]
after fixing #102 it seems you introduced a regression bug: 

with DF 2.3.0 you cannot export lookups anymore. When selecting them the "Select Item(s) to Export " stays empty

Update: When reloading the page over and over, it randomly shows the lookups tho. same for email_templates. cant tell under which circumstances it works and when not.

Update2: Also the "Type" combobox is weird. It randomly only shows "system" but then it again shows "system + MySQL + file storage"

I think the package feature needs some proper testing and fixes, theres also #95 open and maybe more problems with other service types

**Comment by philicious** [comment]
Seems like flushing the cache right before going to the "Package" tab, solves it. (but not #95)

**Comment by philicious** [comment]
@leehicks @aabowen any chance this will be fixed? as its really annoying :/

**Comment by todda48** [comment]
Exporting CORS, email templates, and lookups has been fixed on develop branch and the fix will be in 2.4.

**Comment by philicious** [comment]
verified to be fixed with 2.4.1
