### ISSUE TITLE
Custom Scripting Service not saving Service Definition

### ISSUE THREAD

**Issue by kimpastro** [dreamfactorysoftware/dreamfactory#11]
Hello,
I've tested this on a Windows and MacOS installation, both presented the same problem.

The routine:
Services > Create > Custom Scripting Service. Tab > Service Definition

Fill all fields then save. Everything on that tab just disappears, using Chrome Debug to watch transactions, all data is being sent and no error occurs.

What could be happening? What could I debug to have more information about that?
Thanks.

**Comment by jstablesdf** [comment]
I don't see the Editor or JSON Editor working on custom scripting services in the current release. It should be functional in the next release. Are you using the Editor or the JSON Editor?

**Comment by kimpastro** [comment]
I'm using Editor. 
In 2.0.1 release the JSON Editor is not allowed to write, just read what Editor generate.

**Comment by jstablesdf** [comment]
I don't believe either works currently for custom scripting services, only for remote web services. In the next release both will work for custom scripting services.

**Comment by kimpastro** [comment]
Alright, thanks.

**Comment by drewpearce** [comment]
As of DF 2.0.4, custom script service definitions are editable.

**Comment by happyshows** [comment]
Hi, I'm on 2.0.4, tried editor and jsoneditor, neither can be saved :S

**Comment by drewpearce** [comment]
can you provide more details? what type of service are you editing, what operating system, what install method, etc.?
