### ISSUE TITLE
Error in MySQL syntax when accessing API

### ISSUE THREAD

**Issue by stefkin** [dreamfactorysoftware/dreamfactory#110]
I created connection to existing MySQL database and headed out to API Docs tab to test it.
Apparently, requests fail with the following message:

"SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.app' at line 1 (SQL: SHOW FULL TABLES FROM my_db_name.app)",

The syntax is indeed invalid, why does the generated code contain .app?
Please note that /my_db_name endpoint is working fine, but all other endpoints are giving the above error.

**Comment by drewpearce** [comment]
Hi Stefkin. We generally reserve Github for filing bugs and feature requests. For support requests, head over to our community forums -- community.dreamfactory.com
