### ISSUE TITLE
df-soap: array_key_exists() error breaking API Docs and all other services !

### ISSUE THREAD

**Issue by philicious** [dreamfactorysoftware/dreamfactory#111]
```
500 : {"error":{"context":null,
"message":"array_key_exists(): The first argument should be either a string or an integer",
"code":500,
"trace":["
0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'array_key_exist...', '/opt/dreamfacto...', 246, Array)","
1 /opt/dreamfactory/vendor/dreamfactory/df-soap/src/Services/Soap.php(246): array_key_exists(false, Array)","
2 /opt/dreamfactory/vendor/dreamfactory/df-soap/src/Services/Soap.php(180): DreamFactory\\Core\\Soap\\Services\\Soap->getTypes(false)","
3 /opt/dreamfactory/vendor/dreamfactory/df-soap/src/Services/Soap.php(424): DreamFactory\\Core\\Soap\\Services\\Soap->getFunctions()","
4 /opt/dreamfactory/vendor/dreamfactory/df-soap/src/ServiceProvider.php(35): DreamFactory\\Core\\Soap\\Services\\Soap->buildApiDocInfo()"
```

@leehicks I found another problem with df-soap (using latest 	0.4.1 with DF 2.3.0):
The above error is shown in API Docs. Nothing in dreamfactory.log
I also see similar error in Services when re-adding the SOAP service. 
Also the "Services" stays empty then and shows "You have no Services!" , It also breaks the API entirely = no service working anymore.
I verified all services are still in the DB. So no data loss involved.

**Comment by philicious** [comment]
@leehicks I mailed you the offending WSDL.

After a bit of hackish logging/dumping I think I found a trivial fix:

The problem is with https://github.com/dreamfactorysoftware/df-soap/blob/master/src/Services/Soap.php#L218-L221 as the $name has `complexObjectArray` in it, misleading the stripos/strstr

Adding trailing semicolons to the `complexObjectArray` string

```
                    if (false !== stripos($type, 'complexObjectArray;')) {
                        // declared as "type complexObjectArray"
                        $type = strstr(trim($type), ' complexObjectArray;', true);
                        $structures[$name] = [$type];
                    }
```

seems to fix it. API Docs are working again and also the "Services" are shown again and working

**Comment by leehicks** [comment]
dreamfactory/df-soap tag 0.4.2 fixes this issue.
@philicious This includes your fix plus a space in front for consistency.

To update until the composer.lock main file is updated with the next release, use the following...
`composer update dreamfactory/df-soap --no-dev`

**Comment by philicious** [comment]
@leehicks FYI: working fine as expected. thanks again :)
