### ISSUE TITLE
[Request] DF Script Repository

### ISSUE THREAD

**Issue by zerox1212** [dreamfactorysoftware/dreamfactory#112]
Can we make a script-example repository for DF scripting examples and help?

The script examples on the official wiki are not well developed. If we had a repository to store example scripts it would be much easier for the community to contribute common use scripts.

**Comment by leehicks** [comment]
Sounds like a good idea. [Here](https://github.com/dreamfactorysoftware/example-scripts) you go. We will try to add some common scenarios we see for starters. Feel free to send a pull request with any that you would like to see.
