### ISSUE TITLE
API Docs are missing the service description

### ISSUE THREAD

**Issue by philicious** [dreamfactorysoftware/dreamfactory#116]
Since 2.2.1 I think but for sure since 2.3.0 the API Docs dont show the description of the service anymore.

Minor UX bug.

**Comment by philicious** [comment]
still the case with 2.4.1. is this on purpose? then pls close this issue

**Comment by noogen** [comment]
I'm on 2.4.2 and it's working fine for me.  A couple of quirky things that I did notice while on my slower computer:
1) The API doc either popup script freeze message (Firefox) or crash the browser (Chrome).  Javascript performance issue.  Maybe swagger need to be updated?
2) JSON custom API definition would save but YAML would not save. 

This does not happen on my faster computer.

**Comment by todda48** [comment]
@philicious Starting in 2.8.1 there is a new UI for the API Docs that shows the services in table format. This includes the description.

@noogen Starting in 2.8.1 you can only select a single service at a time. This improves the loading time and navigation of the API docs. The issue with saving YAML has been fixed and will be in the next release 2.9.0 coming out in about 2 weeks.
