### ISSUE TITLE
PUT does sometimes return empty array, even though the request does update in db

### ISSUE THREAD

**Issue by tvarsis** [dreamfactorysoftware/dreamfactory#117]
This applies to PUT/PATCH requests. If I send a request to a table PUT endpoint passing in this body:

```
{
  "resource": [
    {
      "name": "oldvalue"
    }
  ],
  "filter": "name=oldvalue"
}
```

I will get this response (200 code):

```
{
  "resource": [
    {
      "id": 1320
    }
  ]
}
```

But if I send in this body:

```
{
  "resource": [
    {
      "name": "NEWvalue"
    }
  ],
  "filter": "name=oldvalue"
}
```

The database gets updated as it should in the DB and I still get a 200 code as response, but the response body now looks like this:

```
{
  "resource": []
}
```

It does not matter if I try to add fields that should be returned. The resource is always and empty array.

**Comment by Paulodev** [comment]
you tried pass filter in query string

ex: http://domain/api/v2/service/_table/table_name?filter=name%3D+oldvalue

**Comment by tvarsis** [comment]
It is broken for both ways to pass in filters.

**Comment by Paulodev** [comment]
what version the Dreamfactory?

**Comment by tvarsis** [comment]
2.3.0

**Comment by Paulodev** [comment]
Eu testei a requeste e realmente esta acontencendo, tanto em PUT/PATCH o retorno da request vem um array vázio. bom agora e esperar um dos responsáveis pelo projeto verificar.

Me desculpe por não ajudar voce.

**Comment by df-arif** [comment]
@tvarsis , I tried to duplicate the issue you are having but couldn't. What type of db service you are using?

**Comment by tvarsis** [comment]
PostgreSQL

**Comment by drewpearce** [comment]
Could not replicate
