### ISSUE TITLE
OAuth authentication with external Identity server ?

### ISSUE THREAD

**Issue by jamsheer-thottathil** [dreamfactorysoftware/dreamfactory#118]
Is it possible to provide oAuth  authentication with external identity server rather than face book ,git hub etc.

**Comment by razakpm** [comment]
I'm also looking solution for the same , I prefer to authenticate with forgerock or CAS.

**Comment by jlpellicer** [comment]
Same here. I have my oAuth 2 server and would like to use it to authenticate my users.

**Comment by drewpearce** [comment]
In the next release we will be adding support for OpenID Connect which (among other things) will allow easy integration with 3rd party OAuth providers.

**Comment by drewpearce** [comment]
added in 2.7.0
