### ISSUE TITLE
Error in MySQL syntax when add new Column in existing table 

### ISSUE THREAD

**Issue by Navarathinam** [dreamfactorysoftware/dreamfactory#119]
When add new column to existing table via "**Schema**" menu in **Admin**,  getting MySQL syntax error.

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '1' at line 1 (SQL: 1)

I am using DF **2.3.0** in google cloud platform.

How **log** generated **MySQL query** and how to resolve this?

**Comment by drewpearce** [comment]
You should not be seeing this issue in later versions. If you are it is likely not a bug. We generally reserve Github for filing bugs and feature requests. For support requests, head over to our community forums -- community.dreamfactory.com
