### ISSUE TITLE
Security problem

### ISSUE THREAD

**Issue by meiti** [dreamfactorysoftware/dreamfactory#12]
I have 2 instances of dreamfactory v2 on my Debian, in the following directories:
1. /var/www/html/df1
2. /var/www/html/df2

Now, I can write a custom php script on df1 and read content of .env in df2 root directory and retrieve DB_DATABASE, DB_USERNAME, DB_PASSWORD and ...

My simple script:
return file_get_contents("/var/www/html/df2/.env");

How can I solve this problem?

**Comment by giano** [comment]
It's a common problem when running different services on the same machine. 

The most "clean" and secure way is to create 2 different non admin users, with home directory and such, limited access to system directories, install DF in that home directory and run DF (as well as any other service you may need) with that accounts.

So any user will only have access to his environment.

Or just go paravirtual with Docker :)

**Comment by drewpearce** [comment]
PHP scripting is not sandboxed like V8 is. Make sure you secure your dreamfactory instance well if you intend to use PHP.
