### ISSUE TITLE
GUI issue when creating table

### ISSUE THREAD

**Issue by przemek-pl** [dreamfactorysoftware/dreamfactory#120]
Admin Application Version: 2.3.1
DreamFactory Version: 2.3.0
DB: MySQL

When I'm trying to create new table (Schema -> chose service -> Create) form for table shows. After new column is added (Fields-> Add Field) and filling form and clicking "Save" I got: prompt: "Continue without saving?". Confirmation closes only prompt but form for new field is still visible, changes are not applied.
Similar situation is when modifying existing table. Saving after new field is added updates table schema but it does not go back to "table" overview. In order to do this you have to change tab (go to "Data" for example) and switch back to "Schema".

**Comment by drewpearce** [comment]
This issue is logged internally as DF-906. It should be addressed soon.

**Comment by drewpearce** [comment]
This issue is logged internally as DF-906. It should be addressed in an upcoming development sprint.

**Comment by drewpearce** [comment]
This issue was resolve in the 2.4.2 release.
