### ISSUE TITLE
smpt-mail template bug.

### ISSUE THREAD

**Issue by far-fetched** [dreamfactorysoftware/dreamfactory#122]
Email service doesn't use appropriate template, when adding it in payload (body). Only works when appending template via parameter. Link:
http://community.dreamfactory.com/t/issue-with-custom-email-template/1906/8

**Comment by Paulodev** [comment]
+1

**Comment by df-arif** [comment]
Fixed. https://github.com/dreamfactorysoftware/df-core/commit/94c96cac5ac828944dd450c43c45f754e7f0f34b

Will be available in the next release.
