### ISSUE TITLE
CORS settings enquiry SQL query select * from "cors_config" where enabled = 1; not working for PostgreSQL

### ISSUE THREAD

**Issue by abhinavg7** [dreamfactorysoftware/dreamfactory#123]
Dreamfactory 2.3.0-4 instance queries its system database(which in my case is postgresql 9.5.3-1) using the below SQL query for CORS entries :
**select \* from "cors_config" where enabled = 1;**
_**which is not working in case of PostgreSQL**_, and dsp treats the output of this query as no CORS headers are enabled.

There is a table named "cors_config" created by dreamfactory setup, in which cors entries are stored for that particular dreamfactory instance. 

There is a column/field in this table named 'enabled' of boolean type(in case of PostgreSQL) with default value true. When a admin user creates a cors entry through admin console, that entry is stored as a record in cors_config table. 

**_This SQL query should be (in case of postgresql):_**

**select \* from "cors_config" where enabled = '1';    or
select \* from "cors_config" where enabled = TRUE;**   (Standard SQL) or
select \* from "cors_config" where enabled = 1::BOOLEAN; or
select \* from "cors_config" where enabled = CAST( 1 AS BOOLEAN );\

**Comment by abhinavg7** [comment]
Is this issue resolved in later versions of DSP?

**Comment by leehicks** [comment]
This was fixed when we upgraded the CORS package in October with this [change](https://github.com/dreamfactorysoftware/df-core/commit/a48655db4a03b9719421d4aa8390430877a39f46).
Available in the 2.4.x DreamFactory builds.
