### ISSUE TITLE
OAuth error

### ISSUE THREAD

**Issue by GumnutFarmer** [dreamfactorysoftware/dreamfactory#124]
Hi,

I am getting the error:

> Laravel\Socialite\Two\AbstractProvider and DreamFactory\Core\OAuth\Components\DfOAuthTwoProvider define the same property ($request) in the composition of DreamFactory\Core\OAuth\Components\GoogleProvider. This might be incompatible, to improve maintainability consider using accessor methods in traits instead. Class was composed

Trace:

> {"error":{"context":null,"message":"Laravel\Socialite\Two\AbstractProvider and DreamFactory\Core\OAuth\Components\DfOAuthTwoProvider define the same property ($request) in the composition of DreamFactory\Core\OAuth\Components\GoogleProvider. This might be incompatible, to improve maintainability consider using accessor methods in traits instead. Class was composed","code":500,"trace":["0 /srv/api.monitre.com.au/df2/vendor/dreamfactory/df-oauth/src/Components/GoogleProvider.php(41): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2048, 'Laravel\\Sociali...', '/srv/api.monitr...', 41, Array)","1 /srv/api.monitre.com.au/df2/vendor/composer/ClassLoader.php(412): include('/srv/api.monitr...')","2 /srv/api.monitre.com.au/df2/vendor/composer/ClassLoader.php(301): Composer\Autoload\includeFile('/srv/api.monitr...')","3 [internal function]: Composer\Autoload\ClassLoader->loadClass('DreamFactory\\Co...')","4 /srv/api.monitre.com.au/df2/vendor/dreamfactory/df-oauth/src/Services/Google.php(22): spl_autoload_call('DreamFactory\\Co...')","5 /srv/api.monitre.com.au/df2/vendor/dreamfactory/df-oauth/src/Services/BaseOAuthService.php(45): DreamFactory\Core\OAuth\Services\Google->setProvider(Array)","6 /srv/api.monitre.com.au/df2/vendor/dreamfactory/df-oauth/src/ServiceProvider.php(81): DreamFactory\Core\OAuth\Services\BaseOAuthService->__construct(Array)","7 [internal function]: DreamFactory\Core\OAuth\ServiceProvider->DreamFactory\Core\OAuth\{closure}(Array, 'google')","8 /srv/api.monitre.com.au/df2/vendor/dreamfactory/df-core/src/Services/ServiceType.php(181): call_user_func(Object(Closure), Array, 'google')","9 /srv/api.monitre.com.au/df2/vendor/dreamfactory/df-core/src/Services/ServiceManager.php(245): DreamFactory\Core\Services\ServiceType->make('google', Array)","10 /srv/api.monitre.com.au/df2/vendor/dreamfactory/df-core/src/Services/ServiceManager.php(189): DreamFactory\Core\Services\ServiceManager->makeService('google')","11 /srv/api.monitre.com.au/df2/bootstrap/cache/compiled.php(6418): DreamFactory\Core\Services\ServiceManager->getService('google')","12 /srv/api.monitre.com.au/df2/vendor/dreamfactory/df-core/src/Resources/UserSessionResource.php(32): Illuminate\Support\Facades\Facade::__callStatic('getService', Array)","13 /srv/api.monitre.com.au/df2/vendor/dreamfactory/df-core/src/Resources/UserSessionResource.php(32): DreamFactory\Core\Facades\ServiceManager::getService('google')","14 [internal function]: DreamFactory\Core\Resources\UserSessionResource->handleGET()","15 /srv/api.monitre.com.au/df2/vendor/dreamfactory/df-core/src/Components/RestHandler.php(327): call_user_func(Array)","16 /srv/api.monitre.com.au/df2/vendor/dreamfactory/df-core/src/Components/RestHandler.php(185): DreamFactory\Core\Components\RestHandler->processRequest()","17 /srv/api.monitre.com.au/df2/vendor/dreamfactory/df-core/src/Components/RestHandler.php(243): DreamFactory\Core\Components\RestHandler->handleRequest(Object(DreamFactory\Core\Utility\ServiceRequest), '')","18 /srv/api.monitre.com.au/df2/vendor/dreamfactory/df-core/src/Components/RestHandler.php(160): DreamFactory\Core\Components\RestHandler->handleResource(Array)","19 /srv/api.monitre.com.au/df2/vendor/dreamfactory/df-core/src/Services/BaseRestService.php(89): DreamFactory\Core\Components\RestHandler->handleRequest(Object(DreamFactory\Core\Utility\ServiceRequest), 'session')","20 /srv/api.monitre.com.au/df2/bootstrap/cache/compiled.php(17202): DreamFactory\Core\Services\BaseRestService->handleRequest(Object(DreamFactory\Core\Utility\ServiceRequest), 'session')","21 /srv/api.monitre.com.au/df2/bootstrap/cache/compiled.php(17163): DreamFactory\Http\Controllers\RestController->handleService('v2', 'user', 'session')","22 [internal function]: DreamFactory\Http\Controllers\RestController->handleGET('v2', 'user', 'session')","23 /srv/api.monitre.com.au/df2/bootstrap/cache/compiled.php(9138): call_user_func_array(Array, Array)","24 /srv/api.monitre.com.au/df2/bootstrap/cache/compiled.php(9200): Illuminate\Routing\Controller->callAction('handleGET', Array)","25 /srv/api.monitre.com.au/df2/bootstrap/cache/compiled.php(9180): Illuminate\Routing\ControllerDispatcher->call(Object(DreamFactory\Http\Controllers\RestController), Object(Illuminate\Routing\Route), 'handleGET')","26 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))","27 /srv/api.monitre.com.au/df2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))","28 /srv/api.monitre.com.au/df2/bootstrap/cache/compiled.php(17381): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))","29 [internal function]: DreamFactory\Http\Middleware\AccessCheck->handle(Object(Illuminate\Http\Request), Object(Closure))","30 /srv/api.monitre.com.au/df2/bootstrap/cache/compiled.php(9677): call_user_func_array(Array, Array)","31 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))","32 /srv/api.monitre.com.au/df2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))","33 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))","34 /srv/api.monitre.com.au/df2/bootstrap/cache/compiled.php(9662): call_user_func(Object(Closure), Object(Illuminate\Http\Request))","35 /srv/api.monitre.com.au/df2/bootstrap/cache/compiled.php(9181): Illuminate\Pipeline\Pipeline->then(Object(Closure))","36 /srv/api.monitre.com.au/df2/bootstrap/cache/compiled.php(9168): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(DreamFactory\Http\Controllers\RestController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'handleGET')","37 /srv/api.monitre.com.au/df2/bootstrap/cache/compiled.php(8238): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'DreamFactory\\Ht...', 'handleGET')","38 /srv/api.monitre.com.au/df2/bootstrap/cache/compiled.php(8225): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))","39 /srv/api.monitre.com.au/df2/bootstrap/cache/compiled.php(7939): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))","40 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))","41 /srv/api.monitre.com.au/df2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))","42 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))","43 /srv/api.monitre.com.au/df2/bootstrap/cache/compiled.php(9662): call_user_func(Object(Closure), Object(Illuminate\Http\Request))","44 /srv/api.monitre.com.au/df2/bootstrap/cache/compiled.php(7940): Illuminate\Pipeline\Pipeline->then(Object(Closure))","45 /srv/api.monitre.com.au/df2/bootstrap/cache/compiled.php(7931): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))","46 /srv/api.monitre.com.au/df2/bootstrap/cache/compiled.php(7921): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))","47 /srv/api.monitre.com.au/df2/bootstrap/cache/compiled.php(2419): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))","48 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))","49 /srv/api.monitre.com.au/df2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))","50 /srv/api.monitre.com.au/df2/app/Http/Middleware/AuthCheck.php(183): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))","51 [internal function]: DreamFactory\Http\Middleware\AuthCheck->handle(Object(Illuminate\Http\Request), Object(Closure))","52 /srv/api.monitre.com.au/df2/bootstrap/cache/compiled.php(9677): call_user_func_array(Array, Array)","53 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))","54 /srv/api.monitre.com.au/df2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))","55 /srv/api.monitre.com.au/df2/vendor/barryvdh/laravel-cors/src/HandleCors.php(34): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))","56 [internal function]: Barryvdh\Cors\HandleCors->handle(Object(Illuminate\Http\Request), Object(Closure))","57 /srv/api.monitre.com.au/df2/bootstrap/cache/compiled.php(9677): call_user_func_array(Array, Array)","58 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))","59 /srv/api.monitre.com.au/df2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))","60 /srv/api.monitre.com.au/df2/bootstrap/cache/compiled.php(17483): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))","61 [internal function]: DreamFactory\Http\Middleware\FirstUserCheck->handle(Object(Illuminate\Http\Request), Object(Closure))","62 /srv/api.monitre.com.au/df2/bootstrap/cache/compiled.php(9677): call_user_func_array(Array, Array)","63 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))","64 /srv/api.monitre.com.au/df2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))","65 /srv/api.monitre.com.au/df2/bootstrap/cache/compiled.php(13188): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))","66 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))","67 /srv/api.monitre.com.au/df2/bootstrap/cache/compiled.php(9677): call_user_func_array(Array, Array)","68 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))","69 /srv/api.monitre.com.au/df2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))","70 /srv/api.monitre.com.au/df2/bootstrap/cache/compiled.php(11678): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))","71 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))","72 /srv/api.monitre.com.au/df2/bootstrap/cache/compiled.php(9677): call_user_func_array(Array, Array)","73 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))","74 /srv/api.monitre.com.au/df2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))","75 /srv/api.monitre.com.au/df2/bootstrap/cache/compiled.php(12927): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))","76 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))","77 /srv/api.monitre.com.au/df2/bootstrap/cache/compiled.php(9677): call_user_func_array(Array, Array)","78 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))","79 /srv/api.monitre.com.au/df2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))","80 /srv/api.monitre.com.au/df2/bootstrap/cache/compiled.php(12864): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))","81 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))","82 /srv/api.monitre.com.au/df2/bootstrap/cache/compiled.php(9677): call_user_func_array(Array, Array)","83 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))","84 /srv/api.monitre.com.au/df2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))","85 /srv/api.monitre.com.au/df2/bootstrap/cache/compiled.php(3286): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))","86 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))","87 /srv/api.monitre.com.au/df2/bootstrap/cache/compiled.php(9677): call_user_func_array(Array, Array)","88 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))","89 /srv/api.monitre.com.au/df2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))","90 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))","91 /srv/api.monitre.com.au/df2/bootstrap/cache/compiled.php(9662): call_user_func(Object(Closure), Object(Illuminate\Http\Request))","92 /srv/api.monitre.com.au/df2/bootstrap/cache/compiled.php(2366): Illuminate\Pipeline\Pipeline->then(Object(Closure))","93 /srv/api.monitre.com.au/df2/bootstrap/cache/compiled.php(2350): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))","94 /srv/api.monitre.com.au/df2/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))","95 {main}"]}}

Any help appreciated.

**Comment by df-arif** [comment]
Hi @GumnutFarmer, I wasn't able to reproduce this error while trying to use the google OAuth service. I need more information to troubleshoot this further. 

At which point you get this error? While provisioning the service or while using the service? Any specific API call? Also which version of PHP you are using and is your PHP Notices turned on? If your Notices are turned on try turning them off and see it it resolves it. 

I tried to reproduce this using PHP 7.0.8 and all Errors turned on including Notices.

**Comment by dbykadorov** [comment]
I have the same issue after setting up facebook service by this article: http://blog.dreamfactory.com/using-dreamfactory-2.0-with-oauth-services

I'm using php 5.6, and have tried DF 2.3, then 2.4 with same result.

@df-arif What information you need to investiogation? Here you can see API response: http://pastebin.com/dKVmHGCu

**Comment by df-arif** [comment]
@dbykadorov,  just confirmed that this error is happening on PHP 5.6 but not on PHP 7. We will fix this for PHP 5.6. In the meantime, update to PHP 7 to resolve this issue if that is an option for you.

**Comment by dbykadorov** [comment]
@df-arif Thank you for information!

**Comment by df-arif** [comment]
This is fixed. Will be available in the next release.
