### ISSUE TITLE
Platform.api not working correctly in events scripts DF 2.3.1

### ISSUE THREAD

**Issue by Paulodev** [dreamfactorysoftware/dreamfactory#125]
Hello!
I'm having problems with platform.api using a service-remote DF 2.3.1:

**1 - Do not respect the headers of config service called**

```
**Service Config Header**
     Content-type: application / json

**Output in event-script**
     platform.api.put form-data`
```

**2 - Passed Parameters of the request source**

```
     **Request**
     Url= "domain/api/v2/my-service/_table/table-name?filter=attr=value"
     **Script**
     platform.api.put('my-remote-service?user_id=value', payload);
     **Output**
     Url= 'my-remote-service?filter=attr=value' 
     // user_id is removed by DF and passed the filter of first request in my query
```

I'm tried with V8 script

**Comment by drewpearce** [comment]
Beginning in DF 2.4 the options component of the platform resource was refactored and also a feature was added to let you put parameters in the options object as well. http://wiki.dreamfactory.com/DreamFactory/Features/Scripting#The_Platform_Resource
This should resolve this issue.

**Comment by Paulodev** [comment]
thanks @drewpearce
