### ISSUE TITLE
Deleting a Role that is assigned to one or more Application break the actual instance

### ISSUE THREAD

**Issue by luckv** [dreamfactorysoftware/dreamfactory#127]
After I had just installled dreamfactory locally I to set up a connection **Service** to a remote mysql server and a **Role** that granted all rights on any endpoints. Then I assigned that **Role** as the default for all **Application**s and then I deleted it. Istantly some error messages compared, wich I can't remember exactly, and I wasn't able to perform any other action then. So I tried to log out and to re-login but the result was that I couldn't access the admin page, or take any action, no longer.
I think this problem could be related with foreign key integrity. When a **Role** is deleted dreamfactory does not check that there isn't any foreign key that points to it.

**Comment by drewpearce** [comment]
No longer an issue.
