### ISSUE TITLE
DF 2.4.0: error on GET /user/session 

### ISSUE THREAD

**Issue by GabrielStetco** [dreamfactorysoftware/dreamfactory#128]
After updating from 2.3.1 to 2.4.0 I get this error when trying to get the user session : "The ID of the user was not recognized"
This is the result:

```
{
"error": {
"context": null,
"message": "The ID of the user was not recognized.",
"code": "sessGetPP0s01"
}
}
```

This is happening even if I try directly being logged in the API Docs.
The app is installed from github on an nginx/php7 instance.

Please let me know if you need additional information.
Thanks

**Comment by philicious** [comment]
works for me in API Docs via `...api/v2/user/session`

**Comment by drewpearce** [comment]
Unable to duplicate issue. Likely user error/configuration/upgrade issue. Please consult the DreamFactory community forums for help and support, as we reserve Github issue for reporting bugs and feature requests.

**Comment by GabrielStetco** [comment]
I confirm that this related to an upgrade issue
