### ISSUE TITLE
problem: Array field converted to Object

### ISSUE THREAD

**Issue by topvis** [dreamfactorysoftware/dreamfactory#133]
Dreamfactory version 2.3.1-0
Database: mongodb 3.4
API: GET /databasename/_table/{table_name}/{id}  ( _to retrieve one record by identifier._)

The document has a field of array type, e.g., 
`
{
    stringField: "nothing wrong",
    arrayField: [
         {name: 'hello'},
         {name: 'world'}
    ]
}`

When using above mentioned GET API, Dreamfactory will convert the arrayField into an **Object**:
`{
    stringField: "nothing wrong",
    arrayField: {
         0: {name: 'hello'},
         1: {name: 'world'}
    }
}`

**Comment by drewpearce** [comment]
Issue does not exist in latest release with latest php mongodb driver. Assume this was resolved in recent mongodb service changes. Please let us know if this is not the case after upgrading.
