### ISSUE TITLE
Installing on openshift

### ISSUE THREAD

**Issue by m-menon** [dreamfactorysoftware/dreamfactory#14]
hi,

Any documentation/cartridge on installing DF 2.0 on openshift?

thanks

**Comment by todda48** [comment]
We're working on updating the OpenShift cartridge for 2.0. Should be available in December.

**Comment by m-menon** [comment]
cool thanks. In the meantime is there any other way of getting 2.0 to run on openshift? Doesn't really matter if there is a whole bunch of manual steps. A little hesitant to install the current version of the cartridge that is available as I heard that moving to 2.0 isn't that straightforward. thanks

**Comment by hkhako** [comment]
I have a DIY cartiridge for that.
    https://github.com/hkhako/OS_Dreamfactory2.0

The installation script is not perfect yet, but can get you a working instance of DF 2.0.

**Comment by drewpearce** [comment]
DF 2.0 OpenShift is available. http://wiki.dreamfactory.com/DreamFactory/Installation/OpenShift
