### ISSUE TITLE
Missing email parameter after FB oauth_callback POST request

### ISSUE THREAD

**Issue by koko236** [dreamfactorysoftware/dreamfactory#140]
Hi, 

I'm implementing FB OAuth login in self hosted DF instance. I'm following the tutorial linked here: http://wiki.dreamfactory.com/DreamFactory/Tutorials/Using_OAuth

When I make the API call to:
`POST https://your-url/api/v2/user/session?oauth_callback=true&{extracted_query_string_from_callback}` 
I get status 400:
`{"error":{"code":400,"context":null,"message":"Login request is missing required email.","status_code":400}}`

As far as I understand, I shouldn't provide any email. It looks to me as if the request is misinterpreted as some another kind of login type. 

Same issue is mentioned here but no response was given. 
http://community.dreamfactory.com/t/log-in-with-facebook-does-not-work/3480

**Comment by a15lam** [comment]
Hi @koko236 , I tried to duplicate your issue but failed. You are right, you do not need to provide any email address or password at this step. Which version of DreamFactory you are using? Also can you tell me what parameters are getting passed in the {extracted_query_string_from_callback} segment?

**Comment by df-arif** [comment]
Hi @koko236 , I tried to duplicate your issue but failed. You are right, you do not need to provide any email address or password at this step. Which version of DreamFactory you are using? Also can you tell me what parameters are getting passed in the {extracted_query_string_from_callback} segment?

**Comment by koko236** [comment]
Hi, @df-arif, I'm using fresh install it's v2.5. However I should probably explain myself a bit more. I'm trying to implement FB (and G+) login for a native iOS app so I'm probably misunderstanding something fundamental here. I eventually did manage to login using FB Oauth but only after setting redirect URL in DF admin panel to:
 `http://localhost:8080/dreamfactory/dist/index.html?service=fb_oauth` 
but that obviously causes iOS Safari to redirect me to the DF admin panel instead of back to the iOS app.

So I figured I'd set the redirectURL to `fb<app_id>://authorize` to put me back in the app and then make the POST request to 
`https://localhost:8080/api/v2/user/session?oauth_callback=true&code=<authorisation_code>&state=<state_from_the_df_server>#_=_`. 
If I see correctly the only params returned are `code` and `state`. I assumed that the link between the first and the second POST to DreamFactory was the `state` param so the redirect URL pointing back to the fb_oauth service would be superfluous when it probably isn't. 

I spent better part of the day looking for any native mobile implementation of FB OAuth with DF but without much luck - just some old and inconclusive threads at df community forum. I'd be super thankful if you could point me to the right strategy.  :-) I imagine I could write a custom script on DF making the FB call using token or auth code but that way I believe I'd loose the automatic shadow user creation provided by OAuth service, am I right?

**Comment by koko236** [comment]
To cut the story short is there any endpoint where I can send auth code or token from FB and create/log in the DF shadow user?

**Comment by df-arif** [comment]
@koko236, currently there is no exclusive endpoint to create/log in as a shadow user passing auth code. Shadow user is only created as part of oauth callback handling. That being said, you seem to be on the right direction to implement this on iOS. You said...

> So I figured I'd set the redirectURL to fb<app_id>://authorize to put me back in the app and then make the POST request to
https://localhost:8080/api/v2/user/session?oauth_callback=true&code=<authorisation_code>&state=<state_from_the_df_server>#_=_.

That should allow you to log into DF using your FB authenticated user (and create the shadow
user in the first login). Is it not working for you? If you are still getting the 400 error (login request missing required email) then this could mean that the 'state' parameter is not getting passed to DF properly. Maybe it is getting truncated somewhere or getting corrupted somehow? The other thing you can try is, on the second POST to DF you can add the service parameter passing your FB service name like below

`../api/v2/user/session?oauth_callback=true&service=fb_oauth&code=<code>&state=<state>`

DF keeps an internal reference to the OAuth service being used using the state parameter. When DF cannot find that reference using state during the callback (second POST) it ignores the callback handling and treats the request as if you are trying to login with an email and password and therefore you get that 400 error. Providing the service parameter explicitly on the callback URL prevents DF from looking up the service using state parameter.

**Comment by koko236** [comment]
Allright, so maybe I'm messing something up with the params, if that's the way it should work I'll double check that. It seems I even guessed right about the service param in the second call. Thanks a lot for the guidance, I'll let you know if this worked or not.

**Comment by koko236** [comment]
Things changed a bit - now I get Internal Server Error 500 on the second POST request:
```
{"error":{"code":500,"message":""}}
```
Is there a way to make the error less cryptic?

**Comment by df-arif** [comment]
You can turn on debugging in your environment using the .env file that's in the root directory of your DF installation. Set the following in your .env file

> APP_DEBUG=true
> ...
> DF_LOG_LEVEL=DEBUG

This should give you more details on the error with PHP stack trace.

**Comment by koko236** [comment]
Ok, now I get a bit more:
```
{
    "error": {
        "code": 400,
        "message": "Client error: `POST https://graph.facebook.com/oauth/access_token` resulted
 in a `400 Bad Request` response:\n{&quot;error&quot;:{&quot;message&quot;:&quot;Error 
validating verification code. Please make sure your redirect_uri is identical to the one you  
(truncated...)\n"
    }
}
```
Seems like there's something wrong with the DF request to FB oauth endpoint, wrong or missing params?

**Comment by df-arif** [comment]
Make sure that the redirect URL you specified in your DF FB OAuth service matches the redirect URL you specified in your FB app settings.

**Comment by df-arif** [comment]
Found one issue with DF FB OAuth. It so happens that FB dropped support for their graph api v2.2 today. So, you may get an error like ..

> "Undefined variable: access_token", code 500"

If you get this error. Just run `composer update` at your DF installation root and try again. It will take care of that error.

**Comment by koko236** [comment]
> Make sure that the redirect URL you specified in your DF FB OAuth service matches the redirect URL you specified in your FB app settings.

Which FB App setting do you mean? I tried to add the `Valid OAuth redirect URIs` in FBLogin panel but it doesn't accept iOS callback scheme apparently. (Also judging from the FB error message it's about discrepancy between two graph calls, not about mismatch with a FB setting - more below). 

The problem ATM definitely has something to do with redirect_uri, I even started to call FB Oauth endpoint manually from a debug http Chrome plugin (bypassing the second call to DF completely) like so:
```
GET https://graph.facebook.com/v2.8/oauth/access_token?
   client_id={app-id}
   &redirect_uri={redirect-uri}
   &client_secret={app-secret}
   &code={code-parameter}
```
but the full error message states:
`Error validating verification code. Please make sure your redirect_uri is identical to the one you used in the OAuth dialog request`

So it would seem FB thinks the redirect uri on the second call is different from the first one - and I'd swear it's the same `fb{app_id}://authorize` both times... I need to research on that. Anyway until I push forward it seems like a non DF related problem now.

**Comment by aikidoesurf81** [comment]
Hi guys,
I also have problems logging in using the Facebook OAuth on two different apps. I'm getting same error on both: 
"error":{"context":null,"message":"Undefined variable: access_token","code":500,
"trace":["0 /opt/bitnami/apps/dreamfactory/htdocs/vendor/laravel/socialite/src/Two/FacebookProvider.php(87): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined varia...', '/opt/bitnami/ap...', 87, Array)","1 /opt/bitnami/apps/dreamfactory/htdocs/vendor/laravel/socialite/src/Two/FacebookProvider.php(77): Laravel\\Socialite\\Two\\FacebookProvider->parseAccessToken(Object(GuzzleHttp\\Stream\\Stream))", ...

**Comment by koko236** [comment]
**UPDATE** 
I've yet to confirm this but judging from other people reports it may be an issue with either FB transforming my `fb{app_id}://authorize` URI when storing it or refusing to store it at all without telling because of some scheme policy (eg. I came across someone claiming it has to be `https` scheme). 
@df-arif Are you positive the whole flow should work with fb scheme url as redirect_uri?

**Comment by aikidoesurf81** [comment]
One of my apps is 'https', Facebook_OAuth does not work on that one either

**Comment by koko236** [comment]
@aikidoesurf81 Have you tried the `composer update` suggestion by @df-arif above?

**Comment by koko236** [comment]
@aikidosurf81 Sorry, I was replying to myself about the scheme. Didn't notice your post.

**Comment by aikidoesurf81** [comment]
I did, but I cant confirm it worked just yet, after composer update (now version 1.4.1)  Bitnami VM needs to be restarted and for some reason after booting it comes up with a different IP, working on restoring that now

**Comment by rbarriuso** [comment]
In my case the error returned was `400 Bad Request`: `An active access token must be used to query information about the current user`.

It got fixed after `composer update`

See http://community.dreamfactory.com/t/facebook-login-fails/3752

**Comment by koko236** [comment]
Ok to wrap it up. **Yes, FB OAuth can work with native iOS App.**
1. You need to set the redirect URL in DF Oauth Service settings to `fb<app_id>://authorize/` 
2. The slash at the end is a **MUST**, otherwise FB thinks the redirect_URI is different than the first time and throws an error.
3. The general flow is like that: 
3.1 POST to df resource `user/session?service=fb_oauth` (add headers:
X-Dreamfactory-API-Key: <df_api_key>
X-Requested-With: XMLHttpRequest (this is to get json with FB url instead of being redirected)
3.2 Use the returned URL to open webview with FB auth screen
3.3 After successful login FB will redirect to fb<app-id>://authorize/<params>. You should react to that in you AppDelegate methods and retrieve all the params. NOTE: On success the params are '?' and on failure with '#'. 
3.3. POST to `user/session?oauth_callback=true&<all params from fb>` (there should be `code` and `state`)
3.4 You shoud get back session info from DF with `session_token` you can store and make next callbacks with it as a header or param. 

- All calls to DF should have the API key header set. 
- You may have to run 'composer update' for dreamfactory to get rid of `access_token`related error. 

Thanks for all the help.
