### ISSUE TITLE
Problem with API response

### ISSUE THREAD

**Issue by aikidoesurf81** [dreamfactorysoftware/dreamfactory#143]
Hi,
I have two Bitnami DreamFactory VM in Azure.
After running "composer update" at the DF root of one of them, the REST APIs stopped working, including inside 'API Docs' in the DreamFactory console.
I noticed that on the one that is working, the API calls from 'API Docs' are formed:
curl -X GET --header 'Accept: application/json' ... "
while on the one that is not working, the API calls from 'API Docs' are formed:
curl -X GET --header 'Accept: text/html'  ... "
Could it be possible that after update, if affected how the API calls are formed and thus now the REST API calls return error?
Please help.
Thank you

**Comment by drewpearce** [comment]
What version of DreamFactory were you on before running composer update?

**Comment by aikidoesurf81** [comment]
It was running Bitnami-DreamFactory 2.1.0-4

**Comment by drewpearce** [comment]
Initial investigation on my end indicates not a bug. Recommend you look at the documentation for upgrades. Composer update is not a recommended command.
[Upgrade Documentation](http://wiki.dreamfactory.com/DreamFactory/Upgrades)
Also, we generally do not provide support via GitHub, reserving it bugs and feature requests.
If you need additional assistance you can [contact support](mailto:dspsupport@dreamfactory.com) directly as a paying customer or engage the support team and DreamFactory community in our [community forums](http://community.dreamfactory.com).
