### ISSUE TITLE
DF 2.5.0 Exporting schema fails - Table doesn't exist

### ISSUE THREAD

**Issue by koko236** [dreamfactorysoftware/dreamfactory#144]
I'm trying to export all tables schema into package and get error saying 'Table `<table-name>` doesn't exist'. 
What's interesting is that the `<table-name>` mentioned is an alias of one of the tables. It's a many-t-many junction table. I'suspect there's a reference by alias somewhere in the schema that's causing trouble but I'm not sure how it got there and I guess it's not supposed to happen anyway?

**Comment by koko236** [comment]
Even more interesting (and more specific) - there's no error if I select all the tables by hand but if I choose "Add All" I get the error.

**Comment by drewpearce** [comment]
Resolved in the subsequent release
