### ISSUE TITLE
How to export api documentation?

### ISSUE THREAD

**Issue by dppereyra** [dreamfactorysoftware/dreamfactory#149]
Hi,

Just saying that your product has helped me a lot. I do have question as I have looked through your wiki and was unable to find an answer. Is there anyway to export the api documentation either as html/pdf or even better if I can get the swagger json/yaml file?

Thanks and Best Regards,

Dennis Philippe

**Comment by drewpearce** [comment]
Hi, @dppereyra. We generally reserve Github for filing bugs and feature requests. For support requests, head over to our community forums -- http://community.dreamfactory.com
