### ISSUE TITLE
CORS configuration

### ISSUE THREAD

**Issue by nawarian** [dreamfactorysoftware/dreamfactory#15]
Hi, there!

While testing Dream Factory using a SQLite config I couldn't create CORS rules.
Got that:
```SQL
SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: cors_config.created_date (SQL: insert into "cors_config" ("origin", "path", "method", "enabled", "header", "max_age", "created_by_id") values (http://localhost:8080, *, 31, 0, *, 0, 1))
```

That's mainly because `cors_config` table's definition says that `created_date` is a datetime not null and doesn't have a default value.
Don't know if the fix should be placed in the application or in the database migration.

**Comment by df-arif** [comment]
This is a known issue using SQLite and we are working on it. In the mean time please use MySQL or PostgreSQL.

**Comment by nawarian** [comment]
I see. Probably setting $timestamps to true wouldn't be the correct way then.
May the PR be closed?

**Comment by hongkongkiwi** [comment]
Also having the same issue here.

**Comment by df-arif** [comment]
This is fixed and will be available on next release.
