### ISSUE TITLE
Accesing files app with local storage fails with permission denied in mkdir()

### ISSUE THREAD

**Issue by schoel-bis** [dreamfactorysoftware/dreamfactory#151]
On a new install of DreamFactory 2.7 (Bitnami Docker image) accessing the files app fails with `mkdir(): Permission denied`. The stack trace includes `vendor/dreamfactory/df-file/src/Services/LocalFileService.php(31): mkdir('app', 509)"`. The initial configuration value of the files app's root directory is `app` i.e. the first parameter passed to `mkdir` in LocalFileService.php. Changing this configuration value to either an absolute path or `local` works around the issue.

What is happening here, is that LocalFileService tries to create a directory `app` relative to the current working directory because `$root` in the `setDriver` method of that service is a non-empty, relative path. Setting it to `local` will make it hit the second condition which goes for the default of `storage_path('app')`.

Relative paths as root directories for file storage should be made relative to storage_path instead of to the current working directory.

**Comment by leehicks** [comment]
Yeah, sorry, this was a mixup from the DatabaseSeeder.php changes with restructuring 2.7.0. 
The /database/seeds/DatabaseSeeder.php line 54 should be "local" instead of "app". Will patch this shortly.

**Comment by schoel-bis** [comment]
Alright. Still, you might think about making relative paths relative to storage_path. That probably makes much more sense than PWD.

**Comment by leehicks** [comment]
Yeah, agree that this is confusing, which stems from supporting Laravel config "disks" originally. Will try to clear this up. Thanks for the input. I will close this when the patches are in place

**Comment by leehicks** [comment]
I left the DatabaseSeeder as is, which is correctly using a relative path from the installation configured storage directory (<install_dir>/storage), and fixed the file service configuration handling in [dreamfactory/df-file] (https://github.com/dreamfactorysoftware/df-file/commit/127663f955b69b38b9cb0c48739b92c009b78542) along with better help text. It now accepts relative or full paths. The hotfix is dreamfactory/df-file 0.2.1, you can use composer update dreamfactory/df-file to update until a new dreamfactory release is packaged by Bitnami.
