### ISSUE TITLE
DF 2.7.0: User register API don't save password

### ISSUE THREAD

**Issue by luisbatista** [dreamfactorysoftware/dreamfactory#152]
Hello,

I try some scenarios to test the "/user/register" API, and can't get to save the password!

In the DF configuration have: `Allow Open Registration = true`.

Then, using the swagger included in DF I try to register a user with password, have this:
```
body:
{
  "email": "dev9a@mailinator.com",
  "first_name": "dev9a",
  "last_name": "test",
  "display_name": "Dev9a Name",
  "new_password": "soudev9a",
  "code": "onlytotest"
}

login: true
```
The cUrl:
`http://my.domain.com/api/v2/user/register?login=true`

Response:
```
{
  "success": true,
  "confirmation_required": true
}
```
In the database the password is not set, receive an email with the Url to set the password and confirm the account!

Ok, now try the same  but with changing the "login: false" and get:

The cUrl:
`http://my.domain.com/api/v2/user/register?login=false`

Response:
```
{
  "success": true
}
```
Same result without the "code" in the body!

No way to set the user password using the API.

Can you confirm if it is a Bug or other issue?

Regards,
LB

**Comment by todda48** [comment]
The UI is a little confusing. There's an implicit assumption that if you don't want to require email confirmation you should unset 'Open Reg Email Service' in Services-->User-->Config. Set it to empty (no selection). Your first example with login=true should then return a session token.

**Comment by luisbatista** [comment]
Hello @todda48 ,

Thanks for reply.
If you don't tell me I never figure out how put this working! :)
👍 

But, if I want to send a "Welcome" email (after the Registration) what is the best solution with this configuration?

Best regards,
LB

**Comment by todda48** [comment]
You could create an event script on user.register.post.post_process. This script would call the email service with whatever payload you want. Example:
```

var email = {
 
        "to": [
            {
                "name": "John Doe",
                "email": "johndoe@mailinator.com"
            }
        ],
        "subject": "New user",
        "body_text": "A new user was registered.",
        "from_name": "John Doe",
        "from_email": "johndoe@mailinator.com",
        "reply_to_name": "John Doe",
        "reply_to_email": "johndoe@mailinator.com"
    };
 
    platform.api.post("email", email);
```

**Comment by luisbatista** [comment]
Thanks again @todda48

Best regards,
LB

**Comment by todda48** [comment]
Make sure the role you selected for open registration allows script access to the email service. This is done from the Roles tab.
