### ISSUE TITLE
[bug] Response  information when payload have wrong json

### ISSUE THREAD

**Issue by luisbatista** [dreamfactorysoftware/dreamfactory#157]
Hello,

I get this situation when I try to update a field in: **POST user/profile**
In database the user logged have the: `first_name = 'John'` and want to change to `first_name='Doe'`.

I have this payload:
```
POST user/profile
{
  "first_name": "Doe",
}
```

and get the Response Body:
```
{
  "success": true
}
```

**It's wrong response!**
The field not change in database because a incorrent json payload (because of the comma):  **"first_name": "Doe",**

I change the payload to:
```
POST user/profile
{
  "first_name": "Doe"
}
```
And get the same Response Body, but now the field is updated in the database.

Regards,
LB

**Comment by todda48** [comment]
Looking into it.

**Comment by df-arif** [comment]
@luisbatista , This seems like a validation issue. What's actually happening is that when you pass an invalid payload (most client fails and stops the request) the server side sees it as blank and therefore updates nothing but gives you a {"success":true} response. We fixed it to return 400 (Bad request) when payload is blank. The fix should be out in our upcoming release.
