### ISSUE TITLE
Not able to insert more than 3000 records into PostGreSQL in single POST request 

### ISSUE THREAD

**Issue by mital7559** [dreamfactorysoftware/dreamfactory#158]
Hi,

Dreamfactory version : 2.8.0

I am trying to post more than 3000 records in single POST request but it return 500 error code with an html response page of something went wrong.

URL :  http://localhost/api/v2/postgresql/_table/users

Is there any limits set some where in properties file or we cannot insert more than 3000 records in single request?

I want to perform batch insert of like lacs of records , so suggest is that possible with dreamfactory?

Kindly assist.

**Comment by MSchaer1985** [comment]
@mital7559 please use the [community forum](http://community.dreamfactory.com/). This GitHub repo isn't for support.
