### ISSUE TITLE
SQLSTATE[42601]: Syntax error: 7 ERROR: zero-length delimited identifier at or near """"

### ISSUE THREAD

**Issue by varun7447** [dreamfactorysoftware/dreamfactory#159]
I created a postgresql service. The version of postgres is 9.6.3. When i try to use the Schema tab and click on refresh button i am seeing below exception. Is this a bug?

SQLSTATE[42601]: Syntax error: 7 ERROR: zero-length delimited identifier at or near """"
LINE 1: set search_path to ""
^ (SQL: SELECT schema_name FROM information_schema.schemata WHERE schema_name NOT IN ('information_schema','pg_catalog'))

**Comment by drewpearce** [comment]
Can you include the version of DreamFactory as well as the version of PHP and the pgsql PHP driver?

**Comment by varun7447** [comment]
I am using latest version of DreamFactory and whatever version comes during the installation PHP.

**Comment by drewpearce** [comment]
Did you install with Bitnami? What operating system?
You can get the DreamFactory version by looking at the Config page of the admin app.

**Comment by varun7447** [comment]
DreamFactory Version: 2.8.0
Operating System: linux
Release: 3.10.0-514.26.1.el7.x86_64
PHP Version: 7.0.21
System Database: mysql
