### ISSUE TITLE
Imported App To Files.  Nothing In Files

### ISSUE THREAD

**Issue by svstartuplab** [dreamfactorysoftware/dreamfactory#161]
I followed this process:

1)  In Apps I selected the Angular app, Storage Service = files, and created a folder in file for the app.

2) The app imported nicely and I can see the tables and data in DF2.  However, there is no new folder or the app in Files.  This appears to be a bug but I'm new to DF.

I dug deep into the DF2 files and couldn't find the app or the storage folder with files and logs folders.  The app and those folders aren't in apps/dreamfactory/htdocs/storage. 

I have the recent Bitnami install and the current version of DF2 running on Ubuntu 16.04 in a Vagrant Virtualbox on a Mac.  I'm using Nginx.

**Comment by drewpearce** [comment]
If you imported the Angular2 app, that doesn't run inside of DreamFactory. It's meant to be run in Node with the data and APIs being served through DreamFactory. Check out the README for full instructions. Pay close attention to the section titled "Import the package file for the App."

**Comment by svstartuplab** [comment]
"Leave storage service and folder blank. You will be running the app locally on your machine so no file storage is required."   Oops, sorry, didn't notice that.  I saw Files as a selection during import and thought it should be in Files in DF.

**Comment by svstartuplab** [comment]
I installed the app but where does it live?  That question isn't answered in the instructions.  It just says to edit the config file and insert the api key.  I can't find it anywhere on my Ubuntu server and I have nothing but DF2 on it so far.

It isn't clear in the Apps UI that instructions exist on Github.  Seems like we should just select and import.  Could use a message that the readme file is available.

**Comment by drewpearce** [comment]
Hi Jim. The README instructs you to clone the repo to your machine and run it with Node. If you click on the any of the App names in the Apps tab it takes you to the README for that repo.

**Comment by svstartuplab** [comment]
Sure, but I already imported it in Apps.  I can see the schemas, tables, and data.  The Apps / Import functionality works.  Why import it again?    This looks like a design flaw.  Import works, that is the most obvious place to get the apps, but the app files are hidden somewhere.  This is a bug.

Also, it is far from obvious that setup instructions are available by clicking on an app title link in Apps.  That needs to be mentioned in the UI, where most users are going to look for it.  This is a bug.

**Comment by svstartuplab** [comment]
I followed the instructions in Github and they follow the App Import process.  I just can't find the app files to edit per the next instruction. There is nothing about cloning in the instructions:

Import the package file for the app.

From the Apps tab in the admin console, click Import and click 'Address Book for Angular 2' in the list of sample apps. The Address Book package contains the application description, schemas, and sample data.

Leave storage service and folder blank. You will be running the app locally on your machine so no file storage is required.

Click the Import button. If successful, your app will appear on the Apps tab. You may have to refresh the page to see your new app in the list.
Edit your app API key and instance URL

Edit app/config/constants.ts and set DREAMFACTORY_API_KEY to the key for your new app. 

The API key is shown on the app details in the Apps tab of the admin console. Set DREAMFACTORY_INSTANCE_URL to the base URL for your DreamFactory instance.

**Comment by svstartuplab** [comment]
Also notice that the instructions for "Edit your app API key and instance URL"  come before cloning so they are out of sequence.  That should be easy to fix.  Adds more confusion.

**Comment by svstartuplab** [comment]
Also, why install NativeScript?  It errors out anyway because it needs Xcode and Android.  Maybe find however included that in the instructions and discuss.  NativeScript is for developing Angular for iOS and Android.  I don't see how it is relevant here, at least at this point in the setup. Just adds to confusion.

**Comment by svstartuplab** [comment]
I'm no Angular wiz but when I glanced through the code it appears to have a lot of obsolete code.  Sure enough, with npm start it didn't compile.  The Angular code two years ago is mostly obsolete now.  Lots of breaking changes.  While the authors made changes a year ago when Google released it there have been breaking changes since then.  Some of it doesn't comply with the Angular Style Guide and how we build these now.  This app needs to be significantly refactored.

**Comment by MSchaer1985** [comment]
@svstartuplab  Thanks for the feedback. We will look into getting the example app updated.

**Comment by svstartuplab** [comment]
Matt, I’m many months from having the skills to update it but you could ask for help on https://www.reddit.com/r/Angular2/ <https://www.reddit.com/r/Angular2/>

Lots of helpful devs there.

jim

**Comment by drewpearce** [comment]
Hi, Jim. We do take pull requests, so you're welcome to make changes to the README to make it make more sense and submit them for review. If you find an actual bug feel free to submit it as a new Issue, **preferably on the relevant repo** ( https://github.com/dreamfactorysoftware/angular2-sdk ), rather than on the main DreamFactory repo.

The actual OP is not a bug and therefore this issue will be closed. Please know that we do not do technical support through our GitHub, though we do take bug reports, feature requests, and contributions. Users looking for technical assistance should check out the community forums ( http://community.dreamfactory.com ) or look into one of our commercial offerings ( http://dreamfactory.com/products .)
