### ISSUE TITLE
Missing data in the services table

### ISSUE THREAD

**Issue by pafelin** [dreamfactorysoftware/dreamfactory#164]
Hi team

I just set up the dreamfactory on my server and the login screen was just white and it didn't work. 
This was caused due to the reason that the `services` table was empty and then the endpoint `api/v2/system/environment` was returning a 404 error.

I knew that this appication worked because I've tested it locally on a bitnami image. What I did to solve my issue on my production server was to dump my local data from the `services` table and put that manually in the production server. 

That step allowed me to login and start setting up everything. I think the problem was in the seeding of the default services that maybe are required. 

Best

**Comment by drewpearce** [comment]
This indicates that something failed during the installation process as that table should have been generated. This is a support issue and will need to be addressed through proper channels.
http://www.dreamfactory.com/support
(Chat, Email, Phone for paid users, Forums for non-paid.)

Kind regards,
