### ISSUE TITLE
Deny access to column / like functionality

### ISSUE THREAD

**Issue by MyChickenNinja** [dreamfactorysoftware/dreamfactory#170]
Running simple MySQL with DF API.
Only want the API to make requests for '=' and 'like%' on a specific column.

There is no option to deny API query to other columns. After setting up a role and allowing access to the column I want, I can still make API queries to the other columns.

Also 'starts with' and 'ends with' appear to offer the same functionality as 'like' but do not restrict wild card search to beginning or end as you might expect. 

Searched through the docs but didn't find anything specific to this.

**Comment by todda48** [comment]
If you want to restrict access to certain columns, you can easily do this with a server-side script using JavaScript, PHP, or Python. You would add a script for the service/table/event such as mysql._table.contact.get.post_process. See the field level security [examples](http://wiki.dreamfactory.com/DreamFactory/Tutorials/Server_Side_Scripting#Node.js) on the wiki. Basically you loop through the records and delete whatever fields are not allowed based on the role for that user.

I'm not seeing any problem with 'starts with' or 'ends with' filters. Can you provide a specific example?

**Comment by drewpearce** [comment]
Unable to replicate without additional info.
