### ISSUE TITLE
Artisan namespace problem

### ISSUE THREAD

**Issue by Goldenstarc** [dreamfactorysoftware/dreamfactory#171]
when i use this:
`php artisan dreamfactory:setup
`
get this error:
`There are no commands defined in the "dreamfactory" namespace.
`
The command is changed to 
`php artisan df:setup
`
PLEASE update this page
http://wiki.dreamfactory.com/DreamFactory/Installation/Windows

**Comment by chas688** [comment]
@Goldenstarc ,
Sorry about that and thanks for pointing that out. It should be `df:setup`. I've made the change in the wiki. You will need to run:
`php artisan df:setup`
You can view all the other artisan commands as well by just 
`php artisan`

**Comment by Goldenstarc** [comment]
two another thing...first:before runnig df:setup we must run df:env for config..
second: in df:env we must get permission two these 

> *   
> -> storage/
> *   -> bootstrap/cache/
> * Example:
> *      > sudo chown -R {www user}:{your user group} storage/ bootstrap/cache/
> *      > sudo chmod -R 2775 storage/ bootstrap/cache/
these things must be updated.
sorry if these are not issue :(
