### ISSUE TITLE
Data missing when seeding

### ISSUE THREAD

**Issue by Goldenstarc** [dreamfactorysoftware/dreamfactory#172]
every thing woks well with bitnami image but when using source i get this error when i want to login 
(every thing went well)
`Session name cannot be empty, did you forget to call &quot;parent::open()&quot; in &quot;Symfony\Component\HttpFoundation\Session\Storage\Handler\NullSessionHandler&quot;?.
`
any suggest to solve this?

**Comment by df-arif** [comment]
In your php.ini set use_cookies = 0. Restart Apache or php-fpm if you are using nginx.
