### ISSUE TITLE
Cannot update field of type ObjectId in MongoDB

### ISSUE THREAD

**Issue by whitlockau** [dreamfactorysoftware/dreamfactory#174]
I’m trying to use the REST API to update a field in a record in MongoDB. The field is of type ObjectId, but the API refuses to accept the Extended JSON syntax for an ObjectId.

I’m using a PATCH request with the following body:

`{
  "testVal": { "$oid": "5a31edc2743bb8f105db877d" }
}`

The response I get is:

`{
  "error": {
    "code": 500,
    "message": "The dollar ($) prefixed field '$oid' in 'testVal.$oid' is not valid for storage."
  }
}`

I have tested the Extended JSON syntax for a Date (i.e. the “$date” syntax) and that works fine, so it seems to be a problem with ObjectIds specifically. I have also tried the mongo shell syntax of ObjectId("5a31edc2743bb8f105db877d"), but that doesn’t work either.

I raised this as [a question in the forums](http://community.dreamfactory.com/t/cannot-update-field-of-type-objectid-in-mongodb/4214), but nobody has answered so at this point I have to assume it's a bug.

**Comment by todda48** [comment]
This does appear to be a bug. We will try to fix it before the next release, which is scheduled for next week.

**Comment by leehicks** [comment]
@whitlockau Our interface uses the $id label (gets converted to ObjectId() internally, seemingly the "old" way, but still works). $oid usage seems to be an evolution with the transition to the new drivers. We will add the $oid support, but until that is released please see if this scenario works with $id for you.

**Comment by leehicks** [comment]
Looks like $ was dropped from the git commit, should be "Support $oid as well as $id on type conversions"

**Comment by whitlockau** [comment]
Thanks for your help, guys.  The "$id" syntax does seem to work ... mostly.  This works:

```
{
  "testVal": { "$id": "5a31edc2743bb8f105db877d" }
}
```

And this works:

```
{
  "testVal": { "one": { "$id": "5a31edc2743bb8f105db877d" } }
}
```

But this fails:

```
{
  "testVal": { "one": { "$id": "5a31edc2743bb8f105db877d" }, "two": "1234" }
}
```

The error it fails with is this:

```
{
  "error": {
    "code": 500,
    "message": "Found $id field without a $ref before it, which is invalid."
  }
}
```
