### ISSUE TITLE
Api Access Overview component cleared

### ISSUE THREAD

**Issue by it-ced** [dreamfactorysoftware/dreamfactory#177]
DF: 2.11
Bitnami VM.

In the Service Access screen, if I select a service that is already present and configured (e. g. user), the component selection is blanked out.

Works on 2.10 version.

**Comment by drewpearce** [comment]
Can you please provide more details. Your issue lacks context, and is difficult to reproduce without details.

**Comment by it-ced** [comment]
![error_01](https://user-images.githubusercontent.com/35597340/35562429-a09881e8-05b3-11e8-8035-10b82f6e7f30.PNG)

If I select (for example) user instead of api_doc, the values selected in component are deleted.
Unfortunately I can't create a screen because I rollback to version 2.10.

**Comment by drewpearce** [comment]
I have verified this issue and filed it as DF-1295. Thank you.

**Comment by todda48** [comment]
Fixed in develop branch of df-admin-app. Will be in next release.
