### ISSUE TITLE
Api doc security does not work

### ISSUE THREAD

**Issue by it-ced** [dreamfactorysoftware/dreamfactory#178]
DF: 2.10 - 2.11
Bitnami VM.

If the service access selects a component different from *, the relevant api doc is not displayed. Only works *.

**Comment by drewpearce** [comment]
Can you please provide more details. Your issue lacks context, and is difficult to reproduce without details.

**Comment by it-ced** [comment]
I created an apps-users-role chain, with a user with specific permissions. If I select under roles-access a service and a sub component, I can't use api docs with the user with permissions. (see screen 1)
If I select *, I can see the api docs. (see screen 2)

screen 1
![screen_01](https://user-images.githubusercontent.com/35597340/35561756-97e07a80-05b1-11e8-8679-70d38f910f43.PNG)

screen 2
![screen_02](https://user-images.githubusercontent.com/35597340/35561757-9810bc18-05b1-11e8-8007-c2339dd64688.PNG)

**Comment by drewpearce** [comment]
I have confirmed this bug and filed it. DF-1296. Thank you.

**Comment by drewpearce** [comment]
fixed in develop branch of df-core. will be in next release.

**Comment by it-ced** [comment]
I installed the new version. Now everything works until I select a custom component:
e. g. _scheme/ -> works
e. g. _scheme/* -> works
e. g. _scheme/my_api. table/* -> does not work.
e. g. _scheme/my_api. table/ -> does not work.

**Comment by leehicks** [comment]
Just tested this and it seems to be working. There is a space in "my_api. table", is that the case in the actual table listing? That may be causing a problem. Can you confirm that the tables without a space work?

**Comment by it-ced** [comment]
ok I did some other tests:
_scheme/my_api_table/ -> does not works
_scheme/my_api_table/* -> does not work.
_table/my_api_table/ -> works
_table/my_api_table/* -> does not work.

It seems that the dot does not work for the table.
For the scheme I would not know.
