### ISSUE TITLE
CORS error: header ‘Access-Control-Allow-Origin’ missing

### ISSUE THREAD

**Issue by tvarsis** [dreamfactorysoftware/dreamfactory#179]
Hi,

After upgrading to 2.11 I am getting this error:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at {URL}/api/v2/user/session. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

The old CORS settings worked on the older installation. 
I have tried to update all settings, entering both wildcards everywhere, as well as specifying hosts, verbs, headers etc. And it does not matter what I set in these fields. I still get the same error. I have also cleared cache in between.
Is there an issue with CORS in this release?

![image](https://user-images.githubusercontent.com/10090010/35431680-b52922ae-027d-11e8-89cc-0e6842707402.png)

**Comment by tvarsis** [comment]
Just to let you know, I solved this by doing this in Apache bitnami.config

Header always set Access-Control-Allow-Origin "*"
Header always set Access-Control-Allow-Methods "POST, GET, OPTIONS, DELETE, PUT"
Header always set Access-Control-Max-Age "1000"
Header always set Access-Control-Allow-Headers "X-DreamFactory-Api-Key, X-DreamFactory-Session-Token, x-requested-with, Content-Type, origin, authorization, accept, client-security-token"

# Added a rewrite to respond with a 200 SUCCESS on every OPTIONS request.
RewriteEngine On
RewriteCond %{REQUEST_METHOD} OPTIONS
RewriteRule ^(.*)$ $1 [R=200,L]

However, that was needed before, and that pretty much overrides the CORS in DF. So I still think there is an issue here with DF.

**Comment by drewpearce** [comment]
This is a known bug in 2.11.0, and is resolved in 2.11.1 which was released last night. Upgrade instructions: http://wiki.dreamfactory.com/DreamFactory/Upgrades
