### ISSUE TITLE
Issue with installing to ubuntu

### ISSUE THREAD

**Issue by bloodmajik** [dreamfactorysoftware/dreamfactory#181]
![image](https://user-images.githubusercontent.com/32602506/35773401-e4d1a574-0905-11e8-8631-cec3eed8e3d3.png)

Any ideaS?

**Comment by drewpearce** [comment]
Hi blookmajik. We generally reserve our GitHub issues for bugs and feature requests. How-tos and Support requests should be directed to our community forums -- http://community.dreamfactory.com.
Thanks.
