### ISSUE TITLE
Gitlab script integration not working with v4 API

### ISSUE THREAD

**Issue by Notifium** [dreamfactorysoftware/dreamfactory#184]
Hi,
I think your Gitlab library is trying to call Gitlab API v3, which was discontinued a few versions OK.
Regards,
Andy

**Comment by jacotri77** [comment]
Hi Andy,

You can actually just change the baseURL to v4:

https://cl.ly/0T3P0n053u3B

Give that a try.

Thanks!

**Comment by GStetco** [comment]
Hello @Notifium, did this suggestion helped to solve your problem?
I'm asking because I used the v4 url, but it will just get the list of the repository, but not the specific files (error 404).

Thanks
Gabriel

**Comment by jacotri77** [comment]
I am able to access the files inside with this path:
https://cl.ly/1F2H3J1A3U2t

**Comment by GStetco** [comment]
Thanks @jacotri77 
The listing of the files works. The problem is when you need the content. Did you try to set the flag "content" to true?
