### ISSUE TITLE
open_basedir restriction

### ISSUE THREAD

**Issue by meiti** [dreamfactorysoftware/dreamfactory#19]
Hi

I'm using php5-fpm pools and php_admin_value[open_basedir] to limit the directories that can be accessed by Custom Scripting Services (php). When I want to open dreamfactory instance in browser I get the following error.

file_exists(): open_basedir restriction in effect. File(/var/www/html/df2/public/../../.bitnamimeta/demo_machine) is not within the allowed path(s): (/var/www/html/df2:/tmp)","code":500,"trace":["0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'file_exists(): ...', '/var/www/html/m...', 85, Array)","1 /var/www/html/df2/vendor/dreamfactory/df-core/src/Resources/System/Environment.php(85): ...

**Comment by primesoftware** [comment]
That's a problem with a config setting in either your webserver conf or php.ini. Add those paths to the open_basedir list and you should be fine.
