### ISSUE TITLE
Only one usage of each socket address is normally permitted

### ISSUE THREAD

**Issue by RobDeVos** [dreamfactorysoftware/dreamfactory#200]
We are currently experiencing problems with accessing DreamFactory, we don’t believe DreamFactory is the problem.
When we call DreamFactory sometimes we get de message “Only one usage of each socket address (protocol/network address/port) is normally permitted” 
When I searched for a solution  I found:
https://blogs.msdn.microsoft.com/dgorti/2005/09/18/only-one-usage-of-each-socket-address-protocolnetwork-addressport-is-normally-permitted/
I have changed the MaxUsedPort to 32767 and the TCPTimedWaitDelay to 120 seconds.
Even after these changes we are experiencing this problem.
Do you have suggestions?

Regards,
Rob

**Comment by jacotri77** [comment]
Hi @RobDeVos we will take a look at this and see if we can help out.  Can you provide any other details that might be useful surround this occasional message?  What operating system are you on?  Is DF behind a firewall, or outside of a firewall?  What version of DF are you running, etc.?

Thanks!

**Comment by wjgilmore** [comment]
Hi @RobDeVos in addition to @jacotri77 's questions are you by chance receiving this error in conjunction with SQL Server? Does the problem go away when you enable connection pooling inside your DreamFactory SQL Server service configuration?

**Comment by RobDeVos** [comment]
The server is a windows 2012 R2 server with DreamFactory version 2.4.1-1 installed using the windows-installer.
We call the Rest api from several different applications and they give slightly different error messages, the error from SharePoint reads: SQLSTATE[HY000] [2002] Only one usage of each socket address (protocol/network address/port) is normally permitted.
Google search results suggests it is MySQL related, so I search the MySQL directory for a .log file and found mysqld.log but it contains no messages regarding the error. 
Do you have any suggestions where to look?
