### ISSUE TITLE
php stop on continue with php 7.3.2

### ISSUE THREAD

**Issue by Hellorheaven** [dreamfactorysoftware/dreamfactory#208]
Hi, 
i install for first time dreamfactory and have some issue due to the continue switch deprecated on PHP 7.3.2
as you can see here https://wiki.php.net/rfc/continue_on_switch_deprecation

My context is on centos 7 with php 7.3.2 version (remi packages). when I use php artisan df:setup it stop just after db migration with the message : "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?

I change "continue;" by "break;" in the file specified by dreamfactory.log (i don't remermber and erase logs) and it work. after that i tried to create a mysql database service and I had same error when I tried to read the schema or data of this service. i made same modification in this files : 
 ./vendor/dreamfactory/df-database/src/Resources/BaseDbTableResource.php
 ./vendor/dreamfactory/df-database/src/Resources/DbSchemaResource.php
 ./vendor/dreamfactory/df-database/src/Services/BaseDbService.php

and it work fine after. 

I think that you had to replace all "continue;" by "break;" in all files for being compatible with new php version.

thanks.

**Comment by thekevinm** [comment]
Hi @Hellorheaven,

Thank we for bringing this to our attention, we will investigate this issue.

Cheers

**Comment by namtenten** [comment]
same here :((

# php -v
PHP 7.3.4 (cli) (built: Apr  2 2019 13:48:50) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.4, Copyright (c) 1998-2018 Zend Technologies

===================================================

# composer require musonza/chat
Using version ^3.3 for musonza/chat
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)

Installation failed, reverting ./composer.json to its original content.

                                                                                           
  [ErrorException]                                                                         
  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?  
                                                                                           

require [--dev] [--prefer-source] [--prefer-dist] [--no-plugins] [--no-progress] [--no-update] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [<packages>]...

**Comment by tylerssn** [comment]
Same here.

**Comment by wjgilmore** [comment]
Hi,

Just a note we'll be addressing PHP 7.3 support in an upcoming release.

Jason

**Comment by KyronNextLevel** [comment]
Same here

**Comment by pcollinso** [comment]
Hellorheaven, please can you list the files you modified to get this working.i downoaded the dreamfactory 3.0 beta and the issue still persist.i use composer 1.9.0 and php 7.3
on php artisan df:setup, after the migration the seeder stops at AppSeeder.please help me i am stuck

**Comment by Hellorheaven** [comment]
I don't remember i see the dreamfactory.log and change the file it specify me... 
you can do a research by this command
egrep -rl 'continue' /<pathofdreamfactory>/

and editing each file and modify the one which use the continue function...
