### ISSUE TITLE
Email address is appending the DF servicename for Facebook OAuth Service

### ISSUE THREAD

**Issue by isreehari** [dreamfactorysoftware/dreamfactory#210]
```
{
“session_token”: “xxxxx”,
“session_id”: “xxxxx”,
“id”: 121,
“name”: “Sree Iasdf”,
“first_name”: “Sree”,
“last_name”: “Iasdf”,
“email”: "isree+SPTPFacebookOAuth@hotmail.com",
“is_sys_admin”: null,
“last_login_date”: “2019-02-28 07:18:21”,
“host”: “abcdef”,
“oauth_token”: “abcdef”
}
```

Thanks,
Sree

**Comment by isreehari** [comment]
@df-arif any help?

**Comment by wjgilmore** [comment]
Hi @isreehari could you elaborate further? What problem are you experiencing?

**Comment by isreehari** [comment]
I have created an oauthservice for google login e.g. SPTPGoogleOAuth and when I login with google login and called user/session?call_back=true&{code&state} then DF created a user in DF users for my login because that user does not exist before but it created username and email as email+ServiceName@domain.com e.g. isree+SPTPGoogleOAuth@gmail.com

**Comment by isreehari** [comment]
Hi Team, 
                 Please keep the documentation more accurate  - https://github.com/dreamfactorysoftware/df-oauth/blob/master/src/Services/BaseOAuthService.php#L202

DF OAuth service never return the actual email address of the user. It will always return ShadowOAuthUser such as `$emailId . '+' . $serviceName . '@' . $domain;` 


Thank you for wonderful tool. 


Thanks,
Sree
