### ISSUE TITLE
Failed to launch service "df"

### ISSUE THREAD

**Issue by Sakpal** [dreamfactorysoftware/dreamfactory#22]
Hello,

I just installed DreamFactory as per the steps provided.
But when I try to open the application, the following error is shown:
"Failed to launch service "df": Service not found"

How can I resolve this, any idea?

**Comment by df-arif** [comment]
It seems like your DB migration did not run properly. Did you get any error during installation, specifically when you ran 'php artisan dreamfactory:setup' command?

**Comment by Sakpal** [comment]
DB migration & seeding was successful. The setup command ran successfully.

However there's this error message in logs:
production.ALERT: Could not get cors config from DB - SQLSTATE[HY000] [1045] Access denied for user 'forge'@'localhost' (using password: NO) 

But I have updated the .env file with correct credentials

**Comment by df-arif** [comment]
Just to make sure, your DB username is 'forge' and host is 'localhost' in the .env file? If so then please make sure your db user 'forge' has proper grants/privileges for accessing the database ('DB_DATABASE' in .env file) that you set in the .env file.

**Comment by Sakpal** [comment]
The database operations are working. Migration & Seeding is done through the setup command. Even DEBUGGING is set to true.
Still the error message is same: "Failed to launch service "df": Service not found"

Note: I have "df" in my URL. Eg- hostname/df/dreamfactory/public.
          Does this "df" in the URL is causing the issue?

**Comment by Sakpal** [comment]
It was due to multiple instances of DreamFactory was installed.

Note: For DreamFactory to work, DOCUMENT ROOT must point to public folder of DreamFactory.
- http://domainname/dreamfactory/public/dreamfactory/dist/index.html - DIDN'T Work
- http://domainname/dreamfactory/dist/index.html - Worked
- http://subdomain.domainname/dreamfactory/dist/index.html - Worked
