### ISSUE TITLE
Pre processed payload is not saved in MYSQL database .

### ISSUE THREAD

**Issue by damionx7** [dreamfactorysoftware/dreamfactory#227]
I have made a post pre process script to modify a payload record. It changes the payload. But the changed data is not being written to database. Any help would be appreciated.

**Comment by wjgilmore** [comment]
Hi @royalhacker,

DreamFactory can modify both request payloads and responses, however without providing further information we are unable to answer your question. Please provide the following information:

1. The script.
2. Is the script attached to a POST, PUT, or PATCH request?
3. You said you made a "post pre process script". DreamFactory scripts are either pre-process or post-process; they cannot be both. Which one are you using?

Thank you,
Jason

**Comment by royalhacker** [comment]
Here, i have posted all the details on dreamfactory community forum. 
http://community.dreamfactory.com/t/sql-record-pre-processing-not-saving-records/4936

**Comment by damionx7** [comment]
??
