### ISSUE TITLE
Files with UTF8 characters

### ISSUE THREAD

**Issue by charleslcso** [dreamfactorysoftware/dreamfactory#228]
I'm new to DF, so please bear with me.

Installed Bitnami DF 2.14.1-12 in Ubuntu 18.04 LTS. It is up and running.
Logged into admin console, and started playing with it.

First thing for us to try is to play with the file system.
We created a few folders in storage/app/. For example, comics/, comics/heros/, comics/heros/vol1, comics/heros/英雄, comics/heros/英雄/vol1 and 測試中/.

In Admin console, under Files, we can browse into comics/. We can browse into comics/heros/, comics/heros/vol1. But we get error when we browse into those UTF8 directories. 

There is no error message in storage/logs/dreamfactory.log, even though we are using APP_DEBUG=true, APP_LOG_LEVEL=DEBUG.

![Screen Shot 4](https://user-images.githubusercontent.com/520537/60252069-316e3f00-98fc-11e9-8640-001c31281623.jpg)

**Comment by charleslcso** [comment]
The same issue as #192?

**Comment by charleslcso** [comment]
Anyone please? Anyone from DreamFactory?

**Comment by wjgilmore** [comment]
Hi @charleslcso you are correct this looks identical to #192 however the DreamFactory team hasn't implemented anything to noticeably improve this issue. If you identify a solution please let us know.
