### ISSUE TITLE
Facebook OAuth API error after upgrading from DF 2.0.1 -> DF 2.0.4

### ISSUE THREAD

**Issue by hkhako** [dreamfactorysoftware/dreamfactory#23]
I have two instance of DF, one is 2.0.1, while the other is 2.0.4,  They both have identical settings except the domain name.  The redirect URL at facebook included both domains.  However, my app can login via facebook OAuth service with DF 2.0.1 but not 2.0.4.  

I am able to acquire an access code from both version, but not able to create a new user from 2.0.4 with the last API call in the OAuth flow.  

The API call POST to /api/v2/user/session?oauth_callback=true&service=facebook&code={my code}

The call to DF 2.0.4 returns error 500 with no message.  The trace is:

    "0 /var/lib/openshift/{my_id}/app-root/runtime/repo/dreamfactory/vendor/dreamfactory/df-oauth/src/Services/BaseOAuthService.php(92): Laravel\\Socialite\\Two\\AbstractProvider->user()",
    "1 /var/lib/openshift/{my_id}/app-root/runtime/repo/dreamfactory/vendor/dreamfactory/df-core/src/Resources/UserSessionResource.php(81): DreamFactory\\Core\\OAuth\\Services\\BaseOAuthService->handleOAuthCallback()",
    "2 [internal function]: DreamFactory\\Core\\Resources\\UserSessionResource->handlePOST()",
    "3 /var/lib/openshift/{my_id}/app-root/runtime/repo/dreamfactory/vendor/dreamfactory/df-core/src/Components/RestHandler.php(271): call_user_func(Array)",
    "4 /var/lib/openshift/{my_id}/app-root/runtime/repo/dreamfactory/vendor/dreamfactory/df-core/src/Components/RestHandler.php(177): DreamFactory\\Core\\Components\\RestHandler->processRequest()",
    "5 /var/lib/openshift/{my_id}/app-root/runtime/repo/dreamfactory/vendor/dreamfactory/df-core/src/Components/RestHandler.php(224): DreamFactory\\Core\\Components\\RestHandler->handleRequest(Object(DreamFactory\\Core\\Utility\\ServiceRequest), '')",
    "6 /var/lib/openshift/{my_id}/app-root/runtime/repo/dreamfactory/vendor/dreamfactory/df-core/src/Components/RestHandler.php(172): DreamFactory\\Core\\Components\\RestHandler->handleResource(Array)",
    "7 /var/lib/openshift/{my_id}/app-root/runtime/repo/dreamfactory/vendor/dreamfactory/df-core/src/Services/BaseRestService.php(65): DreamFactory\\Core\\Components\\RestHandler->handleRequest(Object(DreamFactory\\Core\\Utility\\ServiceRequest), 'session')",
    "8 /var/lib/openshift/{my_id}/app-root/runtime/repo/dreamfactory/vendor/dreamfactory/df-core/src/Utility/ServiceHandler.php(57): DreamFactory\\Core\\Services\\BaseRestService->handleRequest(Object(DreamFactory\\Core\\Utility\\ServiceRequest), 'session')",
    "9 /var/lib/openshift/{my_id}/app-root/runtime/repo/dreamfactory/bootstrap/cache/compiled.php(17658): DreamFactory\\Core\\Utility\\ServiceHandler::processRequest('v2', 'user', 'session')",
    "10 /var/lib/openshift/{my_id}/app-root/runtime/repo/dreamfactory/bootstrap/cache/compiled.php(17634): DreamFactory\\Http\\Controllers\\RestController->handleService('v2', 'user', 'session')",
    "11 [internal function]: DreamFactory\\Http\\Controllers\\RestController->handlePOST('v2', 'user', 'session')",
    "12 /var/lib/openshift/{my_id}/app-root/runtime/repo/dreamfactory/bootstrap/cache/compiled.php(8873): call_user_func_array(Array, Array)",
    "13 /var/lib/openshift/{my_id}/app-root/runtime/repo/dreamfactory/bootstrap/cache/compiled.php(8942): Illuminate\\Routing\\Controller->callAction('handlePOST', Array)",
    "14 /var/lib/openshift/{my_id}/app-root/runtime/repo/dreamfactory/bootstrap/cache/compiled.php(8922): Illuminate\\Routing\\ControllerDispatcher->call(Object(DreamFactory\\Http\\Controllers\\RestController), Object(Illuminate\\Routing\\Route), 'handlePOST')",
    "15 [internal function]: Illuminate\\Routing\\ControllerDispatcher->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))",
    "16 /var/lib/openshift/{my_id}/app-root/runtime/repo/dreamfactory/bootstrap/cache/compiled.php(9593): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))",
    "17 /var/lib/openshift/{my_id}/app-root/runtime/repo/dreamfactory/bootstrap/cache/compiled.php(17807): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))",
    "18 [internal function]: DreamFactory\\Http\\Middleware\\AccessCheck->handle(Object(Illuminate\\Http\\Request), Object(Closure))",
    "19 /var/lib/openshift/{my_id}/app-root/runtime/repo/dreamfactory/bootstrap/cache/compiled.php(9585): call_user_func_array(Array, Array)",
    "20 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))",
    "21 /var/lib/openshift/{my_id}/app-root/runtime/repo/dreamfactory/bootstrap/cache/compiled.php(9575): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))",
    "22 /var/lib/openshift/{my_id}/app-root/runtime/repo/dreamfactory/bootstrap/cache/compiled.php(8923): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
    "23 /var/lib/openshift/{my_id}/app-root/runtime/repo/dreamfactory/bootstrap/cache/compiled.php(8908): Illuminate\\Routing\\ControllerDispatcher->callWithinStack(Object(DreamFactory\\Http\\Controllers\\RestController), Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request), 'handlePOST')",
    "24 /var/lib/openshift/{my_id}/app-root/runtime/repo/dreamfactory/bootstrap/cache/compiled.php(7862): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request), 'DreamFactory\\\\Ht...', 'handlePOST')",
    "25 /var/lib/openshift/{my_id}/app-root/runtime/repo/dreamfactory/bootstrap/cache/compiled.php(7833): Illuminate\\Routing\\Route->runWithCustomDispatcher(Object(Illuminate\\Http\\Request))",
    "26 /var/lib/openshift/{my_id}/app-root/runtime/repo/dreamfactory/bootstrap/cache/compiled.php(7486): Illuminate\\Routing\\Route->run(Object(Illuminate\\Http\\Request))",
    "27 [internal function]: Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))",
    "28 /var/lib/openshift/{my_id}/app-root/runtime/repo/dreamfactory/bootstrap/cache/compiled.php(9593): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))",
    "29 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))",
    "30 /var/lib/openshift/{my_id}/app-root/runtime/repo/dreamfactory/bootstrap/cache/compiled.php(9575): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))",
    "31 /var/lib/openshift/{my_id}/app-root/runtime/repo/dreamfactory/bootstrap/cache/compiled.php(7487): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
    "32 /var/lib/openshift/{my_id}/app-root/runtime/repo/dreamfactory/bootstrap/cache/compiled.php(7475): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))",
    "33 /var/lib/openshift/{my_id}/app-root/runtime/repo/dreamfactory/bootstrap/cache/compiled.php(7460): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))",
    "34 /var/lib/openshift/{my_id}/app-root/runtime/repo/dreamfactory/bootstrap/cache/compiled.php(2307): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))",
    "35 [internal function]: Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))",
    "36 /var/lib/openshift/{my_id}/app-root/runtime/repo/dreamfactory/bootstrap/cache/compiled.php(9593): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))",
    "37 /var/lib/openshift/{my_id}/app-root/runtime/repo/dreamfactory/app/Http/Middleware/AuthCheck.php(170): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))",
    "38 [internal function]: DreamFactory\\Http\\Middleware\\AuthCheck->handle(Object(Illuminate\\Http\\Request), Object(Closure))",
    "39 /var/lib/openshift/{my_id}/app-root/runtime/repo/dreamfactory/bootstrap/cache/compiled.php(9585): call_user_func_array(Array, Array)",
    "40 /var/lib/openshift/{my_id}/app-root/runtime/repo/dreamfactory/vendor/barryvdh/laravel-cors/src/HandleCors.php(42): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))",
    "41 [internal function]: Barryvdh\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))",
    "42 /var/lib/openshift/{my_id}/app-root/runtime/repo/dreamfactory/bootstrap/cache/compiled.php(9585): call_user_func_array(Array, Array)",
    "43 /var/lib/openshift/{my_id}/app-root/runtime/repo/dreamfactory/bootstrap/cache/compiled.php(17899): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))",
    "44 [internal function]: DreamFactory\\Http\\Middleware\\FirstUserCheck->handle(Object(Illuminate\\Http\\Request), Object(Closure))",
    "45 /var/lib/openshift/{my_id}/app-root/runtime/repo/dreamfactory/bootstrap/cache/compiled.php(9585): call_user_func_array(Array, Array)",
    "46 /var/lib/openshift/{my_id}/app-root/runtime/repo/dreamfactory/bootstrap/cache/compiled.php(12957): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))",
    "47 [internal function]: Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))",
    "48 /var/lib/openshift/{my_id}/app-root/runtime/repo/dreamfactory/bootstrap/cache/compiled.php(9585): call_user_func_array(Array, Array)",
    "49 /var/lib/openshift/{my_id}/app-root/runtime/repo/dreamfactory/bootstrap/cache/compiled.php(11551): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))",
    "50 [internal function]: Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))",
    "51 /var/lib/openshift/{my_id}/app-root/runtime/repo/dreamfactory/bootstrap/cache/compiled.php(9585): call_user_func_array(Array, Array)",
    "52 /var/lib/openshift/{my_id}/app-root/runtime/repo/dreamfactory/bootstrap/cache/compiled.php(12694): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))",
    "53 [internal function]: Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))",
    "54 /var/lib/openshift/{my_id}/app-root/runtime/repo/dreamfactory/bootstrap/cache/compiled.php(9585): call_user_func_array(Array, Array)",
    "55 /var/lib/openshift/{my_id}/app-root/runtime/repo/dreamfactory/bootstrap/cache/compiled.php(12631): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))",
    "56 [internal function]: Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))",
    "57 /var/lib/openshift/{my_id}/app-root/runtime/repo/dreamfactory/bootstrap/cache/compiled.php(9585): call_user_func_array(Array, Array)",
    "58 /var/lib/openshift/{my_id}/app-root/runtime/repo/dreamfactory/bootstrap/cache/compiled.php(2982): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))",
    "59 [internal function]: Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))",
    "60 /var/lib/openshift/{my_id}/app-root/runtime/repo/dreamfactory/bootstrap/cache/compiled.php(9585): call_user_func_array(Array, Array)",
    "61 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))",
    "62 /var/lib/openshift/{my_id}/app-root/runtime/repo/dreamfactory/bootstrap/cache/compiled.php(9575): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))",
    "63 /var/lib/openshift/{my_id}/app-root/runtime/repo/dreamfactory/bootstrap/cache/compiled.php(2254): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
    "64 /var/lib/openshift/{my_id}/app-root/runtime/repo/dreamfactory/bootstrap/cache/compiled.php(2237): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))",
    "65 /var/lib/openshift/{my_id}/app-root/runtime/repo/dreamfactory/public/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))",
    "66 {main}"

**Comment by df-arif** [comment]
This is fixed in 2.1.0
