### ISSUE TITLE
PHP Warning 

### ISSUE THREAD

**Issue by damionx7** [dreamfactorysoftware/dreamfactory#236]
I have PHP 7.3 installed. Could you guys look into this issue. 
`Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/dreamfactory/vendor/dreamfactory/df-database/src/Resources/BaseDbTableResource.php on line 3236`

**Comment by wjgilmore** [comment]
Hi @damionx7  this is due to a breaking change found in PHP 7.3 pertaining to the continue statement. We are in the midst of updating the code to support PHP 7.3, however can confirm DreamFactory works very well on PHP 7.2 so in the meantime just downgrading PHP 7.2 will fix the issue.
