### ISSUE TITLE
Unable to init SQL Server modules - VC11 vs VC12 builds

### ISSUE THREAD

**Issue by cosmocracy** [dreamfactorysoftware/dreamfactory#24]
Wondering if there’s possibly an issue with the build of the latest DreamFactory related to SQL Server support.  I'm using the Bitnami image for 2.0.4 on Windows 7.  When I follow the documentation—including the various steps described on this page: http://wiki.dreamfactory.com/DreamFactory/Installation/Databases/SQLServer I receive the following error from issuing “php -v" on my Windows box.  Note that under a 2.0.1-1 Bitnami image this worked fine.

```
C:\Bitnami\dreamfactory-2.0.4-0\php>php -v
PHP Warning:  PHP Startup: sqlsrv: Unable to initialize module
Module compiled with build ID=API20121212,TS,VC11
PHP    compiled with build ID=API20121212,TS,VC12
These options need to match
 in Unknown on line 0
PHP Warning:  PHP Startup: pdo_sqlsrv: Unable to initialize module
Module compiled with build ID=API20121212,TS,VC11
PHP    compiled with build ID=API20121212,TS,VC12
These options need to match
 in Unknown on line 0
PHP 5.5.30 (cli) (built: Dec  6 2015 19:39:50)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
```

**Comment by cosmocracy** [comment]
My working install--done under 2.0.1-1--gives the following output to "php -v", indicating it's the same version of PHP (etc.) but looks like it was re-built for the 2.0.4 Bitnami Dreamfactory image (?)

```
PHP 5.5.30 (cli) (built: Sep 30 2015 13:50:53)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
```

**Comment by todda48** [comment]
This is a known issue. Should be resolved this week.

**Comment by cosmocracy** [comment]
Ok, thank you @todda48.  I will uninstall and fall-back to 2.0.1-1 for now.  Looks like someone was excited to use VS2013 ;-) for the PHP build.  Merci

**Comment by drewpearce** [comment]
@cosmocracy FYI, after you revert to an older version, you can use the upgrade instructions on the Wiki to get to the latest DreamFactory code without having to worry about changes in the AMP stack. http://wiki.dreamfactory.com/DreamFactory/Installation#Windows

**Comment by cosmocracy** [comment]
@drewpearce Cool! Thank you, neat feature!  (Now I'm trying to figure out how far back to go version-wise... any guess as to whether this VC11/VC12 was introduced by 2.0.4 specifically or by a prior release?  Thanks again!

**Comment by drewpearce** [comment]
The latest you can go to (from Bitnami) is 2.0.2. Then you can update manually.

**Comment by drewpearce** [comment]
The latest version of Bitnami (2.0.4-1) is release and resolves this issue.

**Comment by cosmocracy** [comment]
Nice work! Looking forward to giving it a whirl!
