### ISSUE TITLE
Seeding: AppSeeder "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?

### ISSUE THREAD

**Issue by pcollinso** [dreamfactorysoftware/dreamfactory#240]
please can you list the files you modified to get this working.i downoaded the dreamfactory 3.0 beta and the issue still persist.i use composer 1.9.0 and php 7.3
on php artisan df:setup, after the migration the seeder stops at AppSeeder.please help me i am stuck

**Comment by wjgilmore** [comment]
Hi @pcollinso this is due to a breaking change found in PHP 7.3 pertaining to the continue statement. We are in the midst of updating the code to support PHP 7.3, however can confirm DreamFactory works very well on PHP 7.2 so in the meantime just downgrading PHP 7.2 will fix the issue.
