### ISSUE TITLE
Random "CORS / No ‘Access-Control-Allow-Origin’ header is present" after upgrading from DF 2.0.1 -> DF 2.0.4

### ISSUE THREAD

**Issue by bitperbit** [dreamfactorysoftware/dreamfactory#27]
Hi,

I think this is a new bug, After updating from ver 2.0.1 to 2.0.4 I receive a No 'Access-Control-Allow-Origin' header error, something like 3 times out of 5.
For example, this is what I get in the login request at the first try: 

> XMLHttpRequest cannot load http://v2.amicido.it:8080/api/v2/user/session. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost' is therefore not allowed access.

If I repeat the call it works. The CORS setup is setup to allow everything

![cors_issue](https://cloud.githubusercontent.com/assets/341188/12565308/42df27f2-c3b4-11e5-9abd-680b1838bd1e.PNG)

If I roll back to v 2.0.1 it works properly.
Please advise

**Comment by drewpearce** [comment]
Significant CORS issues resolved in 2.1
