### ISSUE TITLE
"HTTP/1.0 302 Found" in OAuth redirect, after upgrading to DF 2.1

### ISSUE THREAD

**Issue by meiti** [dreamfactorysoftware/dreamfactory#28]
After upgrading to DF 2.1, I get following error when I call http://test.com/api/v2/user/session?service=google

Error:
XML Parsing Error: not well-formed
Location: http://test.com/api/v2/user/session?service=google
Line Number 1, Column 5:HTTP/1.0 302 Found
----^

**Comment by drewpearce** [comment]
Can you provide more details? What tool/application are you using to make the call?

**Comment by meiti** [comment]
I think this issue is resolved in [https://github.com/dreamfactorysoftware/df-oauth/commit/b4bfaff05684d9772b2dd8b029f2ad6867f7a63c](url)

**Comment by drewpearce** [comment]
great. if not, comment back here with more details, and I'll reopen the issue.
