### ISSUE TITLE
can't get apache2 to run it on raspberry pi2

### ISSUE THREAD

**Issue by ScottChapman** [dreamfactorysoftware/dreamfactory#29]
I am running jessie on my raspberry pi2. I was able to do the install, and I can run locally as a service. But I am unable to figure out an appropriate apache2 config file for it.

The one on the wiki here for example refers to the wrong path, but even with the right one I can't get it served up...

Installed in /opt/dreamfactory

**Comment by drewpearce** [comment]
Not a bug, or not enough information provided to duplicate the error.

Help is available via forums, documentation, and directly contacting support. http://www.dreamfactory.com/support

If you believe this message is in error, please reopen the issue with more details.
