### ISSUE TITLE
Database (/dreamfactory/storage/databases/database.sqlite) does not exist.

### ISSUE THREAD

**Issue by jadedevin13** [dreamfactorysoftware/dreamfactory#30]
I can't seem to find the database.sqlite in that directory and Laravel complains about it. A .gitignore can be found in that directory.

**Comment by jadedevin13** [comment]
Creating a .env solve this and pointing to a local database and executing php artisan migrate solves this.

**Comment by drewpearce** [comment]
database.sqlite is the default system database. it is generated when you first run the DreamFactory setup (`php artisan dreamfactory:setup`, OR opening the DreamFactory setup page in your browser.) If you choose to use a different system database, then the check for this file is removed after you perform the migrations.
