### ISSUE TITLE
Feature requests. Memcache configuration

### ISSUE THREAD

**Issue by jadedevin13** [dreamfactorysoftware/dreamfactory#31]
I know you can manually configure memcache on Laravel but I hope there's a feature about it. But I guess it's on the enterprise edition >.<

**Comment by drewpearce** [comment]
I will open a feature request for this.
Please provide details of what you're looking for.

The other items (Multiple Role per User, User specific authentication) need to be their own separate issues with detailed explanations.

**Comment by philicious** [comment]
@drewpearce should be fixed with #63 and already in upcoming release
