### ISSUE TITLE
In post_process custom script the "event.response.content" is broken after updating from DF 2.0.4 -> DF 2.1.2

### ISSUE THREAD

**Issue by bitperbit** [dreamfactorysoftware/dreamfactory#32]
Hi,

In the version 2.1.2 in the post_process custom script the "event.response.content" is not reflecting the data pushed to it.

This is how the issue can be replicated:
- create a table "test" on a mysql database
- set a script for the post process "db._table.test.post.post_process", with this content:
```
event.response.status_code = 400;
event.response.content = {"test": "value"};
```

Push a record on the table. The expected result should be a 400 code response and {"test": "value"} as an output. 
Instead, the return code is modified correctly, but not the response.content, that will return always the original response.

Please advise.
Best regards

Gabriel

**Comment by juniorconte** [comment]
This topic seems to be related to this problem:

http://community.dreamfactory.com/t/how-to-create-users-while-registering-with-different-roles-via-api/2190/4

**Comment by leehicks** [comment]
When changing the content of the response in an event script, you will need to set event.response.content_changed = true before it will get copied back to the main process stream. This was to prevent copying content unnecessarily when handling events.
