### ISSUE TITLE
DF doesn't pass additional headers to the remote service

### ISSUE THREAD

**Issue by meiti** [dreamfactorysoftware/dreamfactory#33]
Hi,
I was using remote web services with no problems before upgrading to DF v2.1 (df-rws v0.2.0)
But in the last version of DF (df-rws) I can't pass additional header from server to the remote service.

Header name: Authorization
Header value: {myLookupKey}
Pass From Client: false
Verbs: 5 Selected

**Comment by drewpearce** [comment]
can you check vendor/dreamfactory/df-rws/src/CHANGELOG.md and verify that you are on version 0.2.0?

**Comment by drewpearce** [comment]
@meiti this is indeed a bug, and has been fixed.
You'll need to go through the standard update process outlined on the wiki.
The overall DF version number will not change, but your df-rws repo should be on version 0.2.2 (see vendor/dreamfactory/df-rws/src/CHANGELOG.md to confirm )
