### ISSUE TITLE
DF doesn't substitute private lookup key values

### ISSUE THREAD

**Issue by meiti** [dreamfactorysoftware/dreamfactory#34]
I have created a SQL DB service for connecting to SQL Server. When I use lookup keys I get the following error, But It works if I use values instead of lookup keys.

{"error":{"context":null,"message":"Failed to connect to database.\nConnection failed to open the DB
 connection: SQLSTATE[01002] Adaptive Server connection failed (severity 9)"

I have investigated the source code and think DF substitutes keys with ********** in connection string.

**Comment by drewpearce** [comment]
you're using a lookup for the user and password of the service or some other part of the service config?

What version of DreamFactory, precisely?

**Comment by df-arif** [comment]
This is fixed in dreamfactory/df-core develop. Will be available in dreamfactory/df-core 0.2.4 with dreamfactory/dreamfactory 2.1.1 release.
