### ISSUE TITLE
Can't change the primary key field when creating a schema.

### ISSUE THREAD

**Issue by juanmanavarro** [dreamfactorysoftware/dreamfactory#35]
- Create a table
- Push the key button of the example_field
- Save the table
- Create a string field
- Push the key button of the created field
- Try to update the table

It gives me this `SQLSTATE[42000]: Syntax error or access violation: 1068 Multiple primary key defined`

**Comment by MSchaer1985** [comment]
@juanmanavarro what is the error message you are seeing? I believe I confirmed this earlier and filed a bug. Are you seeing this with SQL server?

**Comment by juanmanavarro** [comment]
The error message is : *SQLSTATE[42000]: Syntax error or access 
violation: 1068 Multiple primary key defined*, and yes, I'm seeing this 
with a MySQL local server.|
|

**Comment by MSchaer1985** [comment]
@juanmanavarro assuming you want to update the second field created to be the primary key then yes I have confirmed this and will file a bug.

**Comment by drewpearce** [comment]
Restructure of Schema app has eliminated this issue
