### ISSUE TITLE
S3 File Service Cert Issue

### ISSUE THREAD

**Issue by HarveyEV** [dreamfactorysoftware/dreamfactory#36]
Bitnami Windows DF 2.1.0-4. S3 File Service cannot connect to S3 repo do to CA cert error:

DF Log Error:
`Failed to create container 'mycontainer345': Error executing "CreateBucket" on "https://s3.amazonaws.com/mycontainer345"; AWS HTTP error: cURL error 60: Peer certificate cannot be authenticated with given CA certificates  `

Update cacert.pem file referenced in the php.ini and still no luck.

**Comment by HarveyEV** [comment]
I found the location of the offending cacert.pem file.

C:\Bitnami\dreamfactory-2.1.0-4\php\PEAR\AWSSDKforPHP\lib\requestcore (or php dir south of your install directory).

Not it connects. Should update the cacert.pem file in the build.

**Comment by drewpearce** [comment]
The latest Bitnami builds have resolved this.
