### ISSUE TITLE
CURL cacheing Amazon S3 bucket name

### ISSUE THREAD

**Issue by cguerin** [dreamfactorysoftware/dreamfactory#37]
1. Create a Service for Amazon S3
2. Set the container name to an incorrect bucket name (example use an upper case name)
3. Try to access via Files -- you'll get an error creating the bucket.
4. Correct the container name to an existing or new bucket name that is correct.
5. Access it in Files -- it will show you the old URL 

No workaround except rebooting server.

**Comment by cguerin** [comment]
Btw - here's the error message mentioned in step 2.. attempting to connect to a bucket dreamfactorys3files with or without an existing bucket...same error

Failed to create container 'dreamfactorys3Files': Error executing "CreateBucket" on "https://s3-us-west-2.amazonaws.com/dreamfactorys3Files"; AWS HTTP error: Client error response [url] https://s3-us-west-2.amazonaws.com/dreamfactorys3Files [status code] 400 [reason phrase] Bad Request InvalidBucketName (client): The specified bucket is not valid. - <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidBucketName</Code><Message>The specified bucket is not valid.</Message><BucketName>

**Comment by drewpearce** [comment]
Latest release (2.1.2) does not exhibit this behavior. Likely due to upgrading the Amazon SDK that is used.
