### ISSUE TITLE
Azure Blob List Blobs Maximum

### ISSUE THREAD

**Issue by erikkurtu** [dreamfactorysoftware/dreamfactory#375]
I'm using DF 2.12.0 Silver. I have a DF Azure blob service that is getting a list of blobs from a directory.

The Azure blob service api returns a max of 5000 blobs per request. It is supposed to return a "NextMarker" element to enable subsequent requests if the total is greater than 5000, but that value is not returned in the DF api response.
https://docs.microsoft.com/en-us/rest/api/storageservices/List-Blobs

I'm looking for a way to modify my DF installation to either return the NextMarker or automatically combine multiple requests to return the total number of blobs.

Has this been addressed in later versions of DF? Is there a workaround I can do without upgrading?

Thanks

**Comment by erikkurtu** [comment]
I can see that adding getNextMarker() or getContinuationToken() somewhere around line 440 of https://github.com/dreamfactorysoftware/df-azure/blob/master/src/Components/AzureBlobFileSystem.php is probably what needs to get done to correct this.

@wjgilmore can you help?

**Comment by wjgilmore** [comment]
Hi @erikkurtu it is going to be somewhat more involved than adding these method calls. I am going to close this ticket as I see you are in correspondence with our support team so we can continue the conversation there.

**Comment by erikkurtu** [comment]
The support team said they couldn't do anything about this bug. Why would that be cause to close the issue? It'd be nice to have slightly more investment in addressing small but impactful bugs like this one.

If anyone else is facing this problem, the below worked for me. I modified the listBlobs function in /opt/dreamfactory/vendor/dreamfactory/df-azure/src/Components/AzureBlobFileSystem.php

I'm not a php programmer, so someone else might have a more elegant solution.

```
    public function listBlobs($container, $prefix = '', $delimiter = '')
    {
        $nextMarker = "";
        $totalOut = [];
        do {
            $this->checkConnection();
            $options = new ListBlobsOptions();
            $options->setMarker($nextMarker);
            if (!empty($delimiter)) {
                $options->setDelimiter($delimiter);
            }


            if (!empty($prefix)) {
                $options->setPrefix($prefix);
            }


            /** @var ListBlobsResult $results */
            $results = $this->blobConn->listBlobs($container, $options);
            $blobs = $results->getBlobs();
            $nextMarker = $results->getNextMarker();
            $prefixes = $results->getBlobPrefixes();
            $out = [];


            /** @var \MicrosoftAzure\Storage\Blob\Models\Blob $blob */
            foreach ($blobs as $blob) {
                $name = $blob->getName();
                if (0 == strcmp($prefix, $name)) {
                    continue;
                }
                $props = $blob->getProperties();
                $out[] = [
                    'name'             => $name,
                    'last_modified'    => gmdate(static::TIMESTAMP_FORMAT, $props->getLastModified()->getTimestamp()),
                    'content_length'   => $props->getContentLength(),
                    'content_type'     => $props->getContentType(),
                    'content_encoding' => $props->getContentEncoding(),
                    'content_language' => $props->getContentLanguage()
                ];
            }


            foreach ($prefixes as $blob) {
                $out[] = [
                    'name'           => $blob->getName(),
                    'content_type'   => null,
                    'content_length' => 0,
                    'last_modified'  => null
                ];
            }
            array_push($totalOut, ...$out);
        } while ($nextMarker != "");
        return $totalOut;
    }
```
