### ISSUE TITLE
Mapping bug in Data editor

### ISSUE THREAD

**Issue by cguerin** [dreamfactorysoftware/dreamfactory#38]
To reproduce..

1. In SQLLite db use Schema to create two tables with Primary keys.
2. Create a third table that maps the two primary keys as foreign keys so that you can create a Many to Many relationship.
3. Add some records to the first two tables.
4. Open up the mapping table in the editor.
5. The First data value you CAN select from the list of items to set it's ID to the ID in the mapping table.
6. The 2nd data value you CANNOT select from the list of items.

This makes Create or Edit operations impossible.

**Comment by cguerin** [comment]
Note,this item still open

**Comment by drewpearce** [comment]
Is this issue the same as https://github.com/dreamfactorysoftware/dreamfactory/issues/44 ?

**Comment by MSchaer1985** [comment]
@cguerin can you verify if this is the same issue referenced in #44?

**Comment by drewpearce** [comment]
but does not exist in latest release (2.2)
