### ISSUE TITLE
MS SQL table with image type column

### ISSUE THREAD

**Issue by alexgv99** [dreamfactorysoftware/dreamfactory#39]
When I try to access a table (HTTP GET) with a column type image returns the follow error message:
```javascript
{
  "error": {
    "context": null,
    "message": "The Response content must be a string or object implementing __toString(), &quot;boolean&quot; given.",
    "code": 500,
    "trace": [...]
   }
}
```

**Comment by drewpearce** [comment]
This should be fixed in the forthcoming release. If you need the changes immediately, you can switch to the develop branch of dreamfactory/df-core

**Comment by matthewblott** [comment]
This is an issue with Sqlite BLOB data type fields. I was pulling my hair out trying to find out what the issue was but then I removed these fields and the tables that wouldn't load would then load.
