### ISSUE TITLE
Filter SQL with in

### ISSUE THREAD

**Issue by maurodelazeri** [dreamfactorysoftware/dreamfactory#4]
I'm using the API in version 2.0 and am having trouble using IN in my sql, below the details...

![search](http://monosnapmauro.s3.amazonaws.com/monosnapmauro/DreamFactory_2015-09-25_11-50-38.png
) 

![Error](http://monosnapmauro.s3.amazonaws.com/monosnapmauro/DreamFactory_2015-09-25_11-51-04.png
)

![mysql table](http://monosnapmauro.s3.amazonaws.com/monosnapmauro/database.pluuft.com__localhost__pluuftDB__pf_imports__phpMyAdmin_4.0.10deb1_2015-09-25_11-51-47.png
)

**Comment by drewpearce** [comment]
using the filter this way
id in 1,3,4
returns correct results in latest code.

**Comment by maurodelazeri** [comment]
yes, it was fixed!!!
