### ISSUE TITLE
Mobile friendly confirmation enhancement

### ISSUE THREAD

**Issue by rjpalermo1** [dreamfactorysoftware/dreamfactory#40]
Problem:  DF current confirmation is not user friendly.  If user registers via mobile and are not sitting next to a computer they have to close current session, open email client, copy 36-char confirmation code, click on link to open browser, reenter their email address, create a password, and paste the confirm code.  If successful, then they need to close their browser, open the app again and enter their username and password once more.  That is way too much to expect users to complete to try your app - even a lot to ask users that want your app.

Here's the enhancement I would like to see:

In the User Service, the ability to either (1) use the sys generated confirm as is now or (2) let the system generate a code but allow me to specify length/charset (alpha/numeric/alphanumeric) or (3) allow me to create my own confirmation code in app that is stored and sent with the registration/confirmation email or (4) allow me to to require confirmation and put user in 'suspended' state until _my app_ or the user completes the confirmation.

I need (2) & (4).  If my app is on a mobile phone with service, the user will enter their mobile number on registration and using a 3rd party service will receive an SMS right away with a short 5 char number to authenticate.   For tablets, going to send a push notification with confirm code.  I would like to do this through a DSP service to make sure I capture the user info first, but if I can't get it to work I can do it outside the DSP then when complete send a registered user to DSP with confirm=FALSE and we're good.

But...I also need a fallback if they do not receive the SMS/push notice or didn't confirm for whatever reason.  So ideally the user registers uname/pw/phone like they do today and will still get a "welcome" email that has a URL deeplink confirm code that takes them to the DSP for evaluation.  If deeplink is expired or not there, the user is taken to an error page with remedial instruction (likely re-register).  If deeplink confirms token is good it pre-fills the receiving email address that is deep linked in the URL and asks them for their password.  

I am going to work around this with my own confirmation scheme for now, but thought this would be a compelling and needed feature in your DSP.  I'll let you know in the community forums how I integrate the 3rd part SMS service.  Of course there is twilio which should be easy enough to build a service for but not sure I want to pay the expense so searching alternatives...

**Comment by drewpearce** [comment]
This is filed as a Feature Request/Improvement, DF-742

Regarding #4 on your list, you can accomplish this using server side scripting. Simply do not set a default role for newly registered users.
Then write a post process script on user/register.
In the script check for if a confirmation code was included in the request payload (indicating it's a confirmation call, not a new registration call,) and check for a successful confirmation in the response.
If these are true you can make a call to system/user and set the role to whatever you wish.

**Comment by philicious** [comment]
@drewpearce I would like to second this Feature Req. 
Dealing with a similar situation here, facing same difficulties and having to roll our own double-opt-in solution as the confirmation system by DF isnt suitable for mobile users.

@rjpalermo1 could you link me to the forums post you mentioned?

**Comment by drewpearce** [comment]
This was resolved in the 2.3.1 release. See the following commits:
https://github.com/dreamfactorysoftware/df-admin-app/commit/1eba7a77dcf297d23b0978ba0793aa92773fb2be

https://github.com/dreamfactorysoftware/df-admin-app/commit/2e691b7047a81c3b5053192eb710aad93c394c66

https://github.com/dreamfactorysoftware/df-core/commit/f96afa63e2fff3c41cf162382d983a566555328a

https://github.com/dreamfactorysoftware/df-core/commit/a069bf091696ae568b0de02ef94add0fed444517

https://github.com/dreamfactorysoftware/df-user/commit/6b6bc5407c9dffd9c67c4a1b2962da598b9f8937

https://github.com/dreamfactorysoftware/df-user/commit/6d1d8d010c706d73208829aebc9a1cc52096d8c0

https://github.com/dreamfactorysoftware/dreamfactory/commit/fdfa93e24544f6d0fe5260cae97feea48a8d2067
