### ISSUE TITLE
Erro 404 /environment apache

### ISSUE THREAD

**Issue by odranoelBR** [dreamfactorysoftware/dreamfactory#42]
GET /api/v2/system/environment HTTP/1.1" 404 1362 "http://localhost/df2/public/dreamfactory/dist/index.html" 

After two clean install get the sabe problem.
On php built in server works fine, but on apache dont.

Help please \o/

**Comment by drewpearce** [comment]
Check out the wiki installation info for Apache: http://wiki.dreamfactory.com/DreamFactory/Installation/Linux/Apt#Apache

Additionally, our forums are a great way to get help http://community.dreamfactory.com
Or you can always contact support directly: http://www.dreamfactory.com/support

We like to reserve the GitHub issues for bugs. Thanks.
