### ISSUE TITLE
a bug about character "%"

### ISSUE THREAD

**Issue by onepiecewyz** [dreamfactorysoftware/dreamfactory#425]
hello, i meet a bug few day ago. when i GET the url (http://120.78.230.232:18504/api/v2/iplanner/_table/location/!!!), return HTTP status code 200.but when i GET the url(http://120.78.230.232:18504/api/v2/iplanner/_table/location/!!!%), HTTP status code 400, the difference is between "!!!" and "!!!%". why character "%" make this error. and i test the encoded chinese character (%E8%88%92%E5%8D%8E)，also return HTTP status code 404. i also test other character "$", "#", "&"and so on, all fine. now i am confuse about "%" .
my dreamfactory is installed by docker, and linux environment bases on ubuntu and nginx with default configure. 
![image](https://user-images.githubusercontent.com/21165646/129829731-3a5d7807-10a1-48de-afe5-54753f0165e3.png)
![image](https://user-images.githubusercontent.com/21165646/129829570-5b01a139-5ed4-4414-b392-fbd5263e1fd9.png)
![image](https://user-images.githubusercontent.com/21165646/129829984-0a36bb5a-afed-4ab7-b0aa-7f8527087094.png)

**Comment by wjgilmore** [comment]
Hi @onepiecewyz ,

The use of characters such as !!! in table names is highly unusual and is not supported by most database vendors. For instance SQL Server only allows alphanumeric characters. MySQL only allows alphanumeric characters in addition to _ and $. For these reasons it is very unlikely DreamFactory will deviate from standard table naming conventions, meaning it is unlikely special characters will ever be supported.

Thank you,
Jason

**Comment by onepiecewyz** [comment]
> Hi @onepiecewyz ,
> 
> The use of characters such as !!! in table names is highly unusual and is not supported by most database vendors. For instance SQL Server only allows alphanumeric characters. MySQL only allows alphanumeric characters in addition to _ and $. For these reasons it is very unlikely DreamFactory will deviate from standard table naming conventions, meaning it is unlikely special characters will ever be supported.
> 
> Thank you,
> Jason

hi, Jason: my major bug is not about "!!!" but "%". i meet 404 when characters contain "%"， that make me can not use chinese character in dreamfactory.

**Comment by onepiecewyz** [comment]
this issue is same as #192, so chinese character is supported now?
