### ISSUE TITLE
Related field editing not working.

### ISSUE THREAD

**Issue by cguerin** [dreamfactorysoftware/dreamfactory#44]
If I do thefollowing...

Create Table called for example Widget with a Unique ID and a Title
Create Table called say Components with a Unique ID and a Title
Create a many-to-many table called WidgetComponents with WidgetID and ComponentID

The user interface graciously offers to allow WidgetComponets to be edited with a drop down list mapping title to UniqueID, and offer st eh same for ComponentID.

However due to a bug in the data editing, you cannot edit the 2nd related item - -ComponentID.

It will not allow any modification whatsoever.

Try it.

**Comment by cguerin** [comment]
Any new on this? We're holding production deployment until this is fixed.

**Comment by cguerin** [comment]
Okay, guess we'll have to drop Dreamfactory... would be nice if someone responded someday... I posted this a month ago.

**Comment by leehicks** [comment]
Sorry that this got lost in the backlog, could you please detail what DF version you are using, what type of database you are using, and any details you can give us on the tables schema?

**Comment by cguerin** [comment]
Sure, this is DreamFactory Version: 2.1.1  -- hosted at dreamfactory.com

Database is the local SQL database, which I gather is SQLLite.

Basic schema is two tables that have unique iD's with a third mapping table mapping a Many-to-Many relationship simply by mapping ID in table 1 to the ID in table 2.

So lets say you have a table called Mapping which has table1_id and table2_id as the two fields in the mapping table, set...

table1_id as a REFERENCE to table1, field id as a foreign key
table2_id as a REFERENCE to table2, field id as a foreign key

if you try to use the DATA editor to to edit table1_id, no problem it is editable, if you try to edit the table2_id, it is IMPOSSIBLE to edit, it will not allow you to enter a value.

However if you use the REST interface to set it, it will work.

We were hoping to be able to use the DreamFactory GUI to make configuration easy.

**Comment by cguerin** [comment]
Any luck?

**Comment by drewpearce** [comment]
This has been resolved in a past release. Upgrading to latest should do the trick.
