### ISSUE TITLE
can't read from api docs fresh install DreamFactory 2.1.0-4-r05 (Ubuntu 14.04)

### ISSUE THREAD

**Issue by nvasilescu** [dreamfactorysoftware/dreamfactory#45]
I have installed on azure https://vmdepot.msopentech.com/Vhd/Show?vhdId=64108&version=66346 and after I login with the default user/password in api_docs you get an error button at the bottom and if you click it you will get {"schemaValidationMessages":[{"level":"error","message":"Can't read from file http://example.cloudapp.net/api/v2/api_docs"}]}

**Comment by drewpearce** [comment]
Thanks. This is a known bug. Should be resolved in the next release, and doesn't affect functionality of the rest of API Docs.

**Comment by nvasilescu** [comment]
means I can import apps from 2.0.4 from localhost in this azure deployment and all should work ? 

Thx.

**Comment by drewpearce** [comment]
should work just fine. this error message is unrelated.

**Comment by nvasilescu** [comment]
well it doesn't work because the config is not accesibile. It load half of the content and no buttons work.
![dreamfactory_problem](https://cloud.githubusercontent.com/assets/4938117/13634064/e0985108-e5fb-11e5-94f6-52147b956193.jpg)

**Comment by drewpearce** [comment]
subsequent conversation is unrelated to original bug posting, which is resolved in 2.1.1
