### ISSUE TITLE
Error in  Call to a member function getDefaultSchema() on null, using MS SQL. 

### ISSUE THREAD

**Issue by hiram033** [dreamfactorysoftware/dreamfactory#458]
Iam trying to install dream factory using MS SQL and iam getting the error: 

Seeding: AppSeeder

In BaseModel.php line 720:

  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Call to a member function getDefaultSchema() on null

Exception trace:
  at C:\inetpub\wwwroot\ArmasMasterIntegracionFull\vendor\dreamfactory\df-core\src\Models\BaseModel.php:720
 DreamFactory\Core\Models\BaseModel->DreamFactory\Core\Models\{closure}() at C:\inetpub\wwwroot\ArmasMasterIntegracionFull\vendor\laravel\framework\src\Illuminate\Cache\Repository.php:418
 Illuminate\Cache\Repository->rememberForever() at C:\inetpub\wwwroot\ArmasMasterIntegracionFull\vendor\laravel\framework\src\Illuminate\Cache\CacheManager.php:390
 Illuminate\Cache\CacheManager->__call() at C:\inetpub\wwwroot\ArmasMasterIntegracionFull\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php:261
 Illuminate\Support\Facades\Facade::__callStatic() at C:\inetpub\wwwroot\ArmasMasterIntegracionFull\vendor\dreamfactory\df-core\src\Models\BaseModel.php:721
 DreamFactory\Core\Models\BaseModel->getDefaultSchema() at C:\inetpub\wwwroot\ArmasMasterIntegracionFull\vendor\dreamfactory\df-core\src\Models\BaseModel.php:889
 DreamFactory\Core\Models\BaseModel->DreamFactory\Core\Models\{closure}() at C:\inetpub\wwwroot\ArmasMasterIntegracionFull\vendor\laravel\framework\src\Illuminate\Cache\Repository.php:418
 Illuminate\Cache\Repository->rememberForever() at C:\inetpub\wwwroot\ArmasMasterIntegracionFull\vendor\laravel\framework\src\Illuminate\Cache\CacheManager.php:390
 Illuminate\Cache\CacheManager->__call() at C:\inetpub\wwwroot\ArmasMasterIntegracionFull\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php:261
 Illuminate\Support\Facades\Facade::__callStatic() at C:\inetpub\wwwroot\ArmasMasterIntegracionFull\vendor\dreamfactory\df-core\src\Models\BaseModel.php:907
 DreamFactory\Core\Models\BaseModel->getTableSchema() at C:\inetpub\wwwroot\ArmasMasterIntegracionFull\vendor\dreamfactory\df-core\src\Models\BaseModel.php:698
 DreamFactory\Core\Models\BaseModel->getReferences() at C:\inetpub\wwwroot\ArmasMasterIntegracionFull\vendor\dreamfactory\df-core\src\Models\BaseModel.php:1327
 DreamFactory\Core\Models\BaseModel->getReferencingTable() at C:\inetpub\wwwroot\ArmasMasterIntegracionFull\vendor\dreamfactory\df-core\src\Models\BaseModel.php:1392
 DreamFactory\Core\Models\BaseModel->isRelationMapped() at C:\inetpub\wwwroot\ArmasMasterIntegracionFull\vendor\dreamfactory\df-core\src\Models\BaseModel.php:72
 DreamFactory\Core\Models\BaseModel::create() at C:\inetpub\wwwroot\ArmasMasterIntegracionFull\database\seeds\BaseModelSeeder.php:55
 BaseModelSeeder->run() at C:\inetpub\wwwroot\ArmasMasterIntegracionFull\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:36
 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() at C:\inetpub\wwwroot\ArmasMasterIntegracionFull\vendor\laravel\framework\src\Illuminate\Container\Util.php:37
 Illuminate\Container\Util::unwrapIfClosure() at C:\inetpub\wwwroot\ArmasMasterIntegracionFull\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:93
 Illuminate\Container\BoundMethod::callBoundMethod() at C:\inetpub\wwwroot\ArmasMasterIntegracionFull\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:37
 Illuminate\Container\BoundMethod::call() at C:\inetpub\wwwroot\ArmasMasterIntegracionFull\vendor\laravel\framework\src\Illuminate\Container\Container.php:590
 Illuminate\Container\Container->call() at C:\inetpub\wwwroot\ArmasMasterIntegracionFull\vendor\laravel\framework\src\Illuminate\Database\Seeder.php:134
 Illuminate\Database\Seeder->__invoke() at C:\inetpub\wwwroot\ArmasMasterIntegracionFull\vendor\laravel\framework\src\Illuminate\Database\Seeder.php:48
 Illuminate\Database\Seeder->call() at C:\inetpub\wwwroot\ArmasMasterIntegracionFull\database\seeds\DatabaseSeeder.php:20
 DatabaseSeeder->run() at C:\inetpub\wwwroot\ArmasMasterIntegracionFull\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:36
 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() at C:\inetpub\wwwroot\ArmasMasterIntegracionFull\vendor\laravel\framework\src\Illuminate\Container\Util.php:37
 Illuminate\Container\Util::unwrapIfClosure() at C:\inetpub\wwwroot\ArmasMasterIntegracionFull\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:93
 Illuminate\Container\BoundMethod::callBoundMethod() at C:\inetpub\wwwroot\ArmasMasterIntegracionFull\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:37
 Illuminate\Container\BoundMethod::call() at C:\inetpub\wwwroot\ArmasMasterIntegracionFull\vendor\laravel\framework\src\Illuminate\Container\Container.php:590
 Illuminate\Container\Container->call() at C:\inetpub\wwwroot\ArmasMasterIntegracionFull\vendor\laravel\framework\src\Illuminate\Database\Seeder.php:134
 Illuminate\Database\Seeder->__invoke() at C:\inetpub\wwwroot\ArmasMasterIntegracionFull\vendor\laravel\framework\src\Illuminate\Database\Console\Seeds\SeedCommand.php:63
 Illuminate\Database\Console\Seeds\SeedCommand->Illuminate\Database\Console\Seeds\{closure}() at C:\inetpub\wwwroot\ArmasMasterIntegracionFull\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Concerns\GuardsAttributes.php:129
 Illuminate\Database\Eloquent\Model::unguarded() at C:\inetpub\wwwroot\ArmasMasterIntegracionFull\vendor\laravel\framework\src\Illuminate\Database\Console\Seeds\SeedCommand.php:64
 Illuminate\Database\Console\Seeds\SeedCommand->handle() at C:\inetpub\wwwroot\ArmasMasterIntegracionFull\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:36
 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() at C:\inetpub\wwwroot\ArmasMasterIntegracionFull\vendor\laravel\framework\src\Illuminate\Container\Util.php:37
 Illuminate\Container\Util::unwrapIfClosure() at C:\inetpub\wwwroot\ArmasMasterIntegracionFull\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:93
 Illuminate\Container\BoundMethod::callBoundMethod() at C:\inetpub\wwwroot\ArmasMasterIntegracionFull\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:37
 Illuminate\Container\BoundMethod::call() at C:\inetpub\wwwroot\ArmasMasterIntegracionFull\vendor\laravel\framework\src\Illuminate\Container\Container.php:590
 Illuminate\Container\Container->call() at C:\inetpub\wwwroot\ArmasMasterIntegracionFull\vendor\laravel\framework\src\Illuminate\Console\Command.php:134
 Illuminate\Console\Command->execute() at C:\inetpub\wwwroot\ArmasMasterIntegracionFull\vendor\symfony\console\Command\Command.php:255
 Symfony\Component\Console\Command\Command->run() at C:\inetpub\wwwroot\ArmasMasterIntegracionFull\vendor\laravel\framework\src\Illuminate\Console\Command.php:121
 Illuminate\Console\Command->run() at C:\inetpub\wwwroot\ArmasMasterIntegracionFull\vendor\symfony\console\Application.php:1021
 Symfony\Component\Console\Application->doRunCommand() at C:\inetpub\wwwroot\ArmasMasterIntegracionFull\vendor\symfony\console\Application.php:275
 Symfony\Component\Console\Application->doRun() at C:\inetpub\wwwroot\ArmasMasterIntegracionFull\vendor\symfony\console\Application.php:149
 Symfony\Component\Console\Application->run() at C:\inetpub\wwwroot\ArmasMasterIntegracionFull\vendor\laravel\framework\src\Illuminate\Console\Application.php:93
 Illuminate\Console\Application->run() at C:\inetpub\wwwroot\ArmasMasterIntegracionFull\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php:131
 Illuminate\Foundation\Console\Kernel->handle() at C:\inetpub\wwwroot\ArmasMasterIntegracionFull\artisan:37

**Comment by thekevinm** [comment]
Thank you for opening an issue and testing out the software!

The reason you are seeing such a message is due to SQL Server being a licensed feature. Microsoft SQL Server is no longer supported in our open source license. 

To chat further please reach out to us at `dspsupport @ dreamfactory.com`
