### ISSUE TITLE
DF using deprecated PHP version 7.4. Please upgrade to 8.2

### ISSUE THREAD

**Issue by tvarsis** [dreamfactorysoftware/dreamfactory#459]
7.4 have gone EOL: [https://www.php.net/supported-versions.php](https://www.php.net/supported-versions.php)

This have made Bitnami to drop support for DF containers: #https://github.com/bitnami/containers/pull/17893

**Comment by matthewblott** [comment]
@tvarsis I've just downloaded the latest version, it runs with PHP 8

**Comment by tvarsis** [comment]
@matthewblott Yeah, they fixed it in version 5. But they are not that active in Github issues 😅
