### ISSUE TITLE
index.html in JavaScript Address Book Example Invalid XML Payload Error

### ISSUE THREAD

**Issue by thallstein** [dreamfactorysoftware/dreamfactory#46]
I'm going through the JavaScript sample program. When I open the file and try to save it having made no changes I get an xml payload error. I've attached a screenshot of the dialog box.
![javascript addressbook](https://cloud.githubusercontent.com/assets/17556436/13661221/afe509a8-e645-11e5-849f-91298c21b7f3.png)

**Comment by todda48** [comment]
This is a bug that we'll fix ASAP. The API used to allow creating a single record without the resource array wrapper. This is no longer allowed, and the JavaScript sample app needs to be changed to use the array format. You can fix it yourself by changing the AJAX calls to use array format.

{"name":"Joe"}     --->     {"resource":[{"name":"Joe"}]}

**Comment by carstenjacobsen** [comment]
The bug has been fixed and both the code in the repo and package have been updated.

**Comment by thallstein** [comment]
Hi Carsten,

I used Bitnami to install DreamFactory on AWS. Could you provide inx or point me to a link for how to update the AWS instance?

Thanks so much.

Trevor

**Comment by todda48** [comment]
http://wiki.dreamfactory.com/DreamFactory/Installation#Upgrade

**Comment by carstenjacobsen** [comment]
Hi Trevor,

The bug has been fixed and you can get the updated package from the repo
(or import it again from your instance):
https://github.com/dreamfactorysoftware/javascript-sdk/blob/master/add_javascript.dfpkg


Thanks,
Carsten

Carsten Jacobsen | Sr. Software Engineer | DreamFactory |t. 408.915.7815 |
@dfsoftwareinc | [image: DreamFactory] <http://www.dreamfactory.com/>

**Comment by thallstein** [comment]
Quick question - I deleted the app and then went to apps > import. When I proceed with the import I get an error message: "Failed to create records in 'contact'. SQLSTATE[23000]: Integrity constraint violation: 19 PRIMARY KEY must be unique

![import error](https://cloud.githubusercontent.com/assets/17556436/13792652/1f7e2ee8-eab0-11e5-85d7-a03df518e206.png)

**Comment by benbusse** [comment]
you probably need to drop the tables in the schema tab, then import the app again. when you import the app again, it's importing the schema, but if the schema is already there then you'll have collisions.

**Comment by thallstein** [comment]
Yah – I just did that. How does one import a 2nd example app? I wanted to look at the angular js example, but presumably it’s going to complain about this same thing.

**Comment by benbusse** [comment]
i believe each sample app uses the same schema (i.e. schema isn't namespaced for each example app). you can try importing a second one, but i think you need to drop the schema, then import the second app.
