### ISSUE TITLE
How to install firebird driver

### ISSUE THREAD

**Issue by snoopy86** [dreamfactorysoftware/dreamfactory#47]
Hi,

has anyone installed driver for Firebird in official docker?

I did it like that, but i don't see the driver inside DF.

RUN apt-get source php5
RUN find / -name "configure"
RUN cd /php5-5.6.17+dfsg/ext/pdo_firebird/ phpize
RUN ln -s /usr/include/php5 /usr/include/php
RUN git clone https://github.com/jbq/php5.git /tmp/git
RUN cp -a /tmp/git/ext/json /php5-5.6.17+dfsg/ext/
RUN /php5-5.6.17+dfsg/configure
RUN make
RUN make install
RUN echo "extension=pdo_firebird.so" >> /etc/php5/mods-available/pdo.ini

**Comment by drewpearce** [comment]
I am changing this to be a request for firebirdsql support.
Feature request filed.

**Comment by snoopy86** [comment]
I checked install modules and it looks like firebird is installed.

root@06ee81f0eed0:/opt/dreamfactory# php -m | grep Firebird
PDO_Firebird

But in the dropdown in DF i don't see it.

**Comment by drewpearce** [comment]
That's just the PHP driver. It still needs to be built as a supported database type within DreamFactory.

**Comment by drewpearce** [comment]
Firebird SQL support was added in the 2.6.0 release
