### ISSUE TITLE
can't export schema of tables. and can't import .dfpkg exported from 2.0.4 into 2.1.0

### ISSUE THREAD

**Issue by nvasilescu** [dreamfactorysoftware/dreamfactory#48]
1) I have a single table in 2.0.4, and if I check the user_details and user_details/* in mysql export schema, I get the following error : 
"error":{"context":null,"message":"Table 'user_details/' does not exist in the database.","code":404,"trace"

2) A dfpkg package is created without including the mysql schemas, but when I'm trying to import it into an azure instance (DreamFactory 2.1.0-4-r05 (Ubuntu 14.04)) I get : 
"Could not create the services.
Validation failed."

**Comment by nvasilescu** [comment]
same issue with exporting shcmea on 2.1.0

**Comment by df-jablan** [comment]
FYI: The next release will contain a variety of enhancements to the packaging system.

**Comment by Sun-Wukong** [comment]
After upgrading to 2.1.2, the import error for unzipping .dfpkg files persists.
