### ISSUE TITLE
Could not find Service - Problem with Apache VirtualHost

### ISSUE THREAD

**Issue by SoulTransfer** [dreamfactorysoftware/dreamfactory#49]
I create a new issue, as the error is slightly different and I think it might be a different problem.

When I created a virtualHost and tried to access dreamfactory I got the error: Could not find a service for dreamfactory.
I'm using the newest version of dreamfactory directly from the GitHub Repository.

Steps to reproduce:
1. Install XAMPP
2. Clone Dreamfactory Repo
3. Setup Dreamfactory Repo
4. Setup VirtualHost:
<VirtualHost *:80> ServerAdmin webmaster@example.com DocumentRoot "C:/DEV/xampp/dreamfactory/public" ServerName dreamfactory.localhost </VirtualHost>
5. Open URL http://dreamfactory.localhost
ERROR:
Could not find a service for dreamfactory

I also created a VirtualDirectory Alias to use instead of the VirtualHost.. and it works!

**Comment by df-jablan** [comment]
Did you start with an example VirtualHost configuration from the DreamFactory repository or did you roll your own?

The example configurations are (here)[https://github.com/dreamfactorysoftware/dreamfactory/blob/master/server/config/apache/etc/apache2/sites-available/dsp.local.conf].
