### ISSUE TITLE
DreamFactory 2.0 _schema POST creates wrong value for "required" field attribute

### ISSUE THREAD

**Issue by stcroppe** [dreamfactorysoftware/dreamfactory#50]
I am writing an app that creates dream factory tables for pre-existing data sets in another database format. For some reason my data record writes were failing. On further investigation it seems that dream factory is ignoring the POST request to set "required" to TRUE.

I am attaching a file with the dream factory log with relevant dump_var() output.

The file dumps the request content and what is returned by dream factory when the schema for the table is requested.

The relevant sections of the debug file are:

 ["required"] =>  bool(true) which appears in the _schema POST request and
 ["required"] =>  bool(false) which appears in the _schema.{table_name} response.

In every field record case, the required field is returned as the exact opposite of the value requested. For example:

**# POST (schema request) field record:**
   [0] =>
    object(Object)#1734488873 (6) {
      ["fixed_length"] =>
      bool(false)
      ["label"] =>
      string(14) "Test Entity_id"
      ["allow_null"] =>
      bool(false)
      ["name"] =>
      string(13) "testentity_id"
      ["type"] =>
      string(2) "id"
     ## **  ["required"] => bool(true)**
    }

**# GET (_schema.{tableName} request) field record:** 

[0] =>
    object(Object)#272133281 (30) {
      ["alias"] =>
      NULL
      ["name"] =>
      string(13) "testentity_id"
      ["label"] =>
      string(14) "Test Entity_id"
      ["description"] =>
      NULL
      ["type"] =>
      string(2) "id"
      ["db_type"] =>
      string(7) "integer"
      ["length"] =>
      NULL
      ["precision"] =>
      NULL
      ["scale"] =>
      NULL
      ["default"] =>
      NULL
     ## **  ["required"] =>  bool(false)**
      ["allow_null"] =>
      bool(false)
      ["fixed_length"] =>
      bool(false)
      ["supports_multibyte"] =>
      bool(false)
      ["auto_increment"] =>
      bool(true)
      ["is_primary_key"] =>
      bool(true)
      ["is_unique"] =>
      bool(false)
      ["is_index"] =>
      bool(false)
      ["is_foreign_key"] =>
      bool(false)
      ["is_virtual_foreign_key"] =>
      bool(false)
      ["is_foreign_ref_service"] =>
      bool(false)
      ["ref_service"] =>
      NULL
      ["ref_service_id"] =>
      NULL
      ["ref_table"] =>
      NULL
      ["ref_fields"] =>
      NULL
      ["ref_on_update"] =>
      NULL
      ["ref_on_delete"] =>
      NULL
      ["picklist"] =>
      NULL
      ["validation"] =>
      NULL
      ["db_function"] =>
      NULL
    }

Attachment...
[dreamfactory-post-schema-bug.txt](https://github.com/dreamfactorysoftware/dreamfactory/files/181548/dreamfactory-post-schema-bug.txt)

**Comment by leehicks** [comment]
@stcroppe The "required" field is actually a read-only calculated field in the schema, it is set to the equivalent of if required = !(allowNull || defaultValue || autoIncrement). 

I see that this bit of info was left out of the wiki and will try to get that updated asap. Sorry for any confusion.

**Comment by stcroppe** [comment]
OK so to force "required" a field needs to be:

a. Not allowed to be Null. Makes sense.
b. Not have a default value. May not make sense so presumably you use allowNull = true to override a required=true determination.
c. AutoIncrement is true implies system managing related field (typically an id) so essentially read only and I assume a POSTed value is ignored.

I think I've got it. Look forward to the doc update. Thanks for fast response.
