### ISSUE TITLE
Whitescreen on start using docker

### ISSUE THREAD

**Issue by telavancin** [dreamfactorysoftware/dreamfactory#500]
I followed the exact installtion instructions from this repository: https://github.com/dreamfactorysoftware/df-docker.git

But there are errors.

First everything seems working fine. In the client I get prompted to create a account but than i get a white screen.

Error in the client:
`GET
http://localhost/dreamfactory/dist/scripts/app.962c86a2.js
[HTTP/1.1 404 Not Found 23ms]

GET
http://localhost/dreamfactory/dist/scripts/app.962c86a2.js
[HTTP/1.1 404 Not Found 22ms]

Uncaught Error: [$injector:modulerr] Failed to instantiate module dreamfactoryApp due to:
[$injector:nomod] Module 'dreamfactoryApp' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

https://errors.angularjs.org/1.8.2/$injector/modulerr?p0=dreamfactoryApp&p1=%5B%24injector%3Anomod%5D%20Module%20'dreamfactoryApp'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttps%3A%2F%2Ferrors.angularjs.org%2F1.8.2%2F%24injector%2Fnomod%3Fp0%3DdreamfactoryApp%0AminErr%2F%3C%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A137798%0AsetupModuleLoader%2F%3C%2F%3C%2F%3C%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A154387%0Aensure%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A153406%0AsetupModuleLoader%2F%3C%2F%3C%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A153879%0AcreateInjector%2FloadModules%2F%3C%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A167441%0AforEach%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A138459%0AloadModules%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A167120%0AcreateInjector%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A171416%0AdoBootstrap%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A150586%0Abootstrap%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A151104%0AangularInit%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A149892%0A%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A458545%0AmightThrow%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A65059%0ADeferred%2Fthen%2Fresolve%2F%3C%2Fprocess%3C%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A65680%0AsetTimeout%20handler*Deferred%2Fthen%2Fresolve%2F%3C%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A65987%0Afire%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A62675%0AfireWith%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A63769%0Afire%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A63811%0Afire%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A62675%0AfireWith%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A63769%0Aready%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A68261%0Acompleted%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A2202%0AEventListener.handleEvent*%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A68473%0A%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A255%0A%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A271%0A
    minErr http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    loadModules http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    forEach http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    loadModules http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    createInjector http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    doBootstrap http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    bootstrap http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    angularInit http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    <anonymous> http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    mightThrow http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    process http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    setTimeout handler*Deferred/then/resolve/< http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    fire http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    fireWith http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    fire http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    fire http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    fireWith http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    ready http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    completed http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    EventListener.handleEvent* http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    <anonymous> http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    <anonymous> http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
vendor.b658ddac.js:1:137798
    minErr http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    loadModules http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    forEach http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    loadModules http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    createInjector http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    doBootstrap http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    bootstrap http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    angularInit http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    <anonym> http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    mightThrow http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    process http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    (Async: setTimeout handler)
    resolve http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    fire http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    fireWith http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    fire http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    fire http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    fireWith http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    ready http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    completed http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    (Async: EventListener.handleEvent)
    <anonym> http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    <anonym> http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    <anonym> http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
Uncaught TypeError: can't access property "get", $body.injector() is undefined
    <anonymous> http://localhost/dreamfactory/dist/index.html?session_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI5Mzk0MmU5NmY1YWNkODNlMmUwNDdhZDhmZTAzMTE0ZCIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Qvc2V0dXAiLCJpYXQiOjE3MDAxNTk5NzAsImV4cCI6MTcwMDI0NjM3MCwibmJmIjoxNzAwMTU5OTcwLCJqdGkiOiJqaHcwYW5hbGRZSkZvRjdIIiwidXNlcl9pZCI6MSwiZm9yZXZlciI6ZmFsc2V9.nkmletvbGHwAVorjIE8pkf5qZj9o-908h-07XO9em90:22
    setTimeout handler* http://localhost/dreamfactory/dist/index.html?session_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI5Mzk0MmU5NmY1YWNkODNlMmUwNDdhZDhmZTAzMTE0ZCIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Qvc2V0dXAiLCJpYXQiOjE3MDAxNTk5NzAsImV4cCI6MTcwMDI0NjM3MCwibmJmIjoxNzAwMTU5OTcwLCJqdGkiOiJqaHcwYW5hbGRZSkZvRjdIIiwidXNlcl9pZCI6MSwiZm9yZXZlciI6ZmFsc2V9.nkmletvbGHwAVorjIE8pkf5qZj9o-908h-07XO9em90:5
index.html:22:39`

Error in the server:
`[error] 56#56: *13 FastCGI sent in stderr: "PHP message: REST Exception #404 > Could not find a service for dreamfactory" while reading response header from upstream, client: 172.19.0.1, server: dreamfactory.local, request: "GET /dreamfactory/dist/scripts/app.962c86a2.js HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "localhost", referrer: "http://localhost/dreamfactory/dist/index.html?session_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI5Mzk0MmU5NmY1YWNkODNlMmUwNDdhZDhmZTAzMTE0ZCIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Qvc2V0dXAiLCJpYXQiOjE3MDAxNTk5NzAsImV4cCI6MTcwMDI0NjM3MCwibmJmIjoxNzAwMTU5OTcwLCJqdGkiOiJqaHcwYW5hbGRZSkZvRjdIIiwidXNlcl9pZCI6MSwiZm9yZXZlciI6ZmFsc2V9.nkmletvbGHwAVorjIE8pkf5qZj9o-908h-07XO9em90"
2023-11-16T18:39:31.782178130Z `

If i start using the docker image from docker hub everything worksfine.
docker pull dreamfactorysoftware/dreamfactory

**Comment by thekevinm** [comment]
Thank you for the report! Fixed with new release 5.4.1

**Comment by a-schulz** [comment]
Now it's the following error message, both when build locally and using the image from dockerhub.

Client:
````
Uncaught Error: [$injector:modulerr] Failed to instantiate module dreamfactoryApp due to:
[$injector:nomod] Module 'dreamfactoryApp' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

https://errors.angularjs.org/1.8.2/$injector/modulerr?p0=dreamfactoryApp&p1=%5B%24injector%3Anomod%5D%20Module%20'dreamfactoryApp'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttps%3A%2F%2Ferrors.angularjs.org%2F1.8.2%2F%24injector%2Fnomod%3Fp0%3DdreamfactoryApp%0AminErr%2F%3C%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A137798%0AsetupModuleLoader%2F%3C%2F%3C%2F%3C%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A154387%0Aensure%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A153406%0AsetupModuleLoader%2F%3C%2F%3C%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A153879%0AcreateInjector%2FloadModules%2F%3C%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A167441%0AforEach%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A138459%0AloadModules%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A167120%0AcreateInjector%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A171416%0AdoBootstrap%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A150586%0Abootstrap%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A151104%0AangularInit%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A149892%0A%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A458545%0AmightThrow%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A65059%0ADeferred%2Fthen%2Fresolve%2F%3C%2Fprocess%3C%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A65680%0A
    minErr http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    loadModules http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    forEach http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    loadModules http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    createInjector http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    doBootstrap http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    bootstrap http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    angularInit http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    <anonymous> http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    mightThrow http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    process http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
vendor.b658ddac.js:1:137798
    minErr http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    loadModules http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    forEach http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    loadModules http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    createInjector http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    doBootstrap http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    bootstrap http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    angularInit http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    <anonym> http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    mightThrow http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    process http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
Uncaught TypeError: can't access property "get", $body.injector() is undefined
    <anonymous> http://localhost/dreamfactory/dist/index.html?session_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI5Mzk0MmU5NmY1YWNkODNlMmUwNDdhZDhmZTAzMTE0ZCIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Qvc2V0dXAiLCJpYXQiOjE3MDA3MjI0NzMsImV4cCI6MTcwMDgwODg3MywibmJmIjoxNzAwNzIyNDczLCJqdGkiOiJROTQ0Y1BMaUdweklSZHBhIiwidXNlcl9pZCI6MSwiZm9yZXZlciI6ZmFsc2V9.YDdw26qiA2wsSh0y9Y_kHiuadqwT9MXE9vgVMbZwMVs:22
index.html:22:39
````
Server:
```
2023/11/23 06:54:34 [error] 54#54: *4 FastCGI sent in stderr: "PHP message: REST Exception #404 > Could not find a service for dreamfactory" while reading response header from upstream, client: 172.28.0.1, server: dreamfactory.local, request: "GET /dreamfactory/dist/scripts/app.962c86a2.js HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "localhost", referrer: "http://localhost/dreamfactory/dist/index.html?session_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI5Mzk0MmU5NmY1YWNkODNlMmUwNDdhZDhmZTAzMTE0ZCIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Qvc2V0dXAiLCJpYXQiOjE3MDA3MjI0NzMsImV4cCI6MTcwMDgwODg3MywibmJmIjoxNzAwNzIyNDczLCJqdGkiOiJROTQ0Y1BMaUdweklSZHBhIiwidXNlcl9pZCI6MSwiZm9yZXZlciI6ZmFsc2V9.YDdw26qiA2wsSh0y9Y_kHiuadqwT9MXE9vgVMbZwMVs"
```

**Comment by telavancin** [comment]
Now it's the following error message, both when build locally and using the image from dockerhub.

Client:
````
Uncaught Error: [$injector:modulerr] Failed to instantiate module dreamfactoryApp due to:
[$injector:nomod] Module 'dreamfactoryApp' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

https://errors.angularjs.org/1.8.2/$injector/modulerr?p0=dreamfactoryApp&p1=%5B%24injector%3Anomod%5D%20Module%20'dreamfactoryApp'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttps%3A%2F%2Ferrors.angularjs.org%2F1.8.2%2F%24injector%2Fnomod%3Fp0%3DdreamfactoryApp%0AminErr%2F%3C%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A137798%0AsetupModuleLoader%2F%3C%2F%3C%2F%3C%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A154387%0Aensure%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A153406%0AsetupModuleLoader%2F%3C%2F%3C%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A153879%0AcreateInjector%2FloadModules%2F%3C%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A167441%0AforEach%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A138459%0AloadModules%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A167120%0AcreateInjector%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A171416%0AdoBootstrap%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A150586%0Abootstrap%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A151104%0AangularInit%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A149892%0A%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A458545%0AmightThrow%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A65059%0ADeferred%2Fthen%2Fresolve%2F%3C%2Fprocess%3C%40http%3A%2F%2Flocalhost%2Fdreamfactory%2Fdist%2Fscripts%2Fvendor.b658ddac.js%3A1%3A65680%0A
    minErr http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    loadModules http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    forEach http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    loadModules http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    createInjector http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    doBootstrap http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    bootstrap http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    angularInit http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    <anonymous> http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    mightThrow http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    process http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
vendor.b658ddac.js:1:137798
    minErr http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    loadModules http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    forEach http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    loadModules http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    createInjector http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    doBootstrap http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    bootstrap http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    angularInit http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    <anonym> http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    mightThrow http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
    process http://localhost/dreamfactory/dist/scripts/vendor.b658ddac.js:1
Uncaught TypeError: can't access property "get", $body.injector() is undefined
    <anonymous> http://localhost/dreamfactory/dist/index.html?session_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI5Mzk0MmU5NmY1YWNkODNlMmUwNDdhZDhmZTAzMTE0ZCIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Qvc2V0dXAiLCJpYXQiOjE3MDA3MjI0NzMsImV4cCI6MTcwMDgwODg3MywibmJmIjoxNzAwNzIyNDczLCJqdGkiOiJROTQ0Y1BMaUdweklSZHBhIiwidXNlcl9pZCI6MSwiZm9yZXZlciI6ZmFsc2V9.YDdw26qiA2wsSh0y9Y_kHiuadqwT9MXE9vgVMbZwMVs:22
index.html:22:39
````
Server:
```
2023/11/23 06:54:34 [error] 54#54: *4 FastCGI sent in stderr: "PHP message: REST Exception #404 > Could not find a service for dreamfactory" while reading response header from upstream, client: 172.28.0.1, server: dreamfactory.local, request: "GET /dreamfactory/dist/scripts/app.962c86a2.js HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "localhost", referrer: "http://localhost/dreamfactory/dist/index.html?session_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI5Mzk0MmU5NmY1YWNkODNlMmUwNDdhZDhmZTAzMTE0ZCIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Qvc2V0dXAiLCJpYXQiOjE3MDA3MjI0NzMsImV4cCI6MTcwMDgwODg3MywibmJmIjoxNzAwNzIyNDczLCJqdGkiOiJROTQ0Y1BMaUdweklSZHBhIiwidXNlcl9pZCI6MSwiZm9yZXZlciI6ZmFsc2V9.YDdw26qiA2wsSh0y9Y_kHiuadqwT9MXE9vgVMbZwMVs"
```
