### ISSUE TITLE
Use of "size" in SQL DB schema not defined

### ISSUE THREAD

**Issue by stcroppe** [dreamfactorysoftware/dreamfactory#51]
In the SQL DB Service Specifics the example on this page: http://wiki.dreamfactory.com/DreamFactory/Features/Database/SQL

Shows the use of "size" instead of "length" in the JSON. Is this a bug or are they interchangeable?

Should this be discussed in the documentation?

Also related to Size. How is Integer actually managed. There are multiple integer types that can be used across systems and mixing them up can cause problems. The standard sizes are 16, 32 and 64 bit. Does dream factory default all integer settings to 64? SQL has these definitions:

TINYINT = 1 byte (8 bit)
SMALLINT = 2 bytes (16 bit)
MEDIUMINT = 3 bytes (24 bit)
INT = 4 bytes (32 bit)
BIGINT = 8 bytes (64 bit)

Is there a way to force the use of a specific integer size in the API?

**Comment by df-jablan** [comment]
Thanks, I've corrected the wiki page. `length` is what you want. `size` is no longer valid.

To answer your second question, integers are managed by the database, and sometimes by it's associated PHP driver. Whatever is returned from the query is passed on to the client without translation (aside from numeric casting). 

When creating schema, leaving off an integer length will default to the database's default length. With MySQL for instance, when an INT column is created without a length specified, it defaults to a length of eleven (11). 

> This number doesn't correlate 100% to bit length either. It's means that the integer can be up to eleven digits long (like 12,345,678,901). How many bits that is and the mechanism in which it's stored all happens in the database.

There isn't a way to force the returned integer size really. It depends on the database and driver. However, if you're creating a new table you can specify the `length` property in your POST payload, thus specifying the size. But that's just for `INT` types. 

At this time, you can use any of the SQL integer types (that you listed above) as well, when creating your schema. Adding a `length` property to the `type_extras` portion of the payload allows you to specify the the size. The code for this (MySQL) is [here](https://github.com/dreamfactorysoftware/df-core/blob/master/src/Database/Mysql/Schema.php#L98).

Hope that helps.

**Comment by stcroppe** [comment]
Hi Jerry

Many thanks for the response. That all makes sense.

Regards
Steve

Sent from my iPhone
Steve Cropper
+33 (0)6 68 22 42 49
