### ISSUE TITLE
Will this work on CentOS 7

### ISSUE THREAD

**Issue by m-menon** [dreamfactorysoftware/dreamfactory#52]
Will the install steps work on CentOS 7? Thanks

**Comment by reynot** [comment]
We use CentOS 7.1.1503 without issue.

Tim

**Comment by m-menon** [comment]
Cool thanks for confirming. So do I just follow the steps mentioned in the quick set up? Or will you be able to throw me a link or something. Thanks once again

**Comment by reynot** [comment]
We used to use a bitnami install but now follow the links in the setup.

**Comment by m-menon** [comment]
ok thanks a ton :+1:
