### ISSUE TITLE
Dreamfactory 2.1 bitnami install on Centos

### ISSUE THREAD

**Issue by m-menon** [dreamfactorysoftware/dreamfactory#55]
While meddling with an experimental installation, the user service was accidentally disabled. The message when trying to log in is

> Service user is deactivated

How to get around this problem? Which configuration file will I need to edit to get this back on?

After a bit of probing I saw this in the table called "service" in MySQL db.

    +-------------------------+-----------+
    | name                    | is_active |
    +-------------------------+-----------+
    | system                  |         1 |
    | api_docs                |         1 |
    | files                   |         0 |
    | db                      |         0 |
    | email                   |         0 |
    | user                    |         0 |
    | mysql                   |         0 |
    | mongodb                 |         1 |
    | scr-insert              |         1 |
    | testdb                  |         1 |
    | test-mlabs              |         1 |
    +-------------------------+-----------+

Can I just go ahead an issue an update statement to set 0 to 1, for 'user' service?

Btw I went ahead to try with setting the is_active to 1, but I still cannot login. My installation is a Bitnami install on Centos 7. Any pointers? thanks a ton

Thanks,
M&M

**Comment by drewpearce** [comment]
for anyone coming here after the fact, see https://github.com/dreamfactorysoftware/df-core/issues/10 for resolution.
