### ISSUE TITLE
OAuth (facebook) => 302 redirect instead of JSON response

### ISSUE THREAD

**Issue by antonellopasella** [dreamfactorysoftware/dreamfactory#56]
When authenticating on Facebook I receive a 302 Redirect instead of a JSON response I'm in a HTTP domain and the browser block me redirecting to HTTPS

Reading this post (http://blog.dreamfactory.com/using-dreamfactory-2.0-with-oauth-services) the expected response will be

`{
      "response": {
          "redirect": true,
          "url": "https://www.facebook.com/v2.4/dialog/oauth?client_id=15..."
       }
}`

Also http://wiki.dreamfactory.com/DreamFactory/Tutorials/Using_OAuth assert that
`POST https://your-url/api/v2/user/session?service=facebook`
response
`{
	"response": {
		"redirect": true,
		"url": "https://www.facebook.com/v2.4/dialog/oauth?client_id=123&redirect_uri=foo&scope=email&response_type=code"
	}
}`

**Comment by df-arif** [comment]
You would get the expected response as mentioned in the blog and wiki when you make the POST call to  https://your-url/api/v2/user/session?service=facebook using AJAX. If you are not using ajax and making that POST synchronously then it will redirect you to facebook's login page.

**Comment by antonellopasella** [comment]
This is my request and the response

`URL:https://df-*****.com//api/v2/user/session?service=facebook

REQUEST HEADERS
POST //api/v2/user/session?service=facebook HTTP/1.1
Host: df-********************.com
Connection: keep-alive
Content-Length: 0
Pragma: no-cache
Cache-Control: no-cache
Accept: application/json, text/plain, */*
X-Dreamfactory-API-Key: *****************
Origin: http://localhost:3000
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36
Referer: http://localhost:3000/
Accept-Encoding: gzip, deflate
Accept-Language: it-IT,it;q=0.8,en-US;q=0.6,en;q=0.4

RESPONSE HEADERS
HTTP/1.1 302 Found
Server: nginx/1.4.6 (Ubuntu)
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Cache-Control: no-cache
Location: https://www.facebook.com/v2.5/dialog/oauth?client_id=*********************
Access-Control-Allow-Origin: http://localhost:3000
Vary: Origin
Date: Fri, 08 Apr 2016 14:41:30 GMT
x-dreamfactory-routed: true
`

Chrome console error
`XMLHttpRequest cannot load https://df-***********.com//api/v2/user/session?service=facebook. The request was redirected to 'https://www.facebook.com/v2.5/dialog/oauth?client_id=**********', which is disallowed for cross-origin requests that require preflight.
`

I'm in a dreamfactory demo instance

**Comment by df-arif** [comment]
Ok, I see what's going on. On your request please set the header X-Requested-With = XMLHttpRequest.

**Comment by antonellopasella** [comment]
Yes, tested and it works.

Only an annotation, this is a standard AngularJS $http.post and it's made without X-Requested-With = XMLHttpRequest.

Maybe we need to update the doc

Thanks
