### ISSUE TITLE
Swagger Petstore example - API not loading fully in DF

### ISSUE THREAD

**Issue by thallstein** [dreamfactorysoftware/dreamfactory#57]
Hello. I thought a good way to check the DreamFactory Swagger stuff would be to see if the swagger.io petstore works. That swagger definition validates as okay on http://bigstickcarpet.com/swagger-parser/www/index.html and http://editor.swagger.io/#/.

I'm on DF admin 2.1.3 DF 2.1.0

Here's the link to the swagger definition on github, https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v2.0/json/petstore.json

I set up the remote web service and can call it. However, when I paste the petstore swagger definition into DreamFactory I don’t get all the calls stubbed out.

Example curl call and status okay w/ response:

$ curl -X GET --header 'Accept: application/json' --header 'X-DreamFactory-Api-Key: my_key' --header 'X-DreamFactory-Session-Token: my_token' 'http://127.0.0.1:8080/api/v2/petstore/store/inventory'
{"confused":1,"sold":80,"string":10,"pending":274,"available":3581,"Live":2,"fulfilled":1}

![swagger petstore should see](https://cloud.githubusercontent.com/assets/17556436/14406333/a5c72628-fe59-11e5-9149-f14f338e10d3.png)
![swagger petstore df incomplete](https://cloud.githubusercontent.com/assets/17556436/14406334/a5c9ca72-fe59-11e5-93b8-f4ee7106cfb5.png)

**Comment by benbusse** [comment]
Hey Trevor, we're looking into this issue today. Thanks for the heads up, we'll post when we have more info.

**Comment by leehicks** [comment]
I don't believe you are comparing apples to apples here. Look at the link you posted  https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v2.0/json/petstore.json

This definition isn't the same as what petstore.swagger.io uses, which is found here http://petstore.swagger.io/v2/swagger.json.

There may still be an issue importing that second link, looking into now.

**Comment by thallstein** [comment]
Using your version looks better but seems to still be incomplete. It stubs out "Pet" and "Store", but it does not stub out "user". Could this be a name conflict between the petstore swagger "user" namespace "user : Operations about user" and the DreamFactory "user" namespace, "user : Service for managing system users"?

I'm new to this .. so I may make uneducated (that's a nice way of saying "stupid") comments..

BTW - For the Petstore swagger file, would I need to update the base path in the swagger file to match my DreamFactory remote web service base path?

I.E., the swagger file from http://petstore.swagger.io/v2/swagger.json has "basePath": "/v2" and the base path entered in my remote web service is http://petstore.swagger.io/v2/

Would there be any other modifications that would need to be made to the swagger file to get it to work with the remote web service I set up?

Thanks in advance for the insights!

-Trevor

**Comment by leehicks** [comment]
I see the problem and will be working on a fix in the near future (wrapping up a sprint currently). The issue boils down to the service name you create not being prepended to the paths (should be automatic at import time). If you prepend "/{service.name}" in front of each path, and add {service.name} to the "tag" (that is the lookup format for service name) in each path in the file, it should get you most of the way there.

**Comment by thallstein** [comment]
I made those changes (name of the service is 'petstore') and the URL generated is looking correct. The issue I'm seeing now is that the cURL call generated via the API docs does not include the DreamFactory API Key or Token. That is:

The cURL box contains this:

curl -X GET --header 'Accept: application/xml' 'http://127.0.0.1:8080/api/v2/petstore/pet/findByStatus?status=sold'

However - I'm wondering how to get it to generate the headers X-DreamFactory-Api-Key and X-DreamFactory-Session-Token.

**Comment by drewpearce** [comment]
Resolved in 2.2
If you're curious, the api key that is displayed there is the api key for the App api_docs (from the apps tab.)
The session token is generated when you log in to the instance, and can be obtained manually from GET user/session.
