### ISSUE TITLE
Weird bug with service definition / JSON editor

### ISSUE THREAD

**Issue by philicious** [dreamfactorysoftware/dreamfactory#59]
When pasting Swagger JSON with `/n` in a string, it will be stripped.

Example
```
{
  "swagger" : "2.0",
  "info" : {
    "version" : "2.0",
    "title" : "News Service"
  },
  "paths" : {
    "/news" : {
        // foobar
      }
    },
    "/news/add" : {
      // blabla
```

DF will ALWAYS strip the `/n` on save. Even if being on the "Config" tab it will mess up already existing service definition. Its not happening with /fews /gews ...

As you can imagine this is reaaally annoying and took me an hour to figure out whats going on.

PS: a temp workaround is to write `//nnews` so it strip /n and leaves /news

**Comment by MSchaer1985** [comment]
@philicious This is fixed in develop branch. there was an errant string replace that removed all ‘/n’.

**Comment by todda48** [comment]
Just to clarify, fix is in develop branch of df-admin-app repo.
