### ISSUE TITLE
Installation failed. Please run the migration and seeder manually.

### ISSUE THREAD

**Issue by meiti** [dreamfactorysoftware/dreamfactory#6]
Hi,
I get following error message when I install dreamfactory 2.0 on wamp:

SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`dreamfactory`.`service`, CONSTRAINT `service_type_foreign` FOREIGN KEY (`type`) REFERENCES `service_type` (`name`) ON DELETE CASCADE) (SQL: insert into `service` (`name`, `label`, `description`, `is_active`, `type`, `mutable`, `deletable`, `last_modified_date`, `created_date`) values (db, Local SQL Database, Service for accessing local SQLite database., 1, sql_db, 1, 1, 2015-10-07 08:40:11, 2015-10-07 08:40:11))

**Comment by jstablesdf** [comment]
What is your install process? We haven't tested installation on a WAMP stack and don't have any WAMP stacks to test on. We've used [the Bitnami WAMP installers](https://bitnami.com/stack/dreamfactory/installer#windows) and they've worked fine.

**Comment by leehicks** [comment]
There was a migration bug in an earlier build with the default sql database. You can try again with the latest build, or re-run "php artisan migrate" and "php artisan db:seed" at the install root.

**Comment by fillup** [comment]
We have the same problem with a fresh build today using a fork of your Docker image. Running the db:seed command worked. Just FYI.
