### ISSUE TITLE
Services->Config-> Engine PHP doesnt work with opening tag <?php

### ISSUE THREAD

**Issue by philicious** [dreamfactorysoftware/dreamfactory#60]
When creating a custom service and using PHP as engine, your service wont work if it has `<?php` opening tag. The service will show the `Whoops, looks like something went wrong.` message instead.
I didnt test with `<?` short tag. 

Either warn users or strip it or ignore it. I suggest accepting it as a PHP script starts with that tag and people will write it.

**Comment by df-arif** [comment]
This is already addressed for the upcoming release. Service will work with or without the <?php tag.
