### ISSUE TITLE
Blank Screen After Install Without Errors

### ISSUE THREAD

**Issue by primesoftware** [dreamfactorysoftware/dreamfactory#62]
I just did a clean install of DF2 and I cannot seem to access the admin login. I point my browser to the index.php in the public folder but no good. All I get is a blank screen. My Apache logs have no errors and DF itself doesn't have any log files in the log directory. Database is there and so is admin user. Any ideas?

I've also pointed to login.html and tried using that form which only gives an error that /rave/auth/login could not be found. Also, why isn't that password line a password input? It shows password in plain view?

**Comment by MSchaer1985** [comment]
@primesoftware did you install following the directions [here] (http://wiki.dreamfactory.com/DreamFactory/Installation) Can you provide some more info here or post in the [forum] (http://community.dreamfactory.com/)?

**Comment by primesoftware** [comment]
@MSchaer1985 I can provide whatever would help to solve this problem, but the system just isn't giving much to post. When I access the dreamfactory public root I get redirected to dreamfactory/dist/index.html. Is that where the admin login is supposed to be? What other info would be of use? My php error log is empty as is Apache and Dream Factory logs is empty as well. The Dream Factory directory is writeable by Apache and has correct owner ship. Dream Factory is installed in /opt/df2. 

Yes, I did follow those directions. I also removed DF and reinstalled again just to be sure and I've got the same problem. Only difference is I see php5-mysql is called for, but my other packages need php5-mysqlnd. The database has been populated with tables so I don't think there is a MySQL (MariaDB) error.

**Comment by divanski** [comment]
My problem is the same.
500 (Internal Server Error) when try -  Request URL:http://izdravkov:90/api/v2/system/environment
Request Method:GET. This is on my console.
I change in env APP_DEBUG to true and error is "FatalErrorException in Grammar.php line 151:
Maximum function nesting level of '100' reached, aborting!"

**Comment by primesoftware** [comment]
I set DF_LOG_LEVEL to debug and still no log file nor error saying it couldn't be written.....

**Comment by divanski** [comment]
@primesoftware when I set to true - the page is blank but in Chrome(right click and choose  Inspect) in tab Network I see the error "environment" 500. When click on this - see the Headers and Preview.

**Comment by divanski** [comment]
@primesoftware I resolved !
In php.ini you can enable [xdebug]
and increase this - xdebug.max_nesting_level to 300 or more

**Comment by primesoftware** [comment]
@divanski I think we might have separate issues. I am not seeing this error 500 no matter what I do. Going to try out a different REST API that uses NodeJS....

**Comment by df-arif** [comment]
@primesoftware, can you share your apache virtualhost config?

**Comment by primesoftware** [comment]
Here ya go...
```
<VirtualHost *:80>
    ServerName domain.com
    ServerAlias www.domain.com
    ServerAdmin webmaster@domain.com
    DocumentRoot /srv/domain.com/public_html
    Alias /gameapi "/opt/df2/public/"

    RewriteEngine On
    RewriteCond %{HTTP_HOST} !^www\. [NC]
    RewriteCond %{HTTP_HOST} !^$
    RewriteRule ^/?(.*) http://www.%{HTTP_HOST}/$1 [L,R,NE]

    ErrorLog ${APACHE_LOG_DIR}/domain.com.error.log
    CustomLog ${APACHE_LOG_DIR}/domain.com.access.log combined

    php_flag log_errors on
    php_flag display_errors off
    php_value error_reporting 2147483647
    php_value error_log /srv/domain.com/logs/php.error.log
    php_value session.save_path "/srv/domain.com/sessions"
    php_value include_path ".:/usr/share/php:/usr/share/pear:/srv/domain.com/private"
    php_value open_basedir "/srv/domain.com:/usr/share/php:/usr/share/pear:/tmp:/opt/df2"


    <Directory /opt/df2/public>
        Options -Indexes +FollowSymLinks -MultiViews
        AllowOverride All
        AllowOverride None
        Require all granted
        RewriteEngine on
        RewriteBase /
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteRule ^.*$ /index.php [L]

        <LimitExcept GET HEAD PUT DELETE PATCH POST>
            Allow from all
        </LimitExcept>
    </Directory>
</VirtualHost>
```

**Comment by wizard97** [comment]
Same exact issue, blank page redirected to `dreamfactory/dist/index.html`. I'm using Laravel's Homestead, not sure what is going on.

**Comment by drewpearce** [comment]
DreamFactory generally works with PHP 7, though not all of the drivers have been vetted yet.

This error is usually caused by improper migration, or improper file permissions. If you turn on DEBUG mode in your .env file you can get more detailed information in your DreamFactory log.

Since this issue has not been determined to be a bug, but rather falls into the category of installation troubleshooting, please contact DreamFactory support directly ( http://dreamfactory/support ) or to the forums ( http://community.dreamfactory.com ).

We would like to reserve GitHub issues for reporting bugs and feature requests.
