### ISSUE TITLE
Setup misses config options for Redis/Memcache

### ISSUE THREAD

**Issue by philicious** [dreamfactorysoftware/dreamfactory#63]
The setup script https://github.com/dreamfactorysoftware/dreamfactory/blob/master/app/Console/Commands/Setup.php#L17 invoked via `php artisan dreamfactory:setup` misses config parameters for Redis (and likewise for Memcache as mentioned in #31, however I cant even find Memcache options in https://github.com/dreamfactorysoftware/dreamfactory/blob/master/.env-dist).
You can only set `--cache-driver` via the CLI installer. 
One can work around this for sure but its not convenient for unattended installs or with https://github.com/dreamfactorysoftware/df-docker

**Comment by df-arif** [comment]
Added memcached config in environment. Updated the setup command to accept redis and memcached config options. The changes are in develop branch. This should be available in next release.
