### ISSUE TITLE
NoSQL server side advanced filters

### ISSUE THREAD

**Issue by antonellopasella** [dreamfactorysoftware/dreamfactory#64]
"Advanced filters" are availables only to SQL database, there is no way to useit for noSQL database.

Is there a plan for these feature?

**Comment by drewpearce** [comment]
Is this in regard to Role Access?

**Comment by antonellopasella** [comment]
It's about this page (a picture is worth a thousand words :+1: )

![screenshot from 2016-04-28 11-55-12](https://cloud.githubusercontent.com/assets/96335/14882301/3fa087de-0d38-11e6-86c9-8dca18cb0c69.png)

**Comment by drewpearce** [comment]
Thanks. I've filed this as a feature request.
DF-378

**Comment by jkpadmanapan** [comment]
Hi Dreamfactory team,

is that enhancement completed? Our application facing authorization issue. that is one user can be able to see other users record. we can block unwanted record level access only by using Advanced filters method. Kindly finish this enhancement...

**Comment by drewpearce** [comment]
This item does not currently have an ETA.

**Comment by jkpadmanapan** [comment]
okay.. Please tell me how to handle below scenario. Our application facing high priority security issue. employee details are stored in one table. each and every row is belongs to one employee. I want to put record level access restriction to the employee table. It will be helpful for us if you suggest some other solution for this.

**Comment by drewpearce** [comment]
2.9 added support for advanced filters in roles for MongoDB. Other nosql options will be added on an individual request basis.
