### ISSUE TITLE
Cant save user

### ISSUE THREAD

**Issue by philicious** [dreamfactorysoftware/dreamfactory#65]
When saving a user, even if no field changed, I get
``` 
Multiple user-to-app-to-role assignment. You can only have a single user-to-app-to-role assignment.
``` 
However if I select "no role selected", I can save the user and then change the role back to what it was. However that workaround only working for a single app-to-role. I cant set multiple app-roles.

I also had a look here https://github.com/dreamfactorysoftware/df-core/blob/master/src/Models/UserAppRole.php#L47 and checked my table and its contents are 
```
mysql> select * from user_to_app_to_role;
+----+---------+--------+---------+
| id | user_id | app_id | role_id |
+----+---------+--------+---------+
| 16 |       7 |      4 |       1 |
+----+---------+--------+---------+
```

and when monitoring the network on save, I see `api/v2/system/user/7?fields=*&related=user_to_app_to_role_by_user_id,user_lookup_by_user_id` and the user_to_app_to_role_by_user_id object in JSON has exactly those ids. so according to the code, it should NOT throw that exception.

**Comment by df-arif** [comment]
Are you using MySql as your system db? If so, can you check to see if you are using the 'mysqlnd' driver? Run 'php -m' and check if you see 'mysqlnd' on this list. If you only see mysql but no mysqlnd then please install the mysqlnd (native driver) and then this should work. The mysql driver retrieves integer as string from database and therefore failing the check `$model->id !== ArrayUtils::get($data, 'id')` .

**Comment by philicious** [comment]
Hi @df-arif thx for the fast answer.
 I only have mysql and mysqli and the "bad" DF is the dockerized one from https://github.com/dreamfactorysoftware/df-docker/ 

The "good" DF is a plain install and I can confirm it indeed has mysqlnd available !

I'll open this issue on the df-docker repo then. It can be closed here I guess. 

(However you might wanna note this `mysqlnd`requirement down in the docs, either here http://wiki.dreamfactory.com/DreamFactory/Installation/Databases/MySQL or here http://wiki.dreamfactory.com/DreamFactory/Installation )

**Comment by df-arif** [comment]
@philicious, thank you! I have updated the wiki.

**Comment by philicious** [comment]
@df-arif and I can confirm it was indeed the missing mysqlnd. its working now !

**Comment by philicious** [comment]
for the sake of completness, my issue + PR on the other repo https://github.com/dreamfactorysoftware/df-docker/pull/15
