### ISSUE TITLE
[SOLVED] Refresh of SOAP service not working properly

### ISSUE THREAD

**Issue by philicious** [dreamfactorysoftware/dreamfactory#66]
I added some plugins which added more API endpoints to my SOAP service.

In my productive DF, with Redis Cache, the new endpoints showed up in API Docs when I flushed the Cache via "Config"

However in my sandbox DF with file cache, the API Docs doesnt update. Even worse, I created a new service with same WSDL URLbut that new service also doesnt list the new endpoints. 

Why ?

**Comment by df-arif** [comment]
Please check to make sure both storage/* and bootstrap/cache/* directories are writable by your web server. Also try running 'php artisan cache:clear' in the command line from your DF install root. If still doesn't work then try running 'sudo php artisan cache:clear'. If this works when using sudo but doesn't work otherwise then it must be a permission issue on either of those directories.

**Comment by philicious** [comment]
I can confirm that both directories are and were writable. 
I can also see the `storage/framework/cache/ `folder being emptied when flushing cache (both via UI and CLI) and the folder being filled up again when reloading API Docs page.
The `bootstrap/cache/` folder has compiled.php and services.php and they arent cleared nor refreshed.

I'm not even sure if it really has to do with the Cache but clearing the Cache solved it on the other DF install that used Redis Cache.
Maybe theres more going on in the background which I'm not aware of.

Whats really weird is that when I create new services but with the same SOAP URL, they have the same problem. So to me it seems as if the API endpoints are somehow stored in relation to the SOAP URL and not related to the service entity itself. 
I even tried deleting the service, flush cache, add the service again, flush cache -> still nothing.

**Comment by philicious** [comment]
@df-arif 
I now have the same problem on the DF with Redis Cache, so its not Cache backend related.

Scenario:
- Changed some SOAP parameter names on remote SOAP service (the XML definitely changed)
- Flush Cache in DF -> API Docs still shows old 
- Delete Service, flush cache, create service with new name, flush cache -> API Docs still not updated and API not working

If you could tell me whats involved and when service definitions are re-read, I might be able to debug this further. But right now I'm clueless

**Comment by philicious** [comment]
So after randomly restarting DF's webserver and flushing cache a dozen times, it suddenly reflected the changes in API Docs. I have no idea what made it work. But I fear there is something fundamentally broken with SOAP services

**Comment by df-arif** [comment]
Did you try clearing the browser cache as well?

**Comment by philicious** [comment]
@df-arif I now changed SOAP definition back and had to go thru all the hassle again. After 20 mins of restarting webserver, flushing cache over and over again, trying different browsers, clearing browser cache, it out of the sudden updated the API Docs again. Seems random to me. 

Clearing Browser Cache (Cookies/Cache..) didnt help. Also it has to be server-side as calls via CURL to the updated API error out by DF because it expects the outdated params.

**Comment by philicious** [comment]
@df-arif 
any update on this? 

I encounter this problem all the time I change the SOAP wsdl/wsi.
Unfortunately this prevents us (and others!) from using DF in production. 
Its not acceptable for production having to restart webserver over and over and flush cache dozen times to eventually convience DF to refresh the definition.

**Comment by philicious** [comment]
ugh.. I finally solved this. Its not exactly a bug within DF but it could be made more user-friendly.

So, I found in php.net manual that `php.ini` has `soap.wsdl_cache_enabled=1` and `soap.wsdl_cache_ttl=86400` (1d) by default. So I deleted `/tmp/wsdl-*` and Huzza! DF recognized the updated SOAP API.

I saw https://github.com/dreamfactorysoftware/df-soap/commit/aa707ea316eee5958136aff7e98196f1aa4b50b8 which should, in theory, allow setting Service Config Option `cache_wsdl=WSDL_CACHE_NONE` to permanently disable caching without touching php.ini 
(Its not in current release yet)

Additional to this upcoming code change I would suggest deleting /tmp/wsdl-* when doing a "Config->Cache->Flush system-wide Cache" or adding another button there or at SOAP service config page. As this problem is so not-obvious it will cost alot more nerves and hours for other people for sure.

**Comment by drewpearce** [comment]
Hey Phil, the code change you referenced above is live on the master branch of df-soap now, and should also be pulled into the latest master branch of the main repo.

I'm making this a feature request to clear the cache. DF-735

**Comment by opilags** [comment]
I also have this issue. My current workaround is to manually delete the cached WSDL file (/tmp/wsdl-*).
When this issue is going be fixed?

**Comment by drewpearce** [comment]
Resolved. https://github.com/dreamfactorysoftware/df-core/commit/2263a10766f5e0bfddc653e4c9079beb629bb3fb

**Comment by jaredrs** [comment]
Are there any potential negative effects of clearing the system cache in DF?

Am considering as we have some latent bugs that should be fixed according to the code and testing, but I'm nervous to flush it.
