### ISSUE TITLE
Schema field management buttons

### ISSUE THREAD

**Issue by shorstki** [dreamfactorysoftware/dreamfactory#69]
In schema admin panel I don't see "Save" button, there is only "Cancel" button which at first (on adding a field) works as a save, but on edit works as a cancel

Admin Application Version: 2.1.5
DreamFactory Version: 2.1.1

**Comment by drewpearce** [comment]
Filed as DF-736

**Comment by drewpearce** [comment]
This was resolved in DF 2.3 release.
