### ISSUE TITLE
Column order direction

### ISSUE THREAD

**Issue by trojanutilities** [dreamfactorysoftware/dreamfactory#70]
When ordering items by column "ASC/DESC" gets added to the column name and always orders ASC

**Comment by MSchaer1985** [comment]
@trojanutilities Can you please provide a little information such as how you are using ASC/DESC so I can attempt to replicate and file a bug if necesssary? When you say it gets added to the column name do you mean it gets added as field data in a column or as an actual type?

**Comment by trojanutilities** [comment]
Hi @MSchaer1985,

It can be reproduced on the API Docs when doing a GET and ordering by on of the columns. It gets added as the column name and throws an error i.e: "Column not found: 1054 unknown column 'id asc' in order clause..." 

Thank you,

**Comment by MSchaer1985** [comment]
Thanks @trojanutilities I have been able to replicate some of the behaviors you mentioned. Can you tell me the Database you are using?

**Comment by trojanutilities** [comment]
We are using mysql 5.7.10
Thanks

**Comment by MSchaer1985** [comment]
@trojanutilities Thanks, I have verified this behavior and will file a bug.

**Comment by elvisfernandes** [comment]
Any workaround for this while the bug is fixed? I'm still figuring out how to use pre-process scripts to circumvent this error. Any suggestions will be much appreciated.

**Comment by Matt2012** [comment]
Same issue - also using mysql 5.7

**Comment by drewpearce** [comment]
Fixed in 2.2
