### ISSUE TITLE
how to force "supports_inline_execution"

### ISSUE THREAD

**Issue by ivanlunardi** [dreamfactorysoftware/dreamfactory#71]
is there any way to force the "supports_inline_execution" to false in "custom scripting service" ?
Ivan

**Comment by leehicks** [comment]
In the service Config tab, "Additional Configuration" section, add an entry for name = supports_inline_execution and value = 0 or blank. (FYI A value of "false" (string false) actually gets interpreted as true due to a bug that will be fixed in the next release.)

**Comment by ivanlunardi** [comment]
thank you very much,
now it works.
Ivan
