### ISSUE TITLE
DF holding onto too many concurrent PostgreSQL connections.

### ISSUE THREAD

**Issue by crizzs** [dreamfactorysoftware/dreamfactory#72]
Is there a way to cut off idling DB connections to my remote PostgreSQL DB after certain time limit?

Thanks a bunch! :)

**Comment by drewpearce** [comment]
I was under the impression that the connections should close on their own. Are you not seeing that behavior?
Can you provide some more specifics of the issue, like how you determined the connections are remaining open?

Thanks.

**Comment by crizzs** [comment]
Sorry guys. You may close this thread. Dreamfactory is functioning well, I have isolated out the root of my problem.
Just a side question...Can the community version of dreamfactory scale across multiple servers?

**Comment by drewpearce** [comment]
Yes, it can. Check out the scalability guide. http://www.dreamfactory.com/publications/DreamFactory_Scalability_V4.pdf
