### ISSUE TITLE
[Feature Request] Git integration for Custom Services / Process Event Scripts

### ISSUE THREAD

**Issue by philicious** [dreamfactorysoftware/dreamfactory#74]
As of now, one can upload script files or copy/paste the code.

However, it would be quite convenient if DF could pull them from a Git repo via a "Pull" button beside the Browse File button.
Some config options would also be required, like specifying repo URL and optionally commit/branch, if master/HEAD isnt desired.

Also a global Git config would be needed for setting up repo access. However that might also be solved like Jenkins does it: relying on the system users id_rsa

Additionally some system/\* API endpoint for triggering a git pull/checkout for a service. 

This feature would help alot with integrating DF into (semi-)automated CI/CD pipelines and make DevOps / Ops quite happy :)

**Comment by philicious** [comment]
PS: same would apply for the swagger definitions

**Comment by benbusse** [comment]
great idea, logging a feature request now.

**Comment by drewpearce** [comment]
For cross referencing documentation's sake
DF-744 & DF-745

**Comment by jimijon** [comment]
+9999

**Comment by idnow-philicious** [comment]
@benbusse I've seen you added a basic git integration with 2.3.1 but its not much more helpful than uploading a file from your local machine.
So I'm wondering if you have a proper Git integration like suggested in this issue planned or are you done with your current implementation ?

**Comment by philicious** [comment]
@benbusse I've seen you added a basic git integration with 2.3.1 but its not much more helpful than uploading a file from your local machine.
So I'm wondering if you have a proper Git integration like suggested in this issue planned or are you done with your current implementation ?

**Comment by m1guelpiedrafita** [comment]
+1

**Comment by drewpearce** [comment]
This feature was added in 2.4.2
