### ISSUE TITLE
SoapFault response faultcode not passed through to client

### ISSUE THREAD

**Issue by philicious** [dreamfactorysoftware/dreamfactory#76]
When a SOAP call fails, DF only seems to passthrough the error message but not the code. However the code would be quite helpful.

Example SOAP response:
```
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
<SOAP-ENV:Body>
<SOAP-ENV:Fault>
<faultcode>104</faultcode>
<faultstring>Product type is not in allowed types.</faultstring>
</SOAP-ENV:Fault>
</SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

and the corresponding DF result
```
{
    "error": {
      "context": null,
      "message": "Product type is not in allowed types.",
      "code": 500,
      "trace": [.....]
   }
}
```
The `code` is always 500 and seems to come from DF. I'm not sure if that param should hold the SOAP faultcode or another param would be required.

**Comment by philicious** [comment]
Any ideas? 
A hint on where SOAP faults are handled would also help me so I can try to fix myself and PR.

**Comment by df-arif** [comment]
Hi @philicious, While we are working on this, you can look at this https://github.com/dreamfactorysoftware/df-soap/blob/develop/src/Services/Soap.php#L290 . The content of this function need to go inside a try catch block like below 

    protected function callFunction($function, $payload)
    {
        try {
            if (false === ($function = $this->doesFunctionExist($function, true))) {
                throw new NotFoundException("Function '$function' does not exist on this service.");
            }

            $result = $this->client->$function($payload);

            $result = static::object2Array($result);

            return $result;
        } catch (\SoapFault $e){
            throw new InternalServerErrorException($e->getMessage(), $e->faultcode);
        }
    }

**Comment by philicious** [comment]
@df-arif awesome. I just tried your suggested patch and its working excellent. 
(However I put the `try {` after the if block as `$this->doesFunctionExist` cant produce SoapFault imho)

As you already have a patch, I guess a PR isnt necessary. But lemme know if you would prefer to have one

**Comment by df-arif** [comment]
@philicious, Glad it worked for you. I would ask for your PR but we may need to address few other things with this change.

**Comment by philicious** [comment]
@df-arif just in case you missed it and for cross-reference, not pushing you guys ;) https://github.com/dreamfactorysoftware/df-soap/pull/2
