### ISSUE TITLE
Email Template

### ISSUE THREAD

**Issue by ivanlunardi** [dreamfactorysoftware/dreamfactory#80]
I try to send an email via post_process scripting using a template like this :

var payload = event.request.payload.resource[0]

var mail = {
  "template" : "test_template",
  "to": [
    {
      "name": payload.name,
      "email": payload.email
    }
  ],
  "from_name": payload.name,
  "from_email": payload.email,
  "reply_to_name": payload.name,
  "reply_to_email": payload.email,
  "name":"John",
  "link":"https://www.google.it/"
};
var result = platform.api.post("customEmailService", mail);

the email arrived empty.

Ivan

**Comment by drewpearce** [comment]
Can you share your template?
