### ISSUE TITLE
upgrade to version 2.1.2-1 - Oracle function call not working. (FetchMode has not been implemented)

### ISSUE THREAD

**Issue by MobileAppVault** [dreamfactorysoftware/dreamfactory#81]
Hi,

I followed the instruction on this page to get OCI Oracle connection working.
http://wiki.dreamfactory.com/DreamFactory/Installation/Databases/Oracle_DB

Everything works fine expect my function and procedures calls. I get the following response from all my calls.

```
{
  "error": {
    "context": null,
    "message": "Failed to call database stored procedure.\nsetFetchMode has not been implemented",
    "code": 500
  }
} 
```

The issue comes from: 

1.) \apps\dreamfactory\htdocs\vendor\dreamfactory\df-core\src\Database\Schema

**OracleSchema.php**
```
public function callFunction($name, &$params)
    {
...
if ($reader->nextResult()) {
            // more data coming, make room
            $result = [$result];
            do {
                $result[] = $reader->readAll();
            } while ($reader->nextResult());
...
}
```

2.) \apps\dreamfactory\htdocs\vendor\dreamfactory\df-core\src\Database

**DataReader.php**
```
public function nextResult()
    {
        if (($result = $this->statement->nextRowset()) !== false) {
            $this->index = -1;
        }

        return $result;
    }
```

**Comment by drewpearce** [comment]
I'm not seeing this problem in 2.1.2. Can you provide an example of the type of procedure you're using? Also, it is possible that this is resolved in 2.2.
