### ISSUE TITLE
Unknown relationship: app_lookup_by_app_id

### ISSUE THREAD

**Issue by monodesigns** [dreamfactorysoftware/dreamfactory#83]
After installing DreamFactory and attempting to load it in my browser, I get a blank white screen. After digging through the Network tab of Chrome, I'm getting a 400 error when trying to load "environment". The returned message is "Unknown relationship: app_lookup_by_app_id".

Environment:
Windows 7
Apache 2.4.17
PHP 5.6.16
MySQL 5.7.9

**Comment by drewpearce** [comment]
Best guess is that you're running your DB with MyISAM, which does not support foreign key relationships. DB engine needs to be InnoDB.

**Comment by monodesigns** [comment]
That was the issue. Thank you very much, @drewpearce.
