### ISSUE TITLE
Question about SESSION_DRIVER

### ISSUE THREAD

**Issue by philicious** [dreamfactorysoftware/dreamfactory#84]
https://github.com/dreamfactorysoftware/dreamfactory/blob/master/config/session.php#L7-L17 is the only info I could find about `SESSION_DRIVER` .env config. Didnt find it in the wiki.

I'm wondering what the best (=most performant) choice would be (Certainly one of Memcache/Redis/APC) 
I'm using `CACHE_DRIVER=redis` and not sure if that already tells DF to also store sessions there or I would have to also set `SESSION_DRIVER=redis` ?
Where is the storage of the default  `array` driver? 

At least I can say there are no files in `storage/framework/sessions/` with `CACHE_DRIVER=redis`

**Comment by df-arif** [comment]
CACHE_DRIVER is separate from SESSION_DRIVER and DF2 uses array for it. This means session is not persistent and stays only in memory for a process run-time only. This makes DF2 completely stateless and easy to scale horizontally. DF2 uses JWT for Auth & Session management. See http://wiki.dreamfactory.com/DreamFactory/Features/Auth#JSON_Web_Token_.28JWT.29

**Comment by philicious** [comment]
@df-arif ah ok great, thx for clarification. I was wondering in regard of horizontal scalability and immutability.

yes I knew about JWT but was wondering if SESSION_DRIVER affected it in some way.

PS: have a df-docker PR upcoming for passing session related configs in :)
