### ISSUE TITLE
Expression NOW() not working  in DF 2.2

### ISSUE THREAD

**Issue by Paulodev** [dreamfactorysoftware/dreamfactory#85]
I am using DF 2.2 with Mysql database, but the expression is not working properly.
I am following the doc that is in the link below:
http://wiki.dreamfactory.com/DreamFactory/Features/Database/SQL-Field-Expressions

this is the payload that I am going:

```
    {
      "resource": [
        {
          "login": "login",
          "encrypted_password": {
            "expression": "MD5(12345)"
          },
          "created_at": {
            "expression": "NOW()"
          },
          "updated_at": {
            "expression": "NOW()"
          }
        }
      ]
    }
```
but the bank fields are created as follows

```
    {
      "resource": [
        {
          "login": "login",
          "encrypted_password": "MD5(12345)"
          "created_at": "0000-00-00 00:00:00"
          "updated_at": "0000-00-00 00:00:00"
        }
      ]
    }
```
debugging the mysql logs the following SQL being sent by DF:

`insert into `users` (`login`, `encrypted_password`, `created_at`, `updated_at`) values ('login', 'MD5(12345)', 'NOW()', 'NOW()')`

and when I remove the quotes of command NOW() and MD5() of
sql command it performs correctly, however via DF not

**Comment by MSchaer1985** [comment]
Thanks @Paulodev I am testing now and verifying a few things.

**Comment by MSchaer1985** [comment]
Verified bug: DF-799 @Paulodev

**Comment by Paulodev** [comment]
Thanks @MSchaer1985 for atenttion

**Comment by MSchaer1985** [comment]
View commit in develop branch here:https://github.com/dreamfactorysoftware/df-sqldb/commit/49a429ab093d037f123782257494a497fe6907da
