### ISSUE TITLE
DF 2.2: "Scripts" event verb isnt marked yellow anymore

### ISSUE THREAD

**Issue by philicious** [dreamfactorysoftware/dreamfactory#88]
When having a custom event script, the path is marked yellow-ish so you can easily see where you are having custom event "hooks".
However since DF 2.2, only the service and enpoint are marked yellow but the verb (POST/GET/PUT..) isnt marked anymore. 

This is a minor UX bug I'd say.

**Comment by jimijon** [comment]
It might be minor, however, it really hurts UX navigation at the verb level. Anyway, it should be trivial to fix back again.

**Comment by philicious** [comment]
This seems to be working again. Likely also was caused by outdated commercial files. Same as with #89 

Outdated file had df-admin-app 2.2.0 and now its 2.2.1

**Comment by leehicks** [comment]
The latest dreamfactory/df-admin-app (2.2.3) has this fixed. It shipped with the latest dreamfactory build (2.2.1) over the weekend.

**Comment by philicious** [comment]
@leehicks haha ok. perfect then :) didnt notice the 2.2.1 release yet !

**Comment by philicious** [comment]
confirmed to be fixed with 2.2.1
