### ISSUE TITLE
DF 2.2: "Files" doesnt show AWS S3 bucket anymore 

### ISSUE THREAD

**Issue by philicious** [dreamfactorysoftware/dreamfactory#89]
Until 2.1.2 (df-filemanager-app 0.1.1 / df-aws 	0.2.2 ), the "Files" would show AWS S3 service. 

Since 2.2 (df-filemanager-app 0.1.1 / df-aws 	0.3.0), the S3 service isnt shown anymore. However its working as I get a file-list via API Docs

PS: As I did an upgrade from 2.1.2 -> 2.2, I also re-created an S3 service to make sure its not about some migration problem. Same problem tho

**Comment by jimijon** [comment]
I just started using this and found I could get a listing of my bucket's folders, and given a path to a folder to its contents. However, when I put the path to an individual file it said it could not find it.

**Comment by philicious** [comment]
@jimijon I'm not sure your trying the same thing. I mean this here
![files_nofiles](https://cloud.githubusercontent.com/assets/404412/16358495/508664e2-3b14-11e6-9306-bc5055e46796.PNG)

Its empty. But up to DF 2.1.1 it looked like so 
![files_good](https://cloud.githubusercontent.com/assets/404412/16358509/b9d48f28-3b14-11e6-9861-90149ad1eb5e.PNG)
 where the `xxxxx-media` is an S3 service / bucket and the `files` is the local file storage of DF

so @jimijon you might have to open up a separate issue

**Comment by philicious** [comment]
@drewpearce do you know anything about this? Will there be a fix ? thx for info

**Comment by todda48** [comment]
@philicious This was fixed in df-filemanager-app 0.1.2. This was included in the 2.2 release, just tried it with a Bitnami install. Try running the command  'composer update dreamfactory/df-filemanager-app'.

**Comment by philicious** [comment]
@todda48 
huh.. weird. I did build a df-docker based 2.2 image +the commercial composer files. 
(`RUN git checkout tags/2.2.0` + COPY commercial license )
I guess 0.1.2 wasnt available at that point yet ? Otherwise `"dreamfactory/df-filemanager-app": "~0.1.0"` should have installed the 0.1.2, no ?!

**Comment by philicious** [comment]
@todda48 I might found the culprit. In the composer.lock that I got by you guys it reads

```
            "name": "dreamfactory/df-filemanager-app",
            "version": "0.1.1",
            "source": {
                "type": "git",
                "url": "https://github.com/dreamfactorysoftware/df-filemanager-app.git",
                "reference": "ef8b240ea9aad44184701fb7566d2c0877462d2f"
            }
```
whioch basically pins the version to 0.1.1 and that particular commit

**Comment by philicious** [comment]
thx @drewpearce @todda48 , it was indeed the outdated composer.lock file which caused this
