### ISSUE TITLE
Can't run a "new?" service.

### ISSUE THREAD

**Issue by jimijon** [dreamfactorysoftware/dreamfactory#91]
Ok I have created a role and opened it up. I even copied and pasted the "math" example in v8. But no matter what I do or try, I get the same error message:

{"error":{"context":null,"message":"Role not found.","code":404}}

**Comment by df-arif** [comment]
Make sure that the role you opened up is set as the default role for the app that you are using the API key of. Or if you are using both API key and session token (using a valid user) then make sure your user has this role assigned for this app.

**Comment by jimijon** [comment]
I wasn’t too smart. I had copied the api_key from a previous window not knowing that was for a different instance. 
That ate up a day. Thanks for the sanity check.
