### ISSUE TITLE
Remote Web Service ignores CURL options

### ISSUE THREAD

**Issue by philicious** [dreamfactorysoftware/dreamfactory#92]
When calling a Remote Web Service (RWS) via script

```
$platform['api']->post->__invoke("wordpress/posts", json_encode($data));
```
the content-type results in `Content-Type: application/x-www-form-urlencoded`

however I need the content-type to be `application/json` so I tried setting RWS->Config->CURL options `CURLOPT_HTTPHEADER ` to `Content-Type: application/json` but that seems to be ignored.

I also tried setting RWS->Config->Headers and adding content-type there without any luck. (The Headers do seem to work somehow as my configured  `Authorization` header is sent with the request)

PS: the wiki is a bit misleading here http://wiki.dreamfactory.com/DreamFactory/Features/Scripting#Adding_headers_or_other_cURL_options_to_api_calls
It leaves the impression as if the curl options would work with any API call. but its only used with external calls starting with http or https. As seen here https://github.com/dreamfactorysoftware/df-core/blob/master/src/Scripting/BaseEngineAdapter.php#L352

**Comment by philicious** [comment]
Example code working, using external API call with supplied $options
```
        $data = [
            'title' => $payload['postTitle'],
            'content' => $payload['postContent'],
            'categories' => [2]
        ];
        $options = [
            'CURLOPT_HTTPHEADER' => [
                'Content-type: application/json',
                'Authorization: Basic {wordpress_application_pass}'
            ]
        ];
        $res = $platform['api']->post->__invoke("http://foobar.de/wp-json/wp/v2/posts", json_encode($data), $options);
```

Not working, using internal RWS service named "wordpress" and configured "CURL options" for content type and additionally as "Headers":
```
        $data = [
            'title' => $payload['postTitle'],
            'content' => $payload['postContent'],
            'categories' => [2]
        ];
        $res = $platform['api']->post->__invoke("wordpress/posts", json_encode($data));
```

**Comment by df-arif** [comment]
@philicious, Just tried doing a similar thing and it works for me using RWS Headers. Make sure that the "Pass From Client" checkbox is NOT checked. Checking this will pass the header value from your client overwriting your specified value.

**Comment by philicious** [comment]
@df-arif ok. I will retry when I'm on 2.2. Still on 2.1.2 as other (regression) bugs prevent me from upgrading

**Comment by philicious** [comment]
@df-arif I can confirm its working now. Tested with 2.2.1
