### ISSUE TITLE
Can't access S3 file.

### ISSUE THREAD

**Issue by jimijon** [dreamfactorysoftware/dreamfactory#93]
I can list out the files in my folder:

{
  "resource": [
    {
      "name": "product.json",
      "content_type": "application/octet-stream",
      "content_length": 32582,
      "last_modified": "2016-04-28T14:41:39+00:00",
      "path": "Label-Insight/product.json",
      "type": "file"
    },
    {
      "name": "output",
      "content_type": null,
      "content_length": 0,
      "last_modified": null,
      "path": "Label-Insight/output/",
      "type": "folder"
    }
  ]
}

However, when I run the get api with filepath, it responds with:

The requested URL /api/v2/nowfinds3/Label-Insight/product.json   can't be found.

**Comment by carstenjacobsen** [comment]
Are you trying from a script or from API Docs?

If it's from API Docs there is a limitation, it doesn't work for subfolders. It would work for **nowfinds3/product.json** but not for **nowfinds3/Label-Insight/product.json**

**Comment by jimijon** [comment]
Ah, well that would be the answer. So, from the scripts it will work?

**Comment by carstenjacobsen** [comment]
Yes.

Another way to test your APIs is to use an application like Postman. You can do more advanced API testing with a tool like that.
