### ISSUE TITLE
Can't get contents of a file.

### ISSUE THREAD

**Issue by jimijon** [dreamfactorysoftware/dreamfactory#94]
For csv files I get null.
For a text file it returns some cut off response:  {"resource":{"sta

What gives? I can't believe I am the only one seeing this. They are all in files so I am not using S3 to try to eliminate other possible issues.

URGENT

**Comment by carstenjacobsen** [comment]
Is this from a script or the API Docs? Are you using our free hosted system or do you run it on your own system? 

I created a small CSV file, uploaded it to files and could retrieve it again using API Docs. I'm running our latest version, 2.2, are you doing the same?

**Comment by jimijon** [comment]
I am running 2.2. I am running it on our own EC2 server. This is from a service script.

All I get is null. If I add a bad name it correctly tells me it can't find it.

**Comment by drewpearce** [comment]
Not a bug. Closing old issue.
