### ISSUE TITLE
"Packages->Export Package" timeout with AWS S3 service enabled

### ISSUE THREAD

**Issue by philicious** [dreamfactorysoftware/dreamfactory#95]
"Packages->Export Package" only shows `Loading...` in the "Type" combobox.

A network analysis shows the GET on `/api/v2/system/package` times out.

Additionally there is in dreamfactory.log

```
local.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Maximum execution time of 30 seconds exceeded in /opt/dreamfactory/vendor/aws/aws-sdk-php/src/Api/Parser/XmlParser.php:132
```

If you try that endpoint in API Docs you also get

```
<html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.9.12</center>
</body>
</html>
```

When setting the AWS S3 service to "inactive", the request returns almost immediately.

Environment:
Tested on DF 2.1.2 with aws-sdk-php 3.18.3 and df-aws 0.2.2 
aswell as
DF 2.2.0 with aws-sdk-php 3.18.14 and df-aws 0.3.0

**Comment by philicious** [comment]
still the case with DF 2.2.1 with aws-sdk-php 3.18.27 and df-aws 0.3.1

**Comment by philicious** [comment]
@drewpearce any feedback about this one?

**Comment by philicious** [comment]
@drewpearce anything about this one? its breaking the idea of exporting DF settings as a self-contained package if you cannot export S3 service and also cannot export anything else if its enabled

**Comment by philicious** [comment]
@MSchaer1985 this bug is still present in DF 2.3.0

**Comment by MSchaer1985** [comment]
@philicious I'll test and reopen the bug.

**Comment by philicious** [comment]
@MSchaer1985 I tested this again with DF 2.4.1 and the bug is fixed
