### ISSUE TITLE
DF 2.2 /2.2.1: API Docs broken for Custom Services

### ISSUE THREAD

**Issue by philicious** [dreamfactorysoftware/dreamfactory#96]
Since 2.2 the API Docs do prepend the swagger-based APIs with the services name, thus breaking them entirely in API Docs.

e.g. swagger
```
paths:
  /consumers:
    get:
....
```
service is also named `consumers` and DF now shows in API Docs `
GET /consumers/consumers ` instead of only `
GET /consumers` as it used to be. The same pattern applies for ALL endpoints !!

Therefore all curl requests are broken
```
Request URL
http://dreamfactory.app/api/v2/consumers/consumers

Result
    "message": "Invalid or missing resource name.",
```

fortuantely API itself is still working. However the broken API Docs is a major problem !

**Comment by leehicks** [comment]
Was this doc handwritten or imported from somewhere? Could you give me a list of just the paths? The 2.2 release now assumes the doc is from the point of a "service" view and attaches the service name to the beginning, BUT it is supposed to detect prior formats and not prepend if all paths already started with the service name.

**Comment by philicious** [comment]
@leehicks I'll shoot you an email with the swagger. Yes it was handwritten in swagger editor, so its syntactically correct, at least.
Ye ok I think I understand the new approach, however that would braek generating SDKs off the swagger as then the SDK would miss the service part...

**Comment by leehicks** [comment]
DreamFactory generates a "whole-system" swagger file including all of the services (this changed a bit when we upgraded to the swagger 2.0 spec from 1.2). A lot of people were importing or cut-n-pasting swagger defs written from a single service perspective into dreamfactory services. So now the input of definitions is from the service view (though as I mentioned it should handle the old way), but the output swagger contains all services and thus any SDK has all of the service defs.

**Comment by philicious** [comment]
(I started with 2.x releases.)

Well, what I meant was: If the solution would be to remove the service name from the swagger paths, so DF can prepend it. Then using this swagger with swagger-codegen to generate an SDK, then this SDK would miss the service name from all paths, rendering it useless/broken.
But see my email first before we get to deep :)

**Comment by philicious** [comment]
@leehicks any fix yet ? (Unfortunately this is quite an impediment for "my" dev-team)

**Comment by leehicks** [comment]
https://github.com/dreamfactorysoftware/df-core/commit/981f65723751cc6024eb57666f73cdfc67a5095e

Try that out. Works for the files you sent me.

**Comment by philicious** [comment]
@leehicks thx! see my mail with test results

**Comment by philicious** [comment]
fixed by @leehicks commit
