### ISSUE TITLE
DF 2.2.1: API Docs empty if SOAP service enabled

### ISSUE THREAD

**Issue by philicious** [dreamfactorysoftware/dreamfactory#97]
Having a SOAP service that used to display fine in API Docs up until 2.2. Now it seems to cause a problem leading to API Docs being empty, only showing ' fetching resource list: http://dreamfactory.app/api/v2/api_docs; Please wait.' 
 
The XHR on `api_docs` returns and I can see the SOAP service being present in the JSON `paths` object.

In the console, I can see an error not happening on my 2.2 installation
```
TypeError: property is null

[6]</Resolver.prototype.resolve()
 swagger-ui.js:2111
[3]</SwaggerClient.prototype.build/obj.on.response()
 swagger-ui.js:1331
[5]</SwaggerHttp.prototype.execute/responseInterceptor()
 swagger-ui.js:1822
[5]</SwaggerHttp.prototype.execute/obj.on.response()
 swagger-ui.js:1826
[5]</SuperagentHttpClient.prototype.execute/<()
 swagger-ui.js:2042
[162]</Request.prototype.callback()
 swagger-ui.js:24191
Request/<()
 swagger-ui.js:23821
[163]</Emitter.prototype.emit()
 swagger-ui.js:24633
[162]</Request.prototype.end/xhr.onreadystatechange()
```
There are no additional errors in dreamfactory.log

When disabling the service, the error is gone and API Docs is rendered. (However it doesnt show the service description anymore but thats rather a minor UX bug or even on purpose)

**Comment by leehicks** [comment]
See if this commit helps, it fixed a similar issue from another customer. It is also in the 0.3.2 tagged master branch.

https://github.com/dreamfactorysoftware/df-soap/commit/c121350db033420f15aa364fc43441a2351b0d2b

**Comment by philicious** [comment]
@leehicks thanks! I tried, didnt help, check my email with further info for you to test/debug

**Comment by philicious** [comment]
ah and I got this in logs:

looks like that switch in `soapType2ApiDocType` function needs a few more cases

```
local.ALERT: SOAP to Swagger found unknown type: int
local.ALERT: SOAP to Swagger found unknown type: ArrayofString
local.ALERT: SOAP to Swagger found unknown type: ArrayOfBoolean
```

**Comment by philicious** [comment]
fixed with https://github.com/dreamfactorysoftware/df-soap/commit/36b991d9ec8fe0bab2068b88d59ebfa2fbe300b1
