### ISSUE TITLE
Only one RemoteWebService call working per endpoint if using HTTP Headers

### ISSUE THREAD

**Issue by philicious** [dreamfactorysoftware/dreamfactory#99]
so this is a really funny bug. however its really breaking RWS functionality

if you have a RWS, and you configured "Headers" for it, only the **FIRST** RWS call from within an service endpoint will work. 
The second one to same service will have the headers duplicated, the 3rd one will have them 3 times etc..

Example:
RWS service `rws_service_name` has Authorization and Content-Type Headers set
```
$res = $platform['api']->post->__invoke("rws_service_name/some/path", json_encode($data));

$res = $platform['api']->post->__invoke("rws_service_name/other/path", json_encode($data));
```

tcpdump:

```
# first call 
POST /some/path HTTP/1.1
Host: api.acme.com
Accept: */*
Authorization: Basic FooBar
Content-Type: application/json
Content-Length: 142

# second call
POST /other/path HTTP/1.1
Host: api.acme.com
Accept: */*
Authorization: Basic FooBar
Content-Type: application/json
Authorization: Basic FooBar
Content-Type: application/json
Content-Length: 142
```

Only the first call will work, the others are failing with 400 because of duplicate header fields

**Comment by leehicks** [comment]
So it looks like you are calling these back to back inside a PHP script service, correct?
I tested calling the rws directly and having it dump to something like requestb.in with no luck, works as expected. I also tried calling rws back to back from a PHP script, still no luck reproducing header issue.
Are the headers in rws set directly or is "Pass From Client" selected?

**Comment by leehicks** [comment]
Reproduced, scripting context is not clearing from earlier call. Will file it and get a fix soon.

**Comment by philicious** [comment]
Not sure what you mean with "back to back". But  you reproduced it anyways already :+1: 

And yes, it's consecutive calls from a php custom scripting service to a RWS. Doesn't matter if there is more code between the calls. 
Also call to same or different  RWS path doesn't make a difference.

**Comment by leehicks** [comment]
Fix is in develop branch of [dreamfactory/df-rws](https://github.com/dreamfactorysoftware/df-rws/commit/afaad1051d652182498b52f7a70e44fad3bca8b1). Try it out and let me know if you see further issues.

**Comment by philicious** [comment]
@leehicks quickly tested your fix and its working: Headers arent "multiplied" anymore :+1:
